### ISSUE TITLE
0.12.4 - autoprefixer is not a function TypeError

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil#1055]
**Stencil version:**

```
C:\ae\adaept.com\ae-svg-components>npm list @stencil/core
ae-svg-components@0.12.4 C:\ae\adaept.com\ae-svg-components
`-- @stencil/core@0.12.4
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Try to run.
Build fail. Cannot deploy new version to site.
```
C:\ae\adaept.com\ae-svg-components>npm start

> ae-svg-components@0.12.4 start C:\ae\adaept.com\ae-svg-components
> npm run dev


> ae-svg-components@0.12.4 dev C:\ae\adaept.com\ae-svg-components
> stencil build --dev --watch --serve


[ ERROR ]  autoprefixer is not a function TypeError: autoprefixer is not a function at Object.<anonymous>
           (C:\ae\adaept.com\ae-svg-components\stencil.config.ts:31:23) at Module._compile (module.js:652:30) at
           Object.require.extensions..js
           (C:\ae\adaept.com\ae-svg-components\node_modules\@stencil\core\dist\sys\node\index.js:766:20) at Module.load
           (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at
           Module.require (module.js:596:17) at require (internal/module.js:11:18) at requireConfigFile
           (C:\ae\adaept.com\ae-svg-components\node_modules\@stencil\core\dist\sys\node\index.js:773:20) at
           loadConfigFile (C:\ae\adaept.com\ae-svg-components\node_modules\@stencil\core\dist\sys\node\index.js:717:32)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ae-svg-components@0.12.4 dev: `stencil build --dev --watch --serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ae-svg-components@0.12.4 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\peter\AppData\Roaming\npm-cache\_logs\2018-09-02T04_42_33_782Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ae-svg-components@0.12.4 start: `npm run dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ae-svg-components@0.12.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\peter\AppData\Roaming\npm-cache\_logs\2018-09-02T04_42_33_810Z-debug.log

C:\ae\adaept.com\ae-svg-components>
```
![capture393](https://user-images.githubusercontent.com/140737/44952261-602c9d80-ae30-11e8-8d29-3b9da6af74fc.png)

**Expected behavior:**

It runs. I can deploy new version to the site.

**Steps to reproduce:**

This commit: https://github.com/peterennis/ae-svg-components/commit/5ce3cdac643debbadd1441f93516a307a470a5e6
This site: https://aesvg.adaept.com/

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by peterennis** [comment]
Test with prod build command, same error.
No indication from compile that it is --prod. Too early because of error?
Is this the correct command?
Prod is indicated in the error log.
```
C:\ae\adaept.com\ae-svg-components>npm run build --prod

> ae-svg-components@0.12.4 build C:\ae\adaept.com\ae-svg-components
> stencil build


[ ERROR ]  autoprefixer is not a function TypeError: autoprefixer is not a function at Object.<anonymous>
           (C:\ae\adaept.com\ae-svg-components\stencil.config.ts:31:23) at Module._compile (module.js:652:30) at
           Object.require.extensions..js
           (C:\ae\adaept.com\ae-svg-components\node_modules\@stencil\core\dist\sys\node\index.js:766:20) at Module.load
           (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at
           Module.require (module.js:596:17) at require (internal/module.js:11:18) at requireConfigFile
           (C:\ae\adaept.com\ae-svg-components\node_modules\@stencil\core\dist\sys\node\index.js:773:20) at
           loadConfigFile (C:\ae\adaept.com\ae-svg-components\node_modules\@stencil\core\dist\sys\node\index.js:717:32)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ae-svg-components@0.12.4 build: `stencil build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ae-svg-components@0.12.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\peter\AppData\Roaming\npm-cache\_logs
[2018-09-02T04_50_54_122Z-debug.log]

C:\ae\adaept.com\ae-svg-components>
```

[2018-09-02T04_50_54_122Z-debug.log](https://github.com/ionic-team/stencil/files/2342969/2018-09-02T04_50_54_122Z-debug.log)

**Comment by jthoms1** [comment]
import * as autoprefixer from 'autoprefixer';

To

import autoprefixer from 'autoprefixer';

Recent change to tsconfig has allowed for typescript to do a better job of understanding imports.

**Comment by peterennis** [comment]
This is the exact process to fix it:

import autoprefixer from 'autoprefixer';
![capture394](https://user-images.githubusercontent.com/140737/44964861-777a9200-aee7-11e8-91d4-4f5af95c3b72.png)

`npm run start`

![capture395](https://user-images.githubusercontent.com/140737/44964867-82cdbd80-aee7-11e8-938c-de4d2327bab3.png)

Delete these files:

![capture397](https://user-images.githubusercontent.com/140737/44964879-94af6080-aee7-11e8-8e74-b42f64832b98.png)

'npm run start` working again

![capture399](https://user-images.githubusercontent.com/140737/44964983-2d45e080-aee8-11e8-9b9c-db55b7b4205d.png)

**Comment by jthoms1** [comment]
Ah, you were on a prerelease. Ya I renamed generated back to components before releasing 0.12.0. Glad you got it.

**Comment by ItMusaev** [comment]
Есть еще решение, возможно ваш gulp и gulp-autoprefixer не совместимы! установи версию чуть старую примерно вот так 
npm install gulp-autoprefixer@5.0.0
