### ISSUE TITLE
Compile error when trying to build with --prerender flag

### ISSUE THREAD

**Issue by threeaccents** [ionic-team/stencil#1110]
**Stencil version:**

```
 @stencil/core@<0.12.4>
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When running`npm run build` I get this error
```bash
[33:34.8]  prerendering failed in 870 ms

[ ERROR ]  TypeError: Parameter "url" must be a string, not undefined at Url.parse (url.js:103:11) at Object.urlParse
           [as parse] (url.js:97:13) at getWritePathFromUrl
           (/Users/digo/code/src/gitlab.com/threeaccents/soli/webapp/node_modules/@stencil/core/dist/compiler/index.js:7708:38)
           at
           /Users/digo/code/src/gitlab.com/threeaccents/soli/webapp/node_modules/@stencil/core/dist/compiler/index.js:13945:26
           at Generator.next (<anonymous>) at
           /Users/digo/code/src/gitlab.com/threeaccents/soli/webapp/node_modules/@stencil/core/dist/compiler/index.js:13815:71
           at new Promise (<anonymous>) at __awaiter$E
           (/Users/digo/code/src/gitlab.com/threeaccents/soli/webapp/node_modules/@stencil/core/dist/compiler/index.js:13811:12)
           at writePrerenderDest
           (/Users/digo/code/src/gitlab.com/threeaccents/soli/webapp/node_modules/@stencil/core/dist/compiler/index.js:13943:12)
           at
           /Users/digo/code/src/gitlab.com/threeaccents/soli/webapp/node_modules/@stencil/core/dist/compiler/index.js:13929:19

[ ERROR ]  /Users/digo/code/src/gitlab.com/threeaccents/soli/webapp/node_modules/@stencil/core/dist/compiler/index.js:12351
           App.loadBundle = function loadBundle(bundleId, [, ...dependentsList], importer) { ^ TypeError: undefined is
           not a function at Object.loadBundle
           (/Users/digo/code/src/gitlab.com/threeaccents/soli/webapp/node_modules/@stencil/core/dist/compiler/index.js:12351:41)
           at evalmachine.<anonymous>:2:5 at ContextifyScript.Script.runInContext (vm.js:59:29) at Object.runInContext
           (vm.js:120:6) at Object.runInContext
           (/Users/digo/code/src/gitlab.com/threeaccents/soli/webapp/node_modules/@stencil/core/dist/sys/node/index.js:614:8)
           at loadFile
           (/Users/digo/code/src/gitlab.com/threeaccents/soli/webapp/node_modules/@stencil/core/dist/compiler/index.js:12396:23)
           at missingDependents.forEach.d
           (/Users/digo/code/src/gitlab.com/threeaccents/soli/webapp/node_modules/@stencil/core/dist/compiler/index.js:12355:13)
           at Array.forEach (<anonymous>) at Object.loadBundle
           (/Users/digo/code/src/gitlab.com/threeaccents/soli/webapp/node_modules/@stencil/core/dist/compiler/index.js:12353:27)
           at evalmachine.<anonymous>:2:5
```

**Expected behavior:**

The app should build correctly.

**Steps to reproduce:**

``` bash
git clone https://github.com/ionic-team/stencil-starter.git my-app
cd my-app
// update @stencil/core package to 0.12.4 and @stencil/router 0.2.8
npm i
npm run build
```

**Comment by bitflower** [comment]
Duplicate? https://github.com/ionic-team/stencil/issues/1058

**Comment by threeaccents** [comment]
Yup. Thxs

**Comment by gowebvision** [comment]
Any update on this issue?
