### ISSUE TITLE
Random errors in E2E testing 

### ISSUE THREAD

**Issue by jesusbotella** [ionic-team/stencil#1138]
**Stencil version:**

```
 @stencil/core@0.13.2
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Every time E2E tests are executed, an `UnhandledPromiseRejectionWarning` error is raised without modifying code.

Here I post some of the errors I got:
```
(node:42453) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at Promise (/Users/jbotella/Development/carto/airship/node_modules/puppeteer/lib/Connection.js:202:56)
    at new Promise (<anonymous>)
```

```
(node:42114) UnhandledPromiseRejectionWarning: Error: JSHandle is disposed!
    at ExecutionContext.convertArgument (/Users/jbotella/Development/carto/airship/node_modules/puppeteer/lib/ExecutionContext.js:120:17)
    at Array.map (<anonymous>)
    at ExecutionContext.evaluateHandle (/Users/jbotella/Development/carto/airship/node_modules/puppeteer/lib/ExecutionContext.js:92:23)
    at ExecutionContext.evaluate (/Users/jbotella/Development/carto/airship/node_modules/puppeteer/lib/ExecutionContext.js:50:31)
    at E2EElement.<anonymous> (/Users/jbotella/Development/carto/airship/packages/components/node_modules/@stencil/core/dist/testing/index.js:6069:74)
```

```
UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at Promise (/Users/jbotella/Development/carto/airship/node_modules/puppeteer/lib/Connection.js:202:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/jbotella/Development/carto/airship/node_modules/puppeteer/lib/Connection.js:201:12)
```

Here's the complete log of the latest test run that I did
```
> stencil test --spec --e2e

[33:33.9]  @stencil/core v0.13.2 ⚡️
[33:33.9]  testing e2e and spec files
[33:33.9]  build, airship, dev mode, started ...
[33:34.0]  transpile started ...
[33:35.1]  transpile finished in 1.11 s
[33:35.1]  module map started ...
[33:35.1]  generate styles started ...
[33:35.5]  compile global style start ...
[33:35.7]  compile global style finish in 150 ms
[33:35.7]  generate styles finished in 520 ms
[33:36.5]  module map finished in 1.35 s
[33:36.5]  module derive started ...
[33:36.5]  module derive finished in 1 ms
[33:36.5]  generate bundles started ...
[33:36.5]  generate bundles finished in 6 ms
[33:36.5]  generate app files started ...
[33:36.5]  generate app files finished in 10 ms
[33:37.0]  build finished in 3.16 s

 PASS  src/components/as-responsive-content/as-responsive-content.e2e.ts
 PASS  src/components/as-category-widget/as-category-widget.e2e.ts

 RUNS  src/components/as-histogram-widget/as-histogram-widget.e2e.ts
 RUNS  src/components/as-range-slider/thumb/as-range-slider-thumb.e2e.ts
 RUNS  src/components/as-dropdown/as-dropdown.e2e.ts

Test Suites: 2 passed, 2 of 12 total
Tests:       10 passed, 10 total
Snapshots:   0 total
Time:        5s, estimated 7s
████████████████████████████████████████(node:42960) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at Promise (/Users/jbotella/Development/carto/airship/node_modules/puppeteer/lib/Connection.js:202:56)
    at new Promise (<anonymous>)
 PASS  src/components/as-dropdown/as-dropdown.e2e.tscarto/airship/node_modules/puppeteer/lib/Connection.js:201:12)
 PASS  src/components/as-histogram-widget/as-histogram-widget.e2e.ts (5.423s)
 PASS  src/components/as-range-slider/thumb/as-range-slider-thumb.e2e.ts
 PASS  src/components/as-infowindow/as-infowindow.e2e.ts
 PASS  src/components/as-range-slider/track/as-range-slider-bar.e2e.ts
 PASS  src/components/as-histogram-widget/as-histogram-widget.spec.ts
 PASS  src/components/as-category-widget/as-category-widget.spec.ts
 PASS  src/components/as-range-slider/slider/as-range-slider.e2e.ts
 PASS  src/components/as-range-slider/slider/as-range-slider.spec.ts
 › 4 snapshots obsolete.
   • as-range-slider Rendering can be rendered disabled 1
   • as-range-slider Rendering should render 1 thumb + 1 bar when using a value 1
   • as-range-slider Rendering should render 2 thumbs + 1 bar when using a range 1
   • as-range-slider Rendering should render without parameters, using defaults 1
 PASS  src/components/as-range-slider/track/as-range-slider-bar.spec.ts
 › 1 snapshot obsolete.
   • as-range-slider-bar Rendering should render a bar with its values 1

Snapshot Summary
 › 5 snapshots obsolete from 2 test suites. To remove them all, re-run jest with `-u`.
   ↳ src/components/as-range-slider/slider/as-range-slider.spec.ts
       • as-range-slider Rendering can be rendered disabled 1
       • as-range-slider Rendering should render 1 thumb + 1 bar when using a value 1
       • as-range-slider Rendering should render 2 thumbs + 1 bar when using a range 1
       • as-range-slider Rendering should render without parameters, using defaults 1
   ↳ src/components/as-range-slider/track/as-range-slider-bar.spec.ts
       • as-range-slider-bar Rendering should render a bar with its values 1

Test Suites: 12 passed, 12 total
Tests:       58 passed, 58 total
Snapshots:   5 obsolete, 0 total
Time:        7.52s
Ran all test suites.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @carto/airship-components@1.0.0-beta.0 test: `stencil test --spec --e2e`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @carto/airship-components@1.0.0-beta.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jbotella/.npm/_logs/2018-10-09T14_33_45_827Z-debug.log
```

**Expected behavior:**
Tests pass correctly.

**Other information:**

Please let me know if you need anything else :)

**Comment by jesusbotella** [comment]
Seems like test failure was due to obsolete snapshots, but errors are still present.

**Comment by adamdbradley** [comment]
I'm unable to replicate this issue in the latest version.
