### ISSUE TITLE
--prerender for app starter freezes

### ISSUE THREAD

**Issue by big-red-dragon** [ionic-team/stencil#1144]
**Stencil version:**

```
 @stencil/core@0.13.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Prerendering with `--prerender` in the (default) `www` mode just freezes after `[56:11.8]  prerender, started: / ...`. No error when using `--debug`.

**Expected behavior:**

build succeeds

**Steps to reproduce:**

1. `npm init stencil`
2. select `app`
3. `npm run build`

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by matdec01** [comment]
@destructive-dragon Had the same issue. Upgrading to the latest stable (0.14.x) seems to have fixed the problem.

**Comment by CRHain88** [comment]
v0.16 fails.

```sh
[17:07.4]  prerendering started ...
[17:07.4]  prerender, started: / ...
[17:08.2]  prerender, finished: / in 807 ms
[17:08.2]  prerendering failed in 810 ms

[ WARN  ]  Bundling Warning
           Generated an empty bundle

[ ERROR ]  TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type
           undefined at Url.parse (url.js:152:11) at Object.urlParse [as parse] (url.js:146:13) at
           getWritePathFromUrl
           (/Users/crhain88/Development/stencil-app-starter/node_modules/@stencil/core/dist/compiler/index.js:8936:38)
           at
           /Users/crhain88/Development/stencil-app-starter/node_modules/@stencil/core/dist/compiler/index.js:15262:26
           at Generator.next (<anonymous>) at
           /Users/crhain88/Development/stencil-app-starter/node_modules/@stencil/core/dist/compiler/index.js:32:71
           at new Promise (<anonymous>) at __awaiter
           (/Users/crhain88/Development/stencil-app-starter/node_modules/@stencil/core/dist/compiler/index.js:28:12)
           at writePrerenderDest
           (/Users/crhain88/Development/stencil-app-starter/node_modules/@stencil/core/dist/compiler/index.js:15260:12)
           at
           /Users/crhain88/Development/stencil-app-starter/node_modules/@stencil/core/dist/compiler/index.js:15246:19

[ ERROR ]  evalmachine.<anonymous>:4 })(x,r); ^ ReferenceError: x is not defined at
           evalmachine.<anonymous>:4:4 at evalmachine.<anonymous>:5:3 at Script.runInContext
           (vm.js:130:20) at Object.runInContext (vm.js:298:6) at Object.runInContext
           (/Users/crhain88/Development/stencil-app-starter/node_modules/@stencil/core/dist/sys/node/index.js:1:13735)
           at runGlobalScripts
           (/Users/crhain88/Development/stencil-app-starter/node_modules/@stencil/core/dist/compiler/index.js:13557:23)
           at createPlatformServer
           (/Users/crhain88/Development/stencil-app-starter/node_modules/@stencil/core/dist/compiler/index.js:13360:5)
           at resolve
           (/Users/crhain88/Development/stencil-app-starter/node_modules/@stencil/core/dist/compiler/index.js:13639:21)
           at new Promise (<anonymous>) at hydrateHtml
           (/Users/crhain88/Development/stencil-app-starter/node_modules/@stencil/core/dist/compiler/index.js:13622:12)

[17:08.2]  build failed in 12.95 s

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

crhain88 at atl-it-1804 in ~/Development/stencil-app-starter on master [!]

-----

stencil-component-starter also fails:

```sh
[17:38.7]  prerendering started ...
[17:38.8]  prerender, started: / ...
[17:38.8]  missing app global:
           /Users/crhain88/Development/stencil-component-starter/www/build/mycomponent/mycomponent.global.js
```

**Comment by MattMcFarland** [comment]
I'm running into this issue when using stencil v0.17.0 - not using shadow dom, just rendering html - 0.16.0 and below would "fail gracefully" meaning they never finished rendering a certain page of mine, not giving me an error message (wish I knew what was wrong with a particular page) - however in 0.17.0 - it freezes during prerender.

**Comment by arturh85** [comment]
I tried to debug the issue in Stencil 0.17.1-0 with `npm init stencil` using the component starter I get the same error about url must be string. 

Digging a little deeper i found the following line in the callstack:

```
const filePath = getWritePathFromUrl(config, outputTarget, results.url);
```

Outputting results gives me:

```
{ diagnostics:
   [ { level: 'error',
       type: 'build',
       header: 'Build Error',
       messageText:
        'ReferenceError: window is not defined\n    at initHostSnapshot (C:\\projects\\foo\\newstencil\\node_modules\\@stencil\\core\\dist\\compiler\\index.js:11152:13)\n    at connectHostElement (C:\\projects\\foo\\newstencil\\node_modules\\@stencil\\core\\dist\\compiler\\index.js:12891:26)\n    at connectElement (C:\\projects\\foo\\newstencil\\node_modules\\@stencil\\core\\dist\\compiler\\index.js:12876:13)\n    at connectChildElements (C:\\projects\\foo\\newstencil\\node_modules\\@stencil\\core\\dist\\compiler\\index.js:12866:13)\n    at resolve (C:\\projects\\foo\\newstencil\\node_modules\\@stencil\\core\\dist\\compiler\\index.js:13798:9)\n    at new Promise (<anonymous>)\n    at hydrateHtml (C:\\projects\\foo\\newstencil\\node_modules\\@stencil\\core\\dist\\compiler\\index.js:13697:12)\n    at Renderer.<anonymous> (C:\\projects\\foo\\newstencil\\node_modules\\@stencil\\core\\dist\\compiler\\index.js:15123:40)\n    at Generator.next (<anonymous>)\n    at C:\\projects\\foo\\newstencil\\node_modules\\@stencil\\core\\dist\\compiler\\index.js:32:71',
       relFilePath: null,
       absFilePath: null,
       lines: [] } ],
  url: undefined,
  html:
   `<!DOCTYPE html>\n<html dir="ltr" lang="en">\n<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0">\n  <title>Stencil Component Starter</title>\n  <script src="/build/mycomponent.js"></script>\n\n</head>\n<body>\n\n  <my-component first="Stencil" last="'Don't call me a framework' JS"></my-component>\n\n</body>\n</html>\n`,
  styles: null,
  anchors: [],
  components: [],
  styleUrls: [],
  scriptUrls: [],
  imgUrls: [] 
}
```

**Comment by peterpeterparker** [comment]
With v0.17.0 I had the same error respectively:

```
[ ERROR ]  TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined at
           Url.parse (url.js:154:11) at Object.urlParse [as parse] (url.js:148:13) at getWritePathFromUrl
           (/Users/.../node_modules/@stencil/core/dist/compiler/index.js:8992:38)

...

[ ERROR ]  evalmachine.<anonymous>:4 })(x,r); ^ ReferenceError: x is not defined at evalmachine.<anonymous>:4:4 at
           evalmachine.<anonymous>:9:3 at Script.runInContext (vm.js:133:20) at Object.runInContext (vm.js:301:6) at
           Object.runInContext
           (/Users/.../node_modules/@stencil/core/dist/sys/node/index.js:1:13895)
```

once I updated to v0.17.1 I've got now the following error:

```
[ ERROR ]  ENOENT: no such file or directory, open
           '/Users/.../www/build/app/undefined.es5.entry.js' at
           Object.openSync (fs.js:450:3) at Object.readFileSync (fs.js:350:35) at NodeFs.readFileSync
           (/Users/daviddalbusco/Documents/projects/deckdeckgo/deckdeckgo-docs/node_modules/@stencil/core/dist/sys/node/index.js:1:51986)
```

**Comment by peterpeterparker** [comment]
Btw. I do face the 

```
[ WARN  ]  Bundling Warning
           Generated an empty bundle
```

too. Could that be the root of the problem?

**Comment by FDiskas** [comment]
What if `prerender` flag exists then on build time force all components to be `shadow: false`? and revert before building assets? :city_sunset:
Magic :D

**Comment by FDiskas** [comment]
Also just a not `prerender` creats html files not minified

**Comment by mgeorgehansen** [comment]
--prerender freezes in the starter app w/ @stencil/core v0.18.1 & @stencil/router v0.3.3 as well, but I can confirm that setting shadow to false in all components fixes it and the app builds just fine.

**Comment by peterpeterparker** [comment]
My above issue is solved with Stencil >= v1
