### ISSUE TITLE
Cyclic dependency when using stencil component within webpack  project

### ISSUE THREAD

**Issue by cjh1** [ionic-team/stencil#1178]
**Stencil version:**

```
 @stencil/core@0.13.0 >=
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When building a project using webpack that uses a component built by stencil we are seeing the following error with stencil 0.13.0 and above:

```
(node:29666) UnhandledPromiseRejectionWarning: Error: Cyclic dependency
    at visit (/home/cjh/work/source/cyclic/node_modules/toposort/index.js:35:13)
    at visit (/home/cjh/work/source/cyclic/node_modules/toposort/index.js:53:9)
    at visit (/home/cjh/work/source/cyclic/node_modules/toposort/index.js:53:9)
    at Function.toposort [as array] (/home/cjh/work/source/cyclic/node_modules/toposort/index.js:22:22)
    at Object.module.exports.dependency (/home/cjh/work/source/cyclic/node_modules/html-webpack-plugin/lib/chunksorter.js:50:35)
    at HtmlWebpackPlugin.sortChunks (/home/cjh/work/source/cyclic/node_modules/html-webpack-plugin/index.js:364:35)
    at /home/cjh/work/source/cyclic/node_modules/html-webpack-plugin/index.js:113:21
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/cjh/work/source/cyclic/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/home/cjh/work/source/cyclic/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/home/cjh/work/source/cyclic/node_modules/webpack/lib/Compiler.js:358:19)
    at onCompiled (/home/cjh/work/source/cyclic/node_modules/webpack/lib/Compiler.js:225:9)
    at hooks.afterCompile.callAsync.err (/home/cjh/work/source/cyclic/node_modules/webpack/lib/Compiler.js:547:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/cjh/work/source/cyclic/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/cjh/work/source/cyclic/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/home/cjh/work/source/cyclic/node_modules/webpack/lib/Compiler.js:544:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/cjh/work/source/cyclic/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/cjh/work/source/cyclic/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/home/cjh/work/source/cyclic/node_modules/webpack/lib/Compilation.js:1312:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/cjh/work/source/cyclic/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/cjh/work/source/cyclic/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/home/cjh/work/source/cyclic/node_modules/webpack/lib/Compilation.js:1303:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/cjh/work/source/cyclic/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/cjh/work/source/cyclic/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/home/cjh/work/source/cyclic/node_modules/webpack/lib/Compilation.js:1298:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/cjh/work/source/cyclic/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/cjh/work/source/cyclic/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/home/cjh/work/source/cyclic/node_modules/webpack/lib/Compilation.js:1294:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/cjh/work/source/cyclic/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/cjh/work/source/cyclic/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/home/cjh/work/source/cyclic/node_modules/webpack/lib/Compilation.js:1231:27)
```

**Expected behavior:**

The project would build.

**Steps to reproduce:**

The following repo illustrates the problem:

https://github.com/cjh1/cyclic

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

It appears the cyclic dependency is between. `dist/esm/es5/XXX.core.js` and `dist/esm/es5/build/*.entry.js`.

**Comment by AngelMunoz** [comment]
It might be due to `html-webpack-plugin check this issue,
https://github.com/jantimon/html-webpack-plugin/issues/870
I also sent this info to you in the community slack

**Comment by cjh1** [comment]
@AngelMunoz yes, I think that is the same one. As I mentioned on slack we don't have control of our webpack config ( we are an extension to jupyterlab ).
