### ISSUE TITLE
can't use contenteditable property inside template

### ISSUE THREAD

**Issue by jaichandra** [ionic-team/stencil#130]
If I have a template like below, I get an error:
```
export class Foo {
  render() {
    return <div id="textarea" contenteditable="true" />;
  }
}
```

Error:
```
[ ERROR ]  typescript: src/components/foo/foo.tsx, line: 11
           Property 'contenteditable' does not exist on type 'HTMLAttributes'.

     L10:  render() {
     L11:    return <div id="textarea" contenteditable="true" />;
```
This probably is a typescript error though.

**Comment by jgw96** [comment]
If you use `contentEditable="true"` does it work?

**Comment by adamdbradley** [comment]
Yeah I think `contentEditable` should work, but raises a good question of both should work since attribute names are case-insensitive.

**Comment by jaichandra** [comment]
sorry.. couldn't get to this before. For the record, changing it to `contentEditable="true"` throws a different error.
```
[ ERROR ]  typescript: src/components/foo/foo.tsx, line: 11
           Type '{ id: "textarea"; contentEditable: "true"; }' is not assignable to type 'HTMLAttributes'. Types of
           property 'contentEditable' are incompatible. Type '"true"' is not assignableto type 'boolean'.

     L10:  render() {
     L11:    return (<div id="textarea" contentEditable="true"></div>);
```

With the latest build, this error is gone now. But it still doesn't work. I see below error on the compiler.
```
> sd concurrent "stencil build --dev --watch" "stencil-dev-server"

[15:26.0]  build, dev mode, started ...
[15:26.0]  compile started ...

... Uhoh. Got error Unexpected end of JSON input ...
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at SafeParse (/Users/<...>/stencil-app/node_modules/safe-json-parse/index.js:12:21)
    at /Users/<...>/stencil-app/node_modules/body/json.js:27:9
    at IncomingMessage.onEnd (/Users/<...>/stencil-app/node_modules/raw-body/index.js:119:7)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

... Uhoh. Got error Unexpected end of JSON input ...
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at SafeParse (/Users/<...>/stencil-app/node_modules/safe-json-parse/index.js:12:21)
    at /Users/<...>/stencil-app/node_modules/body/json.js:27:9
    at IncomingMessage.onEnd (/Users/<...>/stencil-app/node_modules/raw-body/index.js:119:7)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
[15:29.6]  compile finished in 3.53 s
[15:29.6]  bundle styles started ...
[15:29.6]  bundle modules started ...
[15:29.9]  bundle styles finished in 358 ms
[15:30.0]  bundle modules finished in 446 ms
[15:30.1]  build finished, watching for changes... in 4.04 s
```

**Comment by bfmatei** [comment]
Just a silly remark: did you try `contentEditable={true}`?

**Comment by jaichandra** [comment]
Nopes. Here's my component:
```
import { Component, Prop } from '@stencil/core';

@Component({
  tag: 'svg-foo',
  styleUrl: 'svg-foo.scss'
})
export class Foo {
  @Prop() svg;

  render() {
    return (<div id="textarea" contentEditable="true"></div>);
  }
}
```

**Comment by jaichandra** [comment]
My bad... I was missing the component reference in `stencil.config.js`. The component works after adding it to the config. But I continue to see the error in the terminal and the page doesn't load in the browser initially. It's stuck at `Initializing First Build...`. Once I do a refresh, the component loads, but throws the same error in terminal again. Might be missing something else.

**Comment by patarapolw** [comment]
Now, do I manually add props. I cannot use

```jsx
<link crossOrigin="anonymous" />
```
