### ISSUE TITLE
npm run dev fails on windows after the first time

### ISSUE THREAD

**Issue by jgw96** [ionic-team/stencil#131]
_From @AmitMY on August 14, 2017 19:51_

Cloned the repo, `npm install`, `npm run dev`, worked perfectly.
Ctrl + C
`npm run dev` (and all `npm run dev` after that:

```
amitm@Amit-PC MINGW64 /d/xampp/htdocs/stencil-site (master)
$ npm run dev

> @stencil/stencil-site@0.0.1 dev D:\xampp\htdocs\stencil-site
> gulp && sd concurrent "stencil build --dev --watch" "stencil-dev-server"

[22:49:02] Using gulpfile D:\xampp\htdocs\stencil-site\gulpfile.js
[22:49:02] Starting 'default'...
[22:49:02] Finished 'default' after 46 ms
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3333
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at Server.setupListenHandle [as _listen2] (net.js:1307:14)
    at listenInCluster (net.js:1355:12)
    at Server.listen (net.js:1455:7)
    at Object.<anonymous> (D:\xampp\htdocs\stencil-site\node_modules\@stencil\dev-server\dist\index.js:84:64)
    at Generator.next (<anonymous>)
    at fulfilled (D:\xampp\htdocs\stencil-site\node_modules\@stencil\dev-server\dist\index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
[49:02.9]  build, dev mode, started ...
[49:02.9]  compile started ...
[49:04.4]  compile finished in 1.52 s
[49:04.4]  bundle styles started ...
[49:04.4]  bundle modules started ...
[49:04.5]  bundle styles finished in 130 ms
[49:04.6]  bundle modules finished in 227 ms
[49:04.6]  prerender index html started ...
[49:05.3]  prerender index html finished in 619 ms

[ ERROR ]  EPERM: operation not permitted, lstat 'D:\xampp\htdocs\stencil-site\www\build\app\demos-page.css'

[49:17.9]  build failed, watching for changes... in 15.03 s

```

Of course, this is on everyone's "favorite" OS - Windows

_Copied from original issue: ionic-team/stencil-site#1_

**Comment by jgw96** [comment]
@AmitMY , looks like you might have something already listening on the 3333 port?

**Comment by jgw96** [comment]
Perhaps a rogue node process on your machine?

**Comment by jgw96** [comment]
_From @AmitMY on August 29, 2017 21:23_

Yeah, the rogue process is the stencil server.
This is infinitely reproducible for me, so let me know what you want to know.

Here is a more full process


```
amitm@Amit-PC MINGW64 /d/apps/stencil (master)
$ npm run dev

> stencil@0.0.1 dev D:\xampp\htdocs\apps\stencil
> gulp && workbox-cli generate:sw && sd concurrent "stencil build --dev --watch"                                      "stencil-dev-server"

[00:20:56] Using gulpfile D:\xampp\htdocs\apps\stencil\gulpfile.js
[00:20:56] Starting 'default'...
[00:20:57] Finished 'default' after 858 ms
Using configuration from workbox-cli-config.js.
[21:03.0]  build, dev mode, started ...
[21:03.0]  compile started ...
[21:05.6]  compile finished in 2.63 s
[21:05.7]  bundle styles started ...
[21:05.7]  bundle modules started ...
[21:06.2]  bundle styles finished in 534 ms
[21:06.3]  bundle modules finished in 671 ms
[21:06.4]  prerender index html started ...


amitm@Amit-PC MINGW64 /d/apps/stencil (master)
$ npm run dev

> stencil@0.0.1 dev D:\xampp\htdocs\apps\stencil
> gulp && workbox-cli generate:sw && sd concurrent "stencil build --dev --watch"                                      "stencil-dev-server"

[00:21:09] Using gulpfile D:\xampp\htdocs\apps\stencil\gulpfile.js
[00:21:09] Starting 'default'...
[00:21:10] Finished 'default' after 747 ms
Using configuration from workbox-cli-config.js.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3333
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at Server.setupListenHandle [as _listen2] (net.js:1307:14)
    at listenInCluster (net.js:1355:12)
    at Server.listen (net.js:1455:7)
    at Object.<anonymous> (D:\xampp\htdocs\apps\stencil\node_modules\@stencil\                                     dev-server\dist\index.js:84:64)
    at Generator.next (<anonymous>)
    at fulfilled (D:\xampp\htdocs\apps\stencil\node_modules\@stencil\dev-serve                                     r\dist\index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

```

**Comment by jgw96** [comment]
This issue was moved to ionic-team/stencil-dev-server#11
