### ISSUE TITLE
alpha.5: jest tests fail "cannot find module @stencil/core/app"

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#1446]
**Stencil version:**
```
 @stencil/core@1.0.0-alpha.5
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I'm getting this after monkey-patching issue #https://github.com/ionic-team/stencil/issues/1445
```
 FAIL  src/components/i18n/i18n.spec.ts
  ● Test suite failed to run

    Cannot find module '@stencil/core/app' from 'i18n.spec.ts'

    > 1 | 
        | ^

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (src/components/i18n/i18n.spec.ts:1:56)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.447s
Ran all test suites.
```
This happens even when I completely clear the test files content leaving it empty.

**Expected behavior:**
Tests run fine.

**Steps to reproduce:**
Monkey-patch the file `jest-preprocessor.js` as described in https://github.com/ionic-team/stencil/issues/1445 then `npm i && npm run test`.

**Related code:**
Repo: https://github.com/bitflower/caseos-ui-kit/tree/stencil-one

**Comment by bitflower** [comment]
Solved by implementing breaking change of `jest` config as discussed here with @adamdbradley :
https://stencil-worldwide.slack.com/archives/C9LTCKAN8/p1554814470065500
