### ISSUE TITLE
Stencil One alpha.9 unit tests are not working

### ISSUE THREAD

**Issue by jepiqueau** [ionic-team/stencil#1467]
**Stencil version:**

```
 @stencil/core@1.0.0-alpha.9
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

when running the tests with npm test i got the following error 
```
Test suite failed to run

    unable to resolve "package.json" from: /Users/queaujeanpierre/Documents/StencilWebComponent/testalpha/node_modules/@stencil/core

      at new NodeSystem (node_modules/@stencil/core/dist/sys/node/index.js:69468:19)
      at Object.<anonymous> (node_modules/@stencil/core/dist/sys/node/index.js:69636:15)
      at Object.<anonymous> (node_modules/@stencil/core/dist/testing/index.js:57403:17)
      at Object.<anonymous> (node_modules/@stencil/core/testing/jest-setuptestframework.js:1:63) 
```

**Expected behavior:**

Should run the unit tests

**Steps to reproduce:**

- create a new stencil component with npm init stencil
- modify @stencil/core: "^1.0.0-alpha.9" in package.json
- npm install
- create a my-component.e2e.ts file 

**Related code:**

```ts
// insert any relevant code here

import { newSpecPage } from '@stencil/core/testing';

describe('my-component', () => {
  it('renders', async () => {
    const root = await newSpecPage({html: '<my-component></my-component>'});
    expect(root).toEqualHtml(`<my-component></my-component>`);
    const element = await document.querySelector('my-component');
    expect(element).toHaveClass('hydrated');
  });
});
```

**Other information:**

looking at the @stencil/core/dist/sys/index.js  the
``` 
        try {
            this.packageJsonData = require(path$2.join(this.packageDir, 'package.json'));
        }
        catch (e) {
          console.log('**** e ',e)
            throw new Error(`unable to resolve "package.json" from: ${this.packageDir}`);
        }
``` 
the error in the catch is 
```
console.log node_modules/@stencil/core/dist/sys/node/index.js:69471
    **** e  ReferenceError: HTMLElement is not defined
        at createCustomElement (/Users/queaujeanpierre/Documents/StencilWebComponent/testalpha/node_modules/@stencil/core/dist/runtime/index.js:1667:32)
        at Object.<anonymous> (/Users/queaujeanpierre/Documents/StencilWebComponent/testalpha/node_modules/@stencil/core/dist/runtime/index.js:1678:21)
        at Runtime._execModule (/Users/queaujeanpierre/Documents/StencilWebComponent/testalpha/node_modules/jest-runtime/build/index.js:694:13)
        at Runtime.requireModule (/Users/queaujeanpierre/Documents/StencilWebComponent/testalpha/node_modules/jest-runtime/build/index.js:376:14)
        at Runtime.requireModuleOrMock (/Users/queaujeanpierre/Documents/StencilWebComponent/testalpha/node_modules/jest-runtime/build/index.js:463:19)
        at Object.<anonymous> (/Users/queaujeanpierre/Documents/StencilWebComponent/testalpha/node_modules/@stencil/core/dist/testing/platform.js:6:15)
        at Runtime._execModule (/Users/queaujeanpierre/Documents/StencilWebComponent/testalpha/node_modules/jest-runtime/build/index.js:694:13)
        at Runtime.requireModule (/Users/queaujeanpierre/Documents/StencilWebComponent/testalpha/node_modules/jest-runtime/build/index.js:376:14)
        at Runtime.requireModuleOrMock (/Users/queaujeanpierre/Documents/StencilWebComponent/testalpha/node_modules/jest-runtime/build/index.js:463:19)
        at Object.<anonymous> (/Users/queaujeanpierre/Documents/StencilWebComponent/testalpha/node_modules/@stencil/core/dist/testing/core.js:6:16)

```

**Comment by psmyrdek** [comment]
Can confirm that. The same for me and a few other folks on Stencil's slack.

**Comment by manucorporat** [comment]
can you share your package.json?

**Comment by psmyrdek** [comment]
```
{
  "name": "",
  "version": "1.15.0",
  "description": "",
  "group": "",
  "repository": "",
  "main": "dist/index.js",
  "types": "dist/types/components.d.ts",
  "collection": "dist/collection/collection-manifest.json",
  "module": "dist/index.mjs",
  "es2015": "dist/esm/index.mjs.js",
  "es2017": "dist/esm/index.mjs.js",
  "jsnext:main": "dist/esm/index.mjs.js",
  "scripts": {
    "build": "stencil build",
    "start:dev": "stencil build --dev --watch",
    "test": "stencil test --spec",
    "test:e2e": "stencil test --e2e",
    "test.watch": "stencil test --spec --e2e --watchAll",
    "preversion": "npm run test",
    "postversion": "npm run build"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@stencil/core": "1.0.0-alpha.8",
    "@types/jest": "23.3.10",
    "@types/puppeteer": "1.11.1",
    "@types/xregexp": "3.0.29",
    "jest": "23.6.0",
    "jest-cli": "23.6.0",
    "puppeteer": "1.11.0"
  },
  "dependencies": {
    "slim-select": "1.18.13",
    "xregexp": "4.2.4"
  },
  "publishConfig": {
    "registry": ""
  },
  "files": [
    "dist/",
    "src/locale/"
  ]
}

```

**Comment by jepiqueau** [comment]
my package.json file  ```{
  "name": "testalpha",
  "version": "0.0.1",
  "description": "Stencil Component Starter",
  "module": "dist/index.mjs",
  "main": "dist/index.js",
  "unpkg": "dist/ionic.js",
  "types": "dist/types/components.d.ts",
  "collection": "dist/collection/collection-manifest.json",
  "files": [
    "dist/"
  ],
  "scripts": {
    "build": "stencil build --docs",
    "start": "stencil build --dev --watch --serve",
    "test": "stencil test --spec --e2e",
    "test.watch": "stencil test --spec --e2e --watchAll"
  },
  "dependencies": {},
  "devDependencies": {
    "@stencil/core": "^1.0.0-alpha.9",
    "@types/jest": "23.3.14",
    "@types/puppeteer": "1.12.3",
    "jest": "23.6.0",
    "jest-cli": "23.6.0",
    "puppeteer": "1.12.2"
  },
  "jest": {
    "preset": "@stencil/core/testing"
  },

  "license": "MIT"
}
```

**Comment by adamdbradley** [comment]
I'm not able to replicate this error, what else can I try to recreate this? Also, the unit test should be written like this:

```diff
import { newSpecPage } from '@stencil/core/testing';
+import { MyCmp } from './somewhere';

describe('my-component', () => {
  it('renders', async () => {
-    const root = await newSpecPage({
+    const { root } = await newSpecPage({
+       components: [MyCmp],
        html: '<my-component></my-component>'
    });
    expect(root).toEqualHtml(`<my-component></my-component>`);
    const element = await document.querySelector('my-component');
    expect(element).toHaveClass('hydrated');
  });
});
```

**Comment by jepiqueau** [comment]
Adam, you can find the project on https://github.com/jepiqueau/stencil-unittestsalpha9

**Comment by jepiqueau** [comment]
Adam, it is fixed, i close the issue

**Comment by rahulbhooteshwar** [comment]
> Adam, it is fixed, i close the issue

@jepiqueau  how did you fixed it? I am facing exactly the same issue!!

**Comment by jepiqueau** [comment]
@rahulbhooteshwar This was fixed as Adam told since then i never found the error again. Check your spec file. which stencil release are you using?
