### ISSUE TITLE
Add a method for testing functional components

### ISSUE THREAD

**Issue by nesbocaj** [ionic-team/stencil#1600]
**Stencil version:**

```
 @stencil/core@1.0.1
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

The documentation mentions nothing about testing functional components, so I naively tried to render it with `react-test-renderer` which resulted in the following error:

```
Invariant Violation: Objects are not valid as a React child (found: object with keys {$flags$, $tag$, $children$, $elm$, $attrs$, $key$, $name$}). If you meant to render a collection of children, use an array instead.

      at invariant (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:55:15)
      at throwOnInvalidObjectType (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3931:5)
      at reconcileChildFibers (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4705:7)
      at reconcileChildren (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6508:28)
      at updateHostRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6920:5)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7745:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11413:12)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11445:24)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11528:7)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12416:7)
```

**Expected behavior:**

There should be a Stencil specific renderer for functional components or some other way to test them, ideally a method compatible with jest snapshots.
Furthermore, the documentation should describe how to test functional components.

**Steps to reproduce:**

1. `$ npm init stencil` and pick `component`.
2. `$ npm install --save-dev @stencil/core@1.0.1 react-test-renderer @types/react-test-renderer`.
3. Add the component and test described below.
4. `$ npm run test`.

**Related code:**

*src/components/hello-functional-world/HelloFunctionalWorld.tsx*
```tsx
import { FunctionalComponent, h } from "@stencil/core";

export const HelloFunctionalWorld: FunctionalComponent<HelloFunctionalWorldProps> = ({
  world = "Earth",
}) => <p>Hello {world}!</p>;

interface HelloFunctionalWorldProps {
  world?: string;
}
```

*src/components/hello-functional-world/HelloFunctionalWorld.spec.tsx*
```tsx
import { h } from "@stencil/core";
import renderer from "react-test-renderer";

import HelloFunctionalWorld from "./HelloFunctionalWorld"

it("should render \"Hello Earth!\"") {
  const component = <HelloFunctionalWorld />;

  // should be replaced with a Stencil specific renderer or another method of testing entirely
  const renderedComponent = renderer.create(component).toJSON();

  expect(renderedComponent).toMatchSnapshot();
}
```

**Other information:**

**Comment by FortinFred** [comment]
I think I figured an approach.

Given that you have a functional component named FeedThumbnail

common-renders.spec.**tsx**
```
import { h, Component } from '@stencil/core';
import { FeedThumbnail } from './common-renders';
import { newSpecPage } from '@stencil/core/dist/testing';

@Component({ tag: 'noop-component'})
class Noop {}

describe('newsfeed-post', () => {

  it('should render', async () => {
    const page = await newSpecPage({
      components: [Noop],
      template: () => <FeedThumbnail src="./mock/image.jpg" defaultSrc="defaumtImage" postType="Texte"></FeedThumbnail>
    });

    expect(page.root).toEqualHtml(`<img alt="" class="img-pictogram" src="./mock/image.jpg">`);
  });

});
```

**Comment by nesbocaj** [comment]
That is pretty much the workaround I have been using too, I just abstracted it into a function:

*src/utils/testing/functional-component-rendering.ts*

```tsx
import { Component, FunctionalComponent } from "@stencil/core";
import { SpecPage } from "@stencil/core/dist/declarations";
import { newSpecPage } from "@stencil/core/testing";

export function renderFunctionalComponentToSpecPage<T extends {}>(
  componentConstructor: () => FunctionalComponent<T>,
): Promise<SpecPage> {
  @Component({ tag: "test-component" })
  class TestComponent { }

  return newSpecPage({
    components: [TestComponent],
    template: componentConstructor,
  });
}
```

*src/components/feed-thumbnail/FeedThumbnail.spec.tsx*

```tsx
import { h } from "@stencil/core";

import { renderFunctionalComponentToSpecPage } from "../../utils/testing/functional-component-rendering";
import { FeedThumbnail } from "./FeedThumbnail";

describe("FeedThumbnail", () => {
  it("should render", async () => {
    const page = await renderFunctionalComponentToSpecPage(() =>
      <FeedThumbnail src="./mock/image.jpg" defaultSrc="defaultImage" postType="Text" />);

    expect(page.root).toMatchSnapshot();
  });
});
```
