### ISSUE TITLE
Can no longer dynamically render an svg tag

### ISSUE THREAD

**Issue by eshtadc** [ionic-team/stencil#1888]
**Stencil version:**
> 1.4.0

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Exception: 
core-02153842.js:65 DOMException: Failed to execute 'setAttributeNS' on 'Element': '' is an invalid namespace for attributes.
    at setAccessor (http://localhost:3333/build/core-02153842.js:603:17)
    at updateElement (http://localhost:3333/build/core-02153842.js:625:9)
    at createElm (http://localhost:3333/build/core-02153842.js:677:13)
    at createElm (http://localhost:3333/build/core-02153842.js:687:29)
    at createElm (http://localhost:3333/build/core-02153842.js:687:29)
    at createElm (http://localhost:3333/build/core-02153842.js:687:29)
    at addVnodes (http://localhost:3333/build/core-02153842.js:758:25)
    at patch (http://localhost:3333/build/core-02153842.js:950:13)
    at renderVdom (http://localhost:3333/build/core-02153842.js:1108:5)
    at updateComponent (http://localhost:3333/build/core-02153842.js:1227:17)

called when rendering:
```
const Foo = 'svg';
    const fooAttrs = {
      width: "22",
      height: "22",
      viewBox: "0 0 22 22",
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor"
    };
    return <Foo {...fooAttrs} />;
```

Errors with:
elm.setAttributeNS(namespace, ln, newValue);
namespace = `null`
ln = `"xmlns"`
newValue = `"http://www.w3.org/2000/svg"`
**Expected behavior:**

**Steps to reproduce:**
Dynamically render an svg:

**Related code:**
```tsx
render() {
    const Foo = 'svg';
    const fooAttrs = {
      width: "22",
      height: "22",
      viewBox: "0 0 22 22",
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor"
    };
    return <Foo {...fooAttrs} />;
}
```

**Comment by markargo** [comment]
Same issue here... removing `xmlns` fixed the rendering errors, but then exposed the other issue #1847.

**Comment by manucorporat** [comment]
Can you update to 1.5.2?

**Comment by markargo** [comment]
1.5.2 fixes both issues for me

**Comment by eshtadc** [comment]
Confirmed that 1.5.2 resolves this issue for me as closing. Closing the issue. Thanks!
