### ISSUE TITLE
JEST: Cannot read property '$hostElement$' of undefined

### ISSUE THREAD

**Issue by guidoknoll** [ionic-team/stencil#2056]
**Stencil version:**

```
 @stencil/core@1.8.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When running unit tests, i sporadically get the following error. It is not bound to a specific test case and occurs with a varying frequency:
```
TypeError: Cannot read property '$hostElement$' of undefined
    at getElement (/Users/guidoknoll/Development/widget/node_modules/@stencil/core/dist/runtime/index.js:2242:88)
    at CustomSelect.get el [as el] (/Users/guidoknoll/Development/widget/src/components/filter/custom-select/custom-select/custom-select.tsx:3799:12)
    at Timeout.setTimeout (/Users/guidoknoll/Development/widget/src/components/filter/custom-select/custom-select/custom-select.tsx:3070:12)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
/Users/guidoknoll/Development/widget/node_modules/@stencil/core/dist/runtime/index.js:2242
const getElement = (ref) => buildConditionals.BUILD.lazyLoad ? platform.getHostRef(ref).$hostElement$ : ref;
```

**Expected behavior:**

Error is not thrown.

**Steps to reproduce:**

Can't really tell why the error occurs. If you need some parts of my code i can send it to you but putting it here public is not possible. 

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by marisaoliva** [comment]
any update about this? I've the same error

**Comment by adamdbradley** [comment]
Thank you for opening the issue. To help us debug this further, would you be able to provide a way to replicate this? Thanks

**Comment by guidoknoll** [comment]
I hope i'll find some time to create a minimal example for reproduction the next days. As far as i can see this error happens in combination with the use of rxjs subjects/observables.

**Comment by thccorni** [comment]
I get the same Error testing a component using popper.js
```
TypeError: Cannot read property '$hostElement$' of undefined
    at setValue (/Code/ui-components/node_modules/@stencil/core/dist/runtime/index.js:1368:60)
    at MyPopover.set [as placedAt] (/Code/ui-components/node_modules/@stencil/core/dist/runtime/index.js:1447:25)
    at Object.onCreate (/Code/ui-components/src/components/kiwi-popover/kiwi-popover.tsx:835:21)
    at Popper.call (/Code/ui-components/node_modules/popper.js/src/methods/update.js:71:18)
    at Popper.update$$1 (/Code/ui-components/node_modules/popper.js/src/index.js:94:19)
    at Timeout._onTimeout (/Code/ui-components/node_modules/popper.js/dist/umd/popper.js:64:9)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by guidoknoll** [comment]
As I further inspected this error, it seems like it mostly has to to with rxjs. I often use subjects for managing state across multiple components so i hand over a subject to my stencil web component as a parameter. When i hand over a subject in an unit test spec page and call `.next()` on it, i get the `Cannot read property '$hostElement$' of undefined` error.
This is such an unit test for example:
```tsx
it('should change shown searchterm', async () => {
    const subject = new ReplaySubject<string>();
    const page = await newSpecPage({
        components: [SearchtermInput],
        template: () => (
            <searchterm-input searchTermChange={subject} />
        )
    });
    await page.waitForChanges();
    subject.next('test');
    await page.waitForChanges();
    expect((page.root.querySelector('.search-input') as HTMLInputElement).value).toBe('test');
  });
```
Sadly i can't think of a solution for this, can anyone help?

**Comment by rahul-rautwar** [comment]
As I see you are calling **setTimeout** function in your code,
I am assuming, your have called setTimeoiut function in your **next()** method,
try with the following changes
`
it('should change shown searchterm', async () => {
    const subject = new ReplaySubject<string>();
    const page = await newSpecPage({
        components: [SearchtermInput],
        template: () => (
            <searchterm-input searchTermChange={subject} />
        )
    });
    jest.clearAllTimers();
    await page.waitForChanges();
    subject.next('test');
    jest.advanceTimersByTime(200);
    await page.waitForChanges();
    expect((page.root.querySelector('.search-input') as HTMLInputElement).value).toBe('test');
  });`

and at the top of you spec.ts file add below line before describe block
`jest.useFakeTimers();`

**Comment by ps011** [comment]
Worked like a charm !!

**Comment by guidoknoll** [comment]
Thank you @rahul-rautwar, this worked for me too. I figured out that using
```
testing: {
    timers: 'fake'
}
```
in the stencil.config resolves these errors, too.

**Comment by nghiango** [comment]
I got the same error, I tried to apply some ways above, but I receive the other error.

```
TypeError: Cannot read properties of undefined (reading '$hostElement$')
    at getElement (/Users/ngng/working/projects/test/design-system/node_modules/@stencil/core/internal/testing/index.js:218:378)
    at BjbInternalToast.get el [as el] (/Users/ngng/working/projects/test/design-system/packages/web-components/src/components/internal/test-internal-toast/test-internal-toast.tsx:2357:12)
    at Timeout._onTimeout (/Users/ngng/working/projects/bjb/design-system/packages/web-components/src/components/internal/test-internal-toast/test-internal-toast.tsx:1873:47)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

In the code, I call `setTimeout` inside `componentDidLoad` and `Watch('open')`.

Can anyone help me, please?

**Comment by guidoknoll** [comment]
As @nghiango  mentioned the problem occurs again with the newest version of stencil (4.12.4) and rxjs (7.8.1). The fix with the fake timers sadly doesn't help anymore when subjects are used in unit tests.

Has anyone found a solution for that by now?

The error look similar:
```
TypeError: Cannot read properties of undefined (reading '$hostElement$')

at setValue (/node_modules/@stencil/core/internal/testing/index.js:544:58)
at DatePicker.set [as selectedDate] (/node_modules/@stencil/core/internal/testing/index.js:592:6)
at Object.next (/src/components/filter/custom-datepicker/date-picker/date-picker.tsx:2840:25)
at ConsumerObserver.Object.<anonymous>.ConsumerObserver.next (/node_modules/rxjs/src/internal/Subscriber.ts:161:25)
at SafeSubscriber.Object.<anonymous>.Subscriber._next (/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
at SafeSubscriber.Object.<anonymous>.Subscriber.next (/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
at /node_modules/rxjs/src/internal/Subject.ts:68:20
at Object.errorContext (/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
at Subject.Object.<anonymous>.Subject.next (/node_modules/rxjs/src/internal/Subject.ts:61:5)
at DatePicker.selectDate (/src/components/filter/custom-datepicker/date-picker/date-picker.tsx:3010:27)
at MockButtonElement.onClick (/src/components/filter/custom-datepicker/date-picker/date-picker.tsx:2791:23)
at /node_modules/@stencil/core/mock-doc/index.cjs:728:34
at Array.forEach (<anonymous>)
at triggerEventListener (/node_modules/@stencil/core/mock-doc/index.cjs:726:19)
at dispatchEvent (/node_modules/@stencil/core/mock-doc/index.cjs:750:5)
at MockButtonElement.click (/node_modules/@stencil/core/mock-doc/index.cjs:3495:9)
at Object.<anonymous> (/src/components/filter/custom-datepicker/date-picker/date-picker.spec.tsx:104:69)
at processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by rwaskiewicz** [comment]
Hey folks,

This issue is over four years old - can we please open a new issue if this is an issue with a minimal reproduction case? While it may be that an old issue has reappeared, it's also likely this is a new issue that appears to be the same.  I'm going to close this, but please feel free to open a new issue.
