### ISSUE TITLE
Build fails if assetsDirs has a variable

### ISSUE THREAD

**Issue by jcfranco** [ionic-team/stencil#2085]
**Stencil version:**

```
 @stencil/core@1.8.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

If `assetsDirs` has a variable, the build fails with the following error:

```
Build Error
TypeError: Cannot read property 'trim' of undefined 
at /Users/jcfranco/dev/projects/stencil-component-starter/node_modules/@stencil/core/dist/compiler/index.js:8933:33 
at Array.map (<anonymous>) 
at parseAssetsDirs (/Users/jcfranco/dev/projects/stencil-component-starter/node_modules/@stencil/core/dist/compiler/index.js:8931:17) 
at parseStaticComponentMeta (/Users/jcfranco/dev/projects/stencil-component-starter/node_modules/@stencil/core/dist/compiler/index.js:8824:21) 
at visitNode (/Users/jcfranco/dev/projects/stencil-component-starter/node_modules/@stencil/core/dist/compiler/index.js:8959:24) 
at visitNodes (/Users/jcfranco/dev/projects/stencil-component-starter/node_modules/typescript/lib/typescript.js:70955:48) 
at visitLexicalEnvironment (/Users/jcfranco/dev/projects/stencil-component-starter/node_modules/typescript/lib/typescript.js:70988:22) 
at Object.visitEachChild (/Users/jcfranco/dev/projects/stencil-component-starter/node_modules/typescript/lib/typescript.js:71301:54) 
at visitNode (/Users/jcfranco/dev/projects/stencil-component-starter/node_modules/@stencil/core/dist/compiler/index.js:8970:34) 
at /Users/jcfranco/dev/projects/stencil-component-starter/node_modules/@stencil/core/dist/compiler/index.js:8985:20


```

**Expected behavior:**

No error and build succeeds.

**Steps to reproduce:**

1. Clone `stencil-component-starter` 
2. Modify `my-component.tsx` with code below.
3. Run `npm start`

**Related code:**

```tsx
const assetsDir = "assets";

@Component({
  tag: 'my-component',
  assetsDirs: [assetsDir],
  styleUrl: 'my-component.css',
  shadow: true
})
```

**Other information:**

**Comment by adamdbradley** [comment]
Decorator data must be statically analyzable. And while it could parse the variable, we need to draw the line somewhere of what a variable can and cannot provide, so it's best to just keep the data static within the decorator. Thanks

**Comment by jcfranco** [comment]
Makes sense, thanks!
