### ISSUE TITLE
E2E tests with newE2EPage are always timing out

### ISSUE THREAD

**Issue by kairos666** [ionic-team/stencil#2096]
**Stencil version:**
```
 @stencil/core@1.8.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When a e2e test is run and it contains a page context creation
```
const page = await newE2EPage();
```
Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.Error:

**Expected behavior:**
e2e test execute without timing out at the very beginning of the test

**Steps to reproduce:**

1. new project with **npm init stencil** and component library setup
2. npm install dependencies
3. npm run test
can be reproduce right after generating the new project with test examples

**Related code:**

```console
FAIL  src/components/my-component/my-component.e2e.ts (64.301s)
  ● my-component › renders

    : Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.Error:

      2 |
      3 | describe('my-component', () => {
    > 4 |   it('renders', async () => {
        |   ^
      5 |     const page = await newE2EPage();
      6 |
      7 |     await page.setContent('<my-component></my-component>');

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.Object.<anonymous>.describe (src/components/my-component/my-component.e2e.ts:4:3)
```

**Other information:**
OS win7
Node v10.15.3
looks pretty similar to #1145

**Comment by kairos666** [comment]
same issue with Node v13.5.0
