### ISSUE TITLE
Getting `Cannot read property 'get' of undefined` during JEST tests

### ISSUE THREAD

**Issue by hypery2k** [ionic-team/stencil#2123]
**Stencil version:**
```
@stencil/core@1.7.5
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Running tests work, but getting following output:

```
 PASS  products.component.spec.ts (16.964s)
  ● Console

    console.error node_modules/zone.js/dist/zone.js:703
      Unhandled Promise rejection: Cannot read property 'get' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'get' of undefined
          at lazyBundle.(anonymous function).forEach.compactMeta (/tmp/frontend/node_modules/@web-components-lib/ui-components-c
ore/dist/cjs/core-682f4fdf.js:1723:59)
          at Array.forEach (<anonymous>)
          at lazyBundles.forEach.lazyBundle (/tmp/frontend/node_modules/@web-components-lib/ui-components-core/dist/cjs/core-682
f4fdf.js:1655:53)
          at Array.forEach (<anonymous>)
          at Object.bootstrapLazy (/tmp/frontend/node_modules/@web-components-lib/ui-components-core/dist/cjs/core-682f4fdf.js:1655:17)
          at core.patchEsm.then (/tmp/frontend/node_modules/@web-components-lib/ui-components-core/dist/cjs/loader.cjs.js:10:10)
          at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (/tmp/frontend/node_modules/zone.js/dist/zone.js:391:26)
          at Zone.Object.<anonymous>.Zone.run (/tmp/frontend/node_modules/zone.js/dist/zone.js:150:43)
          at /tmp/frontend/node_modules/zone.js/dist/zone.js:910:34
          at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (/tmp/frontend/node_modules/zone.js/dist/zone.js:423:31)
          at Zone.Object.<anonymous>.Zone.runTask (/tmp/frontend/node_modules/zone.js/dist/zone.js:195:47)
          at drainMicroTaskQueue (/tmp/frontend/node_modules/zone.js/dist/zone.js:601:35)
          at Object.<anonymous>.ZoneTask.invokeTask (/tmp/frontend/node_modules/zone.js/dist/zone.js:502:21)
          at ZoneTask.invoke (/tmp/frontend/node_modules/zone.js/dist/zone.js:487:48)
          at timer (/tmp/frontend/node_modules/zone.js/dist/zone.js:3070:29)
          at Timeout.callback [as _onTimeout] (/tmp/frontend/node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)
          at ontimeout (timers.js:436:11)
          at tryOnTimeout (timers.js:300:5)
          at listOnTimeout (timers.js:263:5)
          at Timer.processTimers (timers.js:223:10) TypeError: Cannot read property 'get' of undefined
          at lazyBundle.(anonymous function).forEach.compactMeta (/tmp/frontend/node_modules/@web-components-lib/ui-components-core/dist/cjs/core-682f4fdf.js:1723:59)
          at Array.forEach (<anonymous>)
          at lazyBundles.forEach.lazyBundle (/tmp/frontend/node_modules/@web-components-lib/ui-components-core/dist/cjs/core-682f4fdf.js:1655:53)
          at Array.forEach (<anonymous>)
          at Object.bootstrapLazy (/tmp/frontend/node_modules/@web-components-lib/ui-components-core/dist/cjs/core-682f4fdf.js:1655:17)
          at core.patchEsm.then (/tmp/frontend/node_modules/@web-components-lib/ui-components-core/dist/cjs/loader.cjs.js:10:10)
          at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (/tmp/frontend/node_modules/zone.js/dist/zone.js:391:26)
          at Zone.Object.<anonymous>.Zone.run (/tmp/frontend/node_modules/zone.js/dist/zone.js:150:43)
          at /tmp/frontend/node_modules/zone.js/dist/zone.js:910:34
          at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (/tmp/frontend/node_modules/zone.js/dist/zone.js:423:31)
          at Zone.Object.<anonymous>.Zone.runTask (/tmp/frontend/node_modules/zone.js/dist/zone.js:195:47)
          at drainMicroTaskQueue (/tmp/frontend/node_modules/zone.js/dist/zone.js:601:35)
          at Object.<anonymous>.ZoneTask.invokeTask (/tmp/frontend/node_modules/zone.js/dist/zone.js:502:21)
          at ZoneTask.invoke (/tmp/frontend/node_modules/zone.js/dist/zone.js:487:48)
          at timer (/tmp/frontend/node_modules/zone.js/dist/zone.js:3070:29)
          at Timeout.callback [as _onTimeout] (/tmp/frontend/node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)
          at ontimeout (timers.js:436:11)
          at tryOnTimeout (timers.js:300:5)
          at listOnTimeout (timers.js:263:5)
          at Timer.processTimers (timers.js:223:10)
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/tmp/frontend/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at Request.client.on.err (/tmp/frontend/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at Request.emit (events.js:194:15)
          at Request.onRequestError (/tmp/frontend/node_modules/request/request.js:881:8)
          at ClientRequest.emit (events.js:189:13)
          at Socket.socketErrorListener (_http_client.js:392:9)
          at Socket.emit (events.js:189:13)
          at emitErrorNT (internal/streams/destroy.js:82:8)
          at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
          at process._tickCallback (internal/process/next_tick.js:63:19) undefined
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/tmp/frontend/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at Request.client.on.err (/tmp/frontend/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at Request.emit (events.js:194:15)
          at Request.onRequestError (/tmp/frontend/node_modules/request/request.js:881:8)
          at ClientRequest.emit (events.js:189:13)
          at Socket.socketErrorListener (_http_client.js:392:9)
          at Socket.emit (events.js:189:13)
          at emitErrorNT (internal/streams/destroy.js:82:8)
          at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
          at process._tickCallback (internal/process/next_tick.js:63:19) undefined
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/tmp/frontend/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at Request.client.on.err (/tmp/frontend/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at Request.emit (events.js:194:15)
          at Request.onRequestError (/tmp/frontend/node_modules/request/request.js:881:8)
          at ClientRequest.emit (events.js:189:13)
          at Socket.socketErrorListener (_http_client.js:392:9)
          at Socket.emit (events.js:189:13)
          at emitErrorNT (internal/streams/destroy.js:82:8)
          at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
          at process._tickCallback (internal/process/next_tick.js:63:19) undefined
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/tmp/frontend/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at Request.client.on.err (/tmp/frontend/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at Request.emit (events.js:194:15)
          at Request.onRequestError (/tmp/frontend/node_modules/request/request.js:881:8)
          at ClientRequest.emit (events.js:189:13)
          at Socket.socketErrorListener (_http_client.js:392:9)
          at Socket.emit (events.js:189:13)
          at emitErrorNT (internal/streams/destroy.js:82:8)
          at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
          at process._tickCallback (internal/process/next_tick.js:63:19) undefined
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/tmp/frontend/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at Request.client.on.err (/tmp/frontend/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at Request.emit (events.js:194:15)
          at Request.onRequestError (/tmp/frontend/node_modules/request/request.js:881:8)
          at ClientRequest.emit (events.js:189:13)
          at Socket.socketErrorListener (_http_client.js:392:9)
          at Socket.emit (events.js:189:13)
          at emitErrorNT (internal/streams/destroy.js:82:8)
          at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
          at process._tickCallback (internal/process/next_tick.js:
```

**Expected behavior:**
No this console output
**Steps to reproduce:**

```
npm test
```

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**
maybe related to this [one](https://github.com/ionic-team/stencil/issues/2056).

**Comment by adamdbradley** [comment]
This looks like an issue with Angular's ngzone and jsdom. If you can create a repo case showing it's a stencil issue that would help us debug. Thanks

**Comment by rlam3** [comment]
@hypery2k were you able to find a workaround?
