### ISSUE TITLE
[1.9.0-14 --next] Unexpected identifier let scopeId; error when using hydrate app

### ISSUE THREAD

**Issue by viljamis** [ionic-team/stencil#2144]
**Stencil version:**
```
 @stencil/core@1.9.0-12 (using --next)
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Hydrate app renderToString causes Eleventy to throw `Unexpected identifier "let scopeId;"` error when using `--next` flag.

**Expected behavior:**
Without `--next` flag everything is working like previously.

**Steps to reproduce:**
I’m basically trying to do what I’ve described in our documentation here: https://www.duetds.com/server-side-rendering/#ssr-configuration This works in`1.9.0-12` without the next flag, but not anymore when using `--next` compiler. The exact error in console is:

```shell
Eleventy fatal error: (more in DEBUG output)
> Error in your Eleventy config file '/duet/docs/.eleventy.js'.

`EleventyConfigError` was thrown
> Unexpected identifier

`SyntaxError` was thrown:
    /duet/packages/components/hydrate/index.js:3790
    let scopeId;
        ^^^^^^^
    
    SyntaxError: Unexpected identifier
        at Module._compile (internal/modules/cjs/loader.js:895:18)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
        at Module.load (internal/modules/cjs/loader.js:815:32)
        at Function.Module._load (internal/modules/cjs/loader.js:727:14)
        at Module.require (internal/modules/cjs/loader.js:852:19)
        at require (internal/modules/cjs/helpers.js:74:18)
        at Object.<anonymous> (/duet/docs/.eleventy.js:9:17)
        at Module._compile (internal/modules/cjs/loader.js:959:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
        at Module.load (internal/modules/cjs/loader.js:815:32)
```

**Related code:**

```js
const hydrate = require(".../packages/components/hydrate")

module.exports = function(config) {
  config.addTransform("hydrate", async (content, outputPath) => {
    if (outputPath.endsWith(".html")) {
      try {
        const results = await hydrate.renderToString(content, {
          clientHydrateAnnotations: true,
          removeScripts: false,
          removeUnusedStyles: false
        })
        return results.html
      } catch (error) {
        return error
      }
    }
    return content
  })
}
```

**Comment by viljamis** [comment]
@adamdbradley Looks like this is still happening with the latest prerelease as well. I also found out that the same issue happens with Gatsby too if trying to build the project. The error from Gatsby was a bit more useful though since I was able to find the exact line causing this. 

**See line 3784 in the generated hydrate/index.js file:**

<img width="900" alt="Screen Shot 2020-02-05 at 14 08 53" src="https://user-images.githubusercontent.com/671836/73840835-c8e82880-4821-11ea-8eba-86470e60e2ea.png">

I now wonder where that could be coming from...?

**Comment by viljamis** [comment]
Think I now found the simplest way to reproduce this.  In stencil.config.ts, if you use `globalScript` setting with something like:

```js
export const config: Config = {
  globalScript: "src/global/global.ts",
}
```

…It will break the hydrate app build when using `--next` flag. This happens even if the `global.ts` file doesn’t have anything in it.

Hope this helps @adamdbradley!
