### ISSUE TITLE
Since v1.10.2 SVGAttribute attributeName and xlinkHref not recognized by the compiler

### ISSUE THREAD

**Issue by jepiqueau** [ionic-team/stencil#2313]
**Stencil version:**

```
 @stencil/core@10.1.2
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

``` 
[ ERROR ]  TypeScript: ./src/components/jeep-linechart/jeep-linechart.tsx:716:58
           Type '{ class: string; attributeName: string; from: string; to:
           string; dur: string; fill: string; }' is not assignable to type
           'SVGAttributes<SVGElement>'.Property 'attributeName' does not exist
           on type 'SVGAttributes<SVGElement>'.

    L715:  stroke-dashoffset={length.toString()}>
    L716:    <animate class= "linechart-data-animate" attributeName="stroke-dashoffset" from={length.toString()}
    L717:    to="0" dur={this._prop.animDuration} fill="freeze">

[ ERROR ]  TypeScript: ./src/components/jeep-linechart/jeep-linechart.tsx:765:33
           Type '{ class: string; xlinkHref: string; id: string; x: string; y:
           string; width: string; height: string; transform: string; }' is not
           assignable to type 'SVGAttributes<SVGElement>'.Property 'xlinkHref'
           does not exist on type 'SVGAttributes<SVGElement>'.

    L764:  <g id={`${id}-g-${line.toString()}-${index.toString()}`} class={`marker ${id}`} fill={color}>
    L765:    <use class="marker-use" xlinkHref={`#${id}`} id={`${id}-${line.toString()}-${index.toString()}`} 
    L766:      x={(pt.x - 5).toString()} y={(pt.y - 5).toString()} width="10" height="10"


```
**Expected behavior:**

should compile without Error this is what happened prior 1.10.2
**Steps to reproduce:**

visit 
```
https://github.com/jepiqueau/jeep-linechart
```
**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by Jagget** [comment]
You need to switch to kebab-style: `xlink-href` and `attribute-name`

**Comment by jepiqueau** [comment]
@Jagget @manucorporat Thanks now it build without message but i got the following error at execution time
```
index-5b5b8a98.js:2668 DOMException: Failed to execute 'setAttributeNS' on 'Element': The qualified name provided ('-href') contains the invalid name-start character '-'.
    at setAccessor (http://localhost:3333/build/index-5b5b8a98.js:618:25)
    at updateElement (http://localhost:3333/build/index-5b5b8a98.js:646:9)
    at createElm (http://localhost:3333/build/index-5b5b8a98.js:695:13)
    at createElm (http://localhost:3333/build/index-5b5b8a98.js:705:29)
    at createElm (http://localhost:3333/build/index-5b5b8a98.js:705:29)
    at addVnodes (http://localhost:3333/build/index-5b5b8a98.js:776:25)
    at patch (http://localhost:3333/build/index-5b5b8a98.js:967:13)
    at updateChildren (http://localhost:3333/build/index-5b5b8a98.js:836:13)
    at patch (http://localhost:3333/build/index-5b5b8a98.js:958:13)
    at updateChildren (http://localhost:3333/build/index-5b5b8a98.js:836:13)
```
I have updated on github so you can have a look

**Comment by jepiqueau** [comment]
@Jagget @manucorporat the memberName in the setAccessor function should be href and not -href

**Comment by jepiqueau** [comment]
@Jagget @manucorporat the ```ln.replace(/^xlink\:?/, '')``` should be replace by ```ln.replace(/^xlink-\:?/, '')```

**Comment by jepiqueau** [comment]
@Jagget @manucorporat if i do that in the www/build/index-5b5b8a98.js file it works but after this i got stuck with the animation looking at the SVG doc the attributeName should be kept like this and not attribute-name
```
<svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg">
  <rect width="10" height="10">
    <animate attributeName="rx" values="0;5;0" dur="10s" repeatCount="indefinite" />
  </rect>
</svg>
```

**Comment by jepiqueau** [comment]
@Jagget Do i have to create a new issue?

**Comment by jepiqueau** [comment]
@Jagget no i was waiting an answer from you or from manu
