### ISSUE TITLE
No way to write E2E tests for components sending requests on DidLoad

### ISSUE THREAD

**Issue by luchsamapparat** [ionic-team/stencil#2434]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**
[x] bug report

**Current behavior:**
Stencil defines a request interceptor foor Puppeteer when setting content on a page. This leads to a problem when the component sends a request on initialisation and you want to mock that request in an E2E test by defining another request interceptor: `Request is already handled!`

This problem has already been addressed in #2381, however it is unclear how the proposed solution (`newSpecPage`) solves the issue in an E2E scenario.

**Expected behavior:**
I can write E2E tests for components that send a request on initialisation.

**Steps to reproduce:**
I created a project (https://github.com/luchsamapparat/stencil-e2e-request-mock) that reproduces the problem I currently have in my actual project:

- MyComponent uses a property value (`this.url`) to send a request on `DidLoad`: 

```ts
  async componentDidLoad() {
    if (!this.url) {
      return;
    }
    const response = await fetch(this.url);
    this.example = await response.json();
  }
```

- In the corresponding E2E test, the only way to test this (at least from what I understand), is to define a Puppeteer interceptor:

```ts
  it('renders', async () => {
    const page = await newE2EPage();

    await page.setRequestInterception(true);

    page.on('request', (request) => {

      if (request.url() === mockUrl) {
        request.respond({
          body: JSON.stringify(mockResponse)
        })
      }

      request.continue();
    });

    await page.setContent(`<my-component url="${mockUrl}"></my-component>`);
    const element = await page.find('my-component');

    page.waitForChanges();

    expect(element.textContent).toBe(JSON.stringify(mockResponse))
  });
```

- `npm test` produces this error:

```
 FAIL  src/components/my-component/my-component.e2e.ts
  my-component
    × renders (223ms)

  ● my-component › renders

    Request is already handled!

      at assert (node_modules/puppeteer/lib/helper.js:283:11)
      at Request.respond (node_modules/puppeteer/lib/NetworkManager.js:456:5)
      at Request.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at Page.interceptedReqCallback (node_modules/@stencil/core/testing/index.js:6623:32)
      at NetworkManager.<anonymous> (node_modules/puppeteer/lib/Page.js:110:68)
      at NetworkManager._onRequest (node_modules/puppeteer/lib/NetworkManager.js:234:10)
      at NetworkManager._onRequestPaused (node_modules/puppeteer/lib/NetworkManager.js:210:12)
        -- ASYNC --
      at Request.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at Page.interceptedReqCallback (node_modules/@stencil/core/testing/index.js:6623:32)
      at NetworkManager.<anonymous> (node_modules/puppeteer/lib/Page.js:110:68)
      at NetworkManager._onRequest (node_modules/puppeteer/lib/NetworkManager.js:234:10)
      at NetworkManager._onRequestPaused (node_modules/puppeteer/lib/NetworkManager.js:210:12)
      at CDPSession._onMessage (node_modules/puppeteer/lib/Connection.js:200:12)
      at Connection._onMessage (node_modules/puppeteer/lib/Connection.js:112:17)
```

**Comment by luchsamapparat** [comment]
> @xiyuan-fengyu I see. Every request should be handled exactly once. This is not an artificial constraint: we cannot simultaneously "continue" request and "abort" it.
> [...]
> Your framework has to do some arbitration on it's side to decide what it wants to do with every request. A good rule of a thumb is to have only one "request" listener that carries all the logic to decide request's fate.

https://github.com/puppeteer/puppeteer/issues/4524

This sounds to me as if Stencil should provide its own API to do request interception which in turn ensures that `.on('request', ...)` is only called once.

I'd provide a PR for a change like this, however as this affects the public API, I'd like to discuss with you first if this aligns with your plans and how you'd image an API like this.

**Comment by xiyuan-fengyu** [comment]
In my solution, I rewrite methods of Page: "addListener", "on", "once", "prependListener", "prependOnceListener", "removeListener", "off", "listeners", "rawListeners",  "listenerCount"。
https://github.com/xiyuan-fengyu/ppspider/blob/master/src/puppeteer/PuppeteerWorkerFactory.ts

**Comment by xiyuan-fengyu** [comment]
In your case,  it's not valid to call request.continue() after request.respond()

**Comment by luchsamapparat** [comment]
Of course, you're right. My example was missing a `return` statement. I updated the reproduction project.

However, that's not the issue as Stencil's request interceptor already handles every request before my custom one is being called.

Here's the output of the updated test:

```
 FAIL  src/components/my-component/my-component.e2e.ts
  my-component
    × renders (208ms)

  ● my-component › renders

    Request is already handled!

      at assert (node_modules/puppeteer/lib/helper.js:283:11)
      at Request.respond (node_modules/puppeteer/lib/NetworkManager.js:456:5)
      at Request.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at Page.interceptedReqCallback (node_modules/@stencil/core/testing/index.js:6623:32)
      at NetworkManager.<anonymous> (node_modules/puppeteer/lib/Page.js:110:68)
      at NetworkManager._onRequest (node_modules/puppeteer/lib/NetworkManager.js:234:10)
      at NetworkManager._onRequestPaused (node_modules/puppeteer/lib/NetworkManager.js:210:12)
        -- ASYNC --
      at Request.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at Page.interceptedReqCallback (node_modules/@stencil/core/testing/index.js:6623:32)
      at NetworkManager.<anonymous> (node_modules/puppeteer/lib/Page.js:110:68)
      at NetworkManager._onRequest (node_modules/puppeteer/lib/NetworkManager.js:234:10)
      at NetworkManager._onRequestPaused (node_modules/puppeteer/lib/NetworkManager.js:210:12)
      at CDPSession._onMessage (node_modules/puppeteer/lib/Connection.js:200:12)
      at Connection._onMessage (node_modules/puppeteer/lib/Connection.js:112:17)

  console.warn src/components/my-component/my-component.e2e.ts:14
    Requesting http://localhost:3333/

  console.error node_modules/@stencil/core/testing/index.js:6545
    requestfailed http://localhost:3333/

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        4.615s
Ran all test suites.
```

**Comment by xiyuan-fengyu** [comment]
so you want custom handlers has high priority than Stencil's request interceptor. in my opinion, you can rewrite methods like page.addListeners, and assign each handler  a priority, sort handlers when add new handler, when request is coming, handlers line up to deal with request if the previous handler didn't call continue, abort or response。

**Comment by fredcido** [comment]
I am also facing the same problem, I need to mock some failure responses and having the same issue with Stencil interceptors:

```
const page = await newE2EPage();

    await page.setRequestInterception(true);  

    page.on('request', request => {
      if (request.url().includes('/settings')) {
        request.respond({
          status: 401,
        });
      }
    });

    await page.setContent(html);
    await page.waitForChanges();
```


Getting the error:

```
Request is already handled!

      at assert (node_modules/puppeteer/lib/helper.js:283:11)
      at Request.continue (node_modules/puppeteer/lib/NetworkManager.js:427:5)
      at Request.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at Page.e.on.e (node_modules/@stencil/core/testing/index.js:997:20)
      at NetworkManager.Page.networkManager.on.event (node_modules/puppeteer/lib/Page.js:110:68)
      at NetworkManager._onRequest (node_modules/puppeteer/lib/NetworkManager.js:234:10)
      at NetworkManager._onRequestWillBeSent (node_modules/puppeteer/lib/NetworkManager.js:167:14)
        -- ASYNC --
      at Request.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at Page.e.on.e (node_modules/@stencil/core/testing/index.js:997:20)
      at NetworkManager.Page.networkManager.on.event (node_modules/puppeteer/lib/Page.js:110:68)
      at NetworkManager._onRequest (node_modules/puppeteer/lib/NetworkManager.js:234:10)
      at NetworkManager._onRequestWillBeSent (node_modules/puppeteer/lib/NetworkManager.js:167:14)
      at CDPSession._onMessage (node_modules/puppeteer/lib/Connection.js:200:12)
      at Connection._onMessage (node_modules/puppeteer/lib/Connection.js:112:17)
```

**Comment by luchsamapparat** [comment]
Good to know that I am not the only one with this issue. I still haven't found a solution for this problem.

I heard that the Stencil-Team is thinking about replacing Puppeteer with Playwright ([see this Tweet](https://twitter.com/adamdbradley/status/1220171102409850880)). From what I understand from the Playwright docs, this might help us:

https://github.com/microsoft/playwright/blob/master/docs/network.md#network-events

**Comment by luchsamapparat** [comment]
@adamdbradley is this still on the roadmap?

**Comment by doctor-house** [comment]
I was able to get around this issue in my e2e tests with the following:

```javascript
const page = await newE2EPage();

page.on('response', response => {
  const e2ePage = page;
  if (response.url() === 'http://localhost:3333/') {
    e2ePage.removeAllListeners('request');
    e2ePage.setRequestInterception(true);
    page.on('request', request => {
      // you can mock responses here
      if (request.url().includes('test')) {
        request.respond({...});
      }
      else {
        request.continue();
      }
    });
  }
});
```
kind of a hack but it works in my tests so 🤷🏻‍♂️

**Comment by elebetsamer** [comment]
@doctor-house Which version of stencil were you using for you work around? I'm on version 2.1.2 at the moment and I'm getting the below error:

![image](https://user-images.githubusercontent.com/75610/99327789-8b441180-282f-11eb-9ac9-5c0ece07144f.png)

**Comment by doctor-house** [comment]
@elebetsamer Im using 2.1.2. Your issue is because `removeAllListeners` is from the `EventEmitter` interface from puppeteer. Use this to get around it:
```ts
(page as any).removeAllListeners('request');
```
I updated my example to be more correct :)

**Comment by laureanray** [comment]
I'm still experiencing this with `2.5.0` are there any plans to fix this or any work arounds?
