### ISSUE TITLE
Test Failed: "flushQueue: Error: referenceNode not found in parentNode.childNodes"

### ISSUE THREAD

**Issue by petergaal91** [ionic-team/stencil#2455]
**Stencil version:**

```
 @stencil/core@1.12.2 and 1.13.0 also
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I want to test property and I receive the following error when I want to wait for the changes:

```
Failed: "flushQueue: Error: referenceNode not found in parentNode.childNodes"

      22 |      });
      23 | 
    > 24 |      it('should render label correctly', async () => {
         |      ^
      25 |              page = await mountComponent();
      26 |              page.rootInstance.label = null;
      27 | 
      28 |              expect(page.rootInstance.renderLabel()).toBe(null);
      29 |
      30 |              page.rootInstance.label = 'Card label';
      31 |
      32 |              await page.waitForChanges(); // <- this line cause this error

      at Env.it (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:91:24)
      at Suite.<anonymous> (src/components/my-component/my-component.spec.ts:24:2)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:13:1)
```

**Expected behavior:**
Do not receive an error

**Steps to reproduce:**
1, Checkout this repository: https://github.com/petergaal91/stencil-sass-path-resolve-bug
2, Run `npm install && npm test`

**Related code:**

```tsx
it('should render label correctly', async () => {
	page = await mountComponent();
	page.rootInstance.label = null;

	expect(page.rootInstance.renderLabel()).toBe(null);

	page.rootInstance.label = 'Card label';

	await page.waitForChanges(); // <- this line cause this error

	expect(page.root?.querySelector('.s-card-header-label')?.textContent).toBe('Card label');
	expect(page.rootInstance.renderLabel()).toMatchSnapshot();
});
```

**Other information:**
OS: Windows 10 build 2004
Node version: 12.16.1

**Comment by rwaskiewicz** [comment]
Hey there 👋 

I apologize it took so long for someone to acknowledge this issue. It looks like the reproduction case no longer exists. If you're willing/able, could you please reupload it for someone to take a look? If not, I completely understand. Thanks!
