### ISSUE TITLE
[@1.14.0-0] Rollup error: 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by adamlacombe** [ionic-team/stencil#2462]
**Stencil version:**

```
 @stencil/core@1.14.0-0
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

`npm run build` throws the following error when a component [imports a decorator](https://github.com/adamlacombe/stencil-rollup-import-decorator-issue/blob/master/src/components/app-home/app-home.tsx#L2-L9):

```stacktrace
[ ERROR ]  Rollup: Parse Error: ./src/components/app-home/app-home.tsx:16:4
           'import' and 'export' may only appear at the top level (Note that you need plugins to import files that are
           not JavaScript) at error
           (/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@stencil/core/compiler/stencil.js:41769:26)
           at Module$1.error
           (/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@stencil/core/compiler/stencil.js:46176:12)
           at tryParse$1
           (/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@stencil/core/compiler/stencil.js:46065:19)
           at Module$1.setSource
           (/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@stencil/core/compiler/stencil.js:46464:24)
           at ModuleLoader.addModuleSource
           (/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@stencil/core/compiler/stencil.js:48497:14)
           at process._tickCallback (internal/process/next_tick.js:68:7)

     L15:      <ion-title>Home</ion-title>
     L16:    </ion-toolbar>
     L17:  </ion-header>,
```

**Expected behavior:**

**Steps to reproduce:**

```bash
git clone https://github.com/adamlacombe/stencil-rollup-import-decorator-issue.git && cd stencil-rollup-import-decorator-issue && npm install && npm run build
```

**Related code:**

```javascript
import { registerInstance as __stencil_registerInstance } from "@stencil/core/internal/client";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function")
        r = Reflect.decorate(decorators, target, key, desc);
    else
        for (var i = decorators.length - 1; i >= 0; i--)
            if (d = decorators[i])
                r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
import { h } from "@stencil/core/internal/client";
import { CustomDecorator } from '../../helpers/utils';
import appHomeStyle from "./app-home.css?tag=app-home";
let AppHome = /** @class */ (() => {
    export const AppHome = class {
        constructor(hostRef) {
            __stencil_registerInstance(this, hostRef);
        }
        render() {
            return [
                h("ion-header", null, h("ion-toolbar", { color: "primary" }, h("ion-title", null, "Home"))),
                h("ion-content", { class: "ion-padding" }, h("p", null, "Welcome to the PWA Toolkit. You can use this starter to build entire apps with web components using Stencil and ionic/core! Check out the README for everything that comes in this starter out of the box and check out our docs on ", h("a", { href: "https://stenciljs.com" }, "stenciljs.com"), " to get started."), h("ion-button", { href: "/profile/ionic", expand: "block" }, "Profile page"))
            ];
        }
    };
    __decorate([
        CustomDecorator()
    ], AppHome.prototype, "test", void 0);
    return AppHome;
})();
export { AppHome };
AppHome.style = appHomeStyle;
```

The compiled code should place the following after the imports 
```javascript
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function")
        r = Reflect.decorate(decorators, target, key, desc);
    else
        for (var i = decorators.length - 1; i >= 0; i--)
            if (d = decorators[i])
                r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
```

**Other information:**

**Comment by manucorporat** [comment]
Can you give it a try to `@stencil/core@1.14.0-1`?

**Comment by adamlacombe** [comment]
Same error unfortunately

```
[51:55.3]  @stencil/core v1.14.0-1 🚜

[ WARN  ]  This is a prerelease build, undocumented changes might happen at any time. Technical support is not
           available for prereleases, but any assistance testing is appreciated.

[51:55.3]  linux, AMD Ryzen 7 1700 Eight-Core Processor  MEM: 96.2MB
[51:55.3]  cpus: 16, freemem: 35979MB, totalmem: 50531MB  MEM: 96.2MB
[51:55.3]  node v10.17.0  MEM: 96.2MB
[51:55.3]  compiler:
           /home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@stencil/core/compiler/stencil.js 
           MEM: 96.2MB
[51:55.3]  build: 20200522112351  MEM: 96.2MB
[51:55.3]  cache optimizations disabled
[51:55.3]  Starting compilation in watch mode...  MEM: 98.5MB
[51:56.4]  build, app, prod mode, started ...
[51:56.4]  start build, 2020-05-25T13:51:56  MEM: 183.2MB
[51:56.4]  cleaning 1 dirs ...  MEM: 183.2MB
[51:56.4]  empty dir: /home/adam/repos/stencil-rollup-import-decorator-issue/www  MEM: 183.2MB
[51:56.4]  cleaning dirs finished in 61 ms  MEM: 186.5MB
[51:56.5]  transpile started ...
[51:57.1]  load collection: @ionic/core, ./node_modules/@ionic/core/dist/collection/collection-manifest.json  MEM:
           208.5MB
[51:57.7]  load collection: ionicons, ./node_modules/ionicons/dist/collection/collection-manifest.json  MEM:
           252.6MB
[51:57.7]  Transpiled modules: [ "/home/adam/repos/stencil-rollup-import-decorator-issue/src/helpers/utils.ts",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/src/components/app-home/app-home.tsx",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/src/components/app-profile/app-profile.tsx",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/src/components/app-root/app-root.tsx",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/src/global/app.ts",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/global/ionic-global.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/action-sheet-controller/action-sheet-controller.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/action-sheet/action-sheet.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/alert-controller/alert-controller.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/alert/alert.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/avatar/avatar.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/back-button/back-button.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/anchor/anchor.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/backdrop/backdrop.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/app/app.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/badge/badge.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/buttons/buttons.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/card-content/card-content.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/button/button.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/card-subtitle/card-subtitle.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/card/card.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/card-header/card-header.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/chip/chip.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/col/col.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/card-title/card-title.js",
           "/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@ionic/core/dist/collection/components/content/content.js",
[51:57.7]  generated app types started ...  MEM: 252.8MB
[51:57.7]  generated app types finished: ./src/components.d.ts in 2 ms  MEM: 252.8MB
[51:58.5]  transpile finished in 2.02 s
[51:58.5]  generate outputs started ...  MEM: 269.4MB
[51:58.5]  getComponentAssetsCopyTasks: 2  MEM: 269.4MB
[51:58.5]  copy started ...
[51:58.5]  generate lazy started ...
[51:58.5]  generateEntryModules, 90 entryModules  MEM: 269.4MB
[51:58.7]  generate lazy finished in 233 ms
[51:58.7]  generate www started ...  MEM: 273.9MB
[51:58.8]  generateIndexHtml, write: ./www/index.html  MEM: 277.0MB
[51:58.8]  generate www finished in 86 ms  MEM: 277.0MB
[51:59.7]  copy finished (704 files) in 1.23 s
[51:59.7]  generate outputs finished in 1.23 s  MEM: 282.0MB
[51:59.7]  aborted build, 2020-05-25T13:51:56  MEM: 282.0MB

[ ERROR ]  Rollup: Parse Error: ./src/components/app-home/app-home.tsx:16:4
           'import' and 'export' may only appear at the top level (Note that you need plugins to import files that are
           not JavaScript) at error
           (/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@stencil/core/compiler/stencil.js:44948:26)
           at Module$1.error
           (/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@stencil/core/compiler/stencil.js:49359:12)
           at tryParse$1
           (/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@stencil/core/compiler/stencil.js:49248:19)
           at Module$1.setSource
           (/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@stencil/core/compiler/stencil.js:49649:24)
           at ModuleLoader.addModuleSource
           (/home/adam/repos/stencil-rollup-import-decorator-issue/node_modules/@stencil/core/compiler/stencil.js:51696:14)
           at process._tickCallback (internal/process/next_tick.js:68:7)

     L15:      <ion-title>Home</ion-title>
     L16:    </ion-toolbar>
     L17:  </ion-header>,

[51:59.7]  build failed in 3.33 s
```
