### ISSUE TITLE
defineCustomElements does not work in Jest environment

### ISSUE THREAD

**Issue by gassiss** [ionic-team/stencil#2603]
**Stencil version:**
```
 @stencil/core@1.12.2
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
`defineCustomElements` does not define custom elements in Jest environment.

**Expected behavior:**
Expected `defineCustomElements` to successfully define custom elements created with stencil

**Steps to reproduce:**
I’ve put up a minimum repo that you can check here: https://github.com/gassiss/stencil-jest

This repo essentially glues together the initial boilerplate generated by Vue and StencilJS.

In the `hello-world` folder you can `npm run serve` to start the dev server. If you open the browser console and run `window.customElements.get('my-component')` you'll see that everything is working as intended. (This is the example component generated by stencil)

The problem is, when I write unit tests for my Vue app, `my-component` is not defined. If you go to `tests/unit/example.spec.js`, I'm logging the result, which is `undefined`. If you enable line 10 you'll see that manually declaring the custom element work as intended.

**Other information:**
Thank you for your hard work on this lib! 

My apologies if this was already covered in the docs/past issues, it is a very hard topic to do research for! All I could find was how to use `Jest` to test `StencilJS` components from the perspective of the person **creating** the Design System, but not from the perspective of the one **using** it.

**Comment by chiyema** [comment]
jsdom 16.2.0 starts supporting CustomElements. https://github.com/jsdom/jsdom/releases/tag/16.2.0

**Comment by gassiss** [comment]
> jsdom 16.2.0 starts supporting CustomElements. https://github.com/jsdom/jsdom/releases/tag/16.2.0

I was able to get CustomElements to work by using [jsdom-environment-sixteen](https://www.npmjs.com/package/jest-environment-jsdom-sixteen). Enabled it on the test [here](https://github.com/gassiss/stencil-jest/blob/master/hello-world/tests/unit/example.spec.js#L2).

The problem is calling `defineCustomElements` from `stencil` doesn't seem to be doing anything! Defining it manually, as evidenced on [L10 here](https://github.com/gassiss/stencil-jest/blob/master/hello-world/tests/unit/example.spec.js#L10) works as expected.

**Comment by chiyema** [comment]
> t CustomElements

Why do you need to call defineCustomElements within stencil?

**Comment by gassiss** [comment]
> > t CustomElements
> 
> Why do you need to call defineCustomElements within stencil?

Not within stencil:

Project A is a stencil based design system. 
Project B is the web app consuming project A.

I'm calling `defineCustomElements` on project B as indicated in the docs. It works on the browser, but not in the test environment.

Makes sense?

**Comment by chiyema** [comment]
> > > t CustomElements
> > 
> > 
> > Why do you need to call defineCustomElements within stencil?
> 
> Not within stencil:
> 
> Project A is a stencil based design system.
> Project B is the web app consuming project A.
> 
> I'm calling `defineCustomElements` on project B as indicated in the docs. It works on the browser, but not in the test environment.
> 
> Makes sense?

Yeah, makes sense to me now. Did you encounter any issue while calling `defineCustomElements` from your vue app? I am integrating the web components with react app and got a `style.replace is not a funciton` issue.

**Comment by gassiss** [comment]
> > > > t CustomElements
> > > 
> > > 
> > > Why do you need to call defineCustomElements within stencil?
> > 
> > 
> > Not within stencil:
> > Project A is a stencil based design system.
> > Project B is the web app consuming project A.
> > I'm calling `defineCustomElements` on project B as indicated in the docs. It works on the browser, but not in the test environment.
> > Makes sense?
> 
> Yeah, makes sense to me now. Did you encounter any issue while calling `defineCustomElements` from your vue app? I am integrating the web components with react app and got a `style.replace is not a funciton` issue.

No, making it run on the browser was a breeze!

**Comment by adrianiskandar** [comment]
Hello, is there an update on this issue?
I'm facing this issue as well.
Project A: is a stencil based project for web components
Project B: is and Angular 10 app using project A 

In the browser everything works fine when you import the angular module  generated by Stencil. That module has the method call `loader.defineCustomElements(window);`  but while running the Jest tests, even if you import the module it shows:

```
(node:49844) UnhandledPromiseRejectionWarning: TypeError: style.replace is not a function
(node:49844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

I tried calling the method directly in the test inside a beforeEach statement and is still show the same error style.replace is not a function but additionally is showing this other error:

```
    console.error
      Error: Could not parse CSS stylesheet
          at exports.createStylesheet (/angular-project/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:34:21)
          at HTMLStyleElementImpl._updateAStyleBlock (/angular-project/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:68:5)
          at HTMLStyleElementImpl._attach (/angular-project/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:19:12)
          at HTMLHeadElementImpl._insert (/angular-project/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:845:14)
          at HTMLHeadElementImpl._preInsert (/angular-project/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:768:10)
          at HTMLHeadElementImpl.insertBefore (/angular-project/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:605:17)
          at HTMLHeadElement.insertBefore (/angular-project/node_modules/jsdom/lib/jsdom/living/generated/Node.js:370:60)
          at Object.bootstrapLazy (/angular-project/node_modules/stencil-web-components/dist/cjs/index-976349b1.js:1614:14)
          at /angular-project/node_modules/stencil-web-components/dist/cjs/loader.cjs.js:19:16
          at ZoneDelegate.invoke (/angular-project/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:402:30) {visibility:hidden}.hydrated{visibility:inherit}

      at VirtualConsole.<anonymous> (../../node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at exports.createStylesheet (../../node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:38:63)
      at HTMLStyleElementImpl._updateAStyleBlock (../../node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:68:5)
      at HTMLStyleElementImpl._attach (../../node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:19:12)
      at HTMLHeadElementImpl._insert (../../node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:845:14)
      at HTMLHeadElementImpl._preInsert (../../node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:768:10)
      at HTMLHeadElementImpl.insertBefore (../../node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:605:17)
```

@gassiss I tried using  [jsdom-environment-sixteen](https://www.npmjs.com/package/jest-environment-jsdom-sixteen) but that didn't fixed the issue.

**Comment by qfan** [comment]
In ```jest``` test environment, ```defineCustomElements``` seems to crash in this ```registerStyle``` function, and I added a *throw* to see what's in that *style*:

```
const registerStyle = (scopeId, cssText, allowCS) => {
    let style = styles.get(scopeId);
    if (supportsConstructibleStylesheets && allowCS) {
        style = (style || new CSSStyleSheet());
        if (typeof style.replace !== 'function') throw style;  //--------------------- I added this line to see what is going on
        style.replace(cssText);  // ---------------------------------  original crash TypeError: style.replace is not a function
    }
    else {
        style = cssText;
    }
    styles.set(scopeId, style);
};
```

And the *throw* gave me this:

```
    thrown: CSSStyleSheet {
      "cssRules": Array [],
      "parentStyleSheet": null,
    }
```

Again, the above was in the ```jest``` test environment.

When I try ``` var x = new CSSStyleSheet() ``` in **Browser**, ```x.replace``` is indeed a function.

So my random guess is, **either** feature detection ``` (supportsConstructibleStylesheets && allowCS)``` SHOULD skip this ```style.replace``` call, **or**, something mocking ```CSSStyleSheet``` object in jest isn't implementing all features properly.

**Comment by WaldemarEnns** [comment]
This still seems to be an issue. I can't run `defineCustomElements` as well - it says:

```
 The Header component › mounted THEN renders component correctly

    TypeError: Cannot read property 'get' of undefined

      13 |   beforeAll(async () => {
      14 |     await applyPolyfills()
    > 15 |     await defineCustomElements()
         |     ^
      16 |   })
      17 |
      18 |   beforeEach(async () => 
```

referring to this line:

```
cmpMeta.$lazyBundleId$ = lazyBundle[0];
        if (!exclude.includes(tagName) && !customElements.get(tagName)) {
            cmpTags.push(tagName);
            customElements.define(tagName, proxyComponent(HostElement, cmpMeta, 1 /* isElementConstructor */));
        }
```

or to be more specific:


```
!customElements.get(tagName)
```

**Comment by rami8k** [comment]
I'm facing the same issue, did anybody manage to solve this?
Much appreciated.

**Comment by Ckearns1210** [comment]
having the same issue, has this been investigated?

**Comment by christian-bromann** [comment]
Hi you all 👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we are now supporting more frameworks to test Stencil components, e.g. [WebdriverIO](https://stenciljs.com/docs/testing/webdriverio/overview) or [Playwright](https://stenciljs.com/docs/testing/playwright/overview). We do not recommend to use the Jest test runner as it uses JSDOM which we don't know if it is compatible with Stencil.

Please let me know if you have any questions!

Thank you for your understanding and support of StencilJS!
