### ISSUE TITLE
Terser error

### ISSUE THREAD

**Issue by olivier65** [ionic-team/stencil#2695]
**Stencil version:**
```
 @stencil/core@2.0.3
```

**I'm submitting a:**
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
You will sometimes get this error at the minification stage:
```
[41:49.5]  copy started ...
[41:49.5]  generate lazy started ...
[41:50.5]  copy finished (114 files) in 1.07 s
Error: did not find a shallow_cmp function for AST_Chain
    at AST_Chain.AST_Node.shallow_cmp (C:\Javascript\stencil\compiler\stencil.js:8017:147224)
    at shallow_cmp (C:\Javascript\stencil\compiler\stencil.js:8017:146531)
    at equivalent_to (C:\Javascript\stencil\compiler\stencil.js:8017:146572)
    at AST_Chain.equivalent_to (C:\Javascript\stencil\compiler\stencil.js:8017:179369)
    at C:\Javascript\stencil\compiler\stencil.js:8017:270022
    at AST_Binary.optimize (C:\Javascript\stencil\compiler\stencil.js:8017:174713)
    at Compressor.before (C:\Javascript\stencil\compiler\stencil.js:8017:174459)
    at AST_Binary.transform (C:\Javascript\stencil\compiler\stencil.js:8017:93167)
    at C:\Javascript\stencil\compiler\stencil.js:8017:97330
    at Compressor.before (C:\Javascript\stencil\compiler\stencil.js:8017:174431)
```

**Expected behavior:**
No error!

**Steps to reproduce:**
Not readily reproducible.

**Other information:**
The terser maintainer has acknowledged the bug in [issue #816](https://github.com/terser/terser/issues/816) and fixed it in release 5.3.4. I created a private build of stencil after upgrading terser and the error above went away. Please upgrade terser to 5.3.4 and re-release stencil ASAP!

**Comment by tricki** [comment]
Is this still an issue since fb4803a7041a8f1ff0756fbd85adcb6a7f6ed852?

**Comment by olivier65** [comment]
No, it looks OK now.
