### ISSUE TITLE
Testing: newSpecPage().template() is not parsed as JSX

### ISSUE THREAD

**Issue by rmirro** [ionic-team/stencil#2850]
**Stencil version:**

```
 @stencil/core@2.4.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Specifying `template` in the Stencil supplied test `app-profile.spec.ts`:
```tsx
const { rootInstance } = await newSpecPage({
  components: [AppProfile],
  // html: '<app-profile></app-profile>',
  template: () => (
    <app-profile></app-profile>
  )
});
```
Results in that test failing:
```
$ npm run test.spec

> newspecpage-template@0.0.1 test.spec /Users/robertmirro/dev/stencil/template-test
> stencil test --spec

[58:16.5]  @stencil/core
[58:16.7]  v2.4.0 📷
[58:16.8]  testing spec files
[58:16.8]  jest args: --spec --max-workers=8
 FAIL  src/components/app-profile/app-profile.spec.ts
  ● Test suite failed to run

    '>' expected.

    Type expected.

    Unterminated regular expression literal.

      at Object.process (node_modules/@stencil/core/testing/index.js:1221:11)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:464:35)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:569:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:607:25)

Test Suites: 1 failed, 1 of 4 total
Tests:       0 total
Snapshots:   0 total
Time:        1.205 s
```

**Expected behavior:**

`template` appears to have been working without issue at some point: https://github.com/ionic-team/stencil/issues/1923

**Steps to reproduce:**

1. install stencil as an **app** in a folder named *test-template*: `npm init stencil`
2. install dependencies: `cd test-template && npm i`
3. ensure latest stencil core is available: `npm i @stencil/core@latest --save-exact`
4. install test dependencies: `npm i --save-dev @types/jest@26.0.20 jest@26.6.3 jest-cli@26.6.3`
5. update *package.json/scripts* to allow running spec tests only: `"test.spec": "stencil test --spec",`
6. run spec-only tests: `npm run test.spec`

**Other information:**

*package.json*
```tsx
{
  "name": "test-template",
  "private": true,
  "version": "0.0.1",
  "description": "Stencil App Starter",
  "scripts": {
    "build": "stencil build",
    "start": "stencil build --dev --watch --serve",
    "test": "stencil test --spec --e2e",
    "test.spec": "stencil test --spec",
    "test.watch": "stencil test --spec --e2e --watchAll",
    "generate": "stencil generate"
  },
  "devDependencies": {
    "@stencil/core": "2.4.0",
    "@stencil/router": "^1.0.1",
    "@types/jest": "^26.0.20",
    "jest": "^26.6.3",
    "jest-cli": "^26.6.3"
  },
  "license": "MIT"
}

```

**Comment by rmirro** [comment]
Apparently renaming the `spec` file to use a `.tsx` extension and adding the following `import` allows `template` to function again.
```tsx
import { h } from '@stencil/core';
```
Using the original `.ts` extension allowed me to regain hoisting via `ts-jest`: https://github.com/ionic-team/stencil/issues/2778#issuecomment-794518515
