### ISSUE TITLE
Testing Error: expect not defined

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#288]
**Stencil version:**

```
 @stencil/core@0.0.7
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Running the unit tests results in the following output:

```
 FAIL  src/components/my-name/my-name.spec.ts
  ● Test suite failed to run

    ReferenceError: expect is not defined
      
      at Object.<anonymous> (node_modules/@stencil/core/testing/index.js:4669:1)
      at Module._compile (module.js:635:30)
      at Object.Module._extensions..js (module.js:646:10)
      at Module.load (module.js:554:32)
      at tryModuleLoad (module.js:497:12)
      at Function.Module._load (module.js:489:3)
      at Module.require (module.js:579:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (node_modules/@stencil/core/testing/jest.preprocessor.js:3:15)
      at Module._compile (module.js:635:30)
```

**Expected behavior:**
worky worky (or fail with actual test failure, not a failure to find `expect` method)

**Steps to reproduce:**

1. `git@github.com:ionic-team/stencil-app-starter.git`
1. `cd stencil-app-starter`
1. `npm i`
1. `npm ls @stencil/core`  - just to verify got version 0.0.7
1. `npm test`
1. observe sadness

Rolling back through the versions, something apparently changed in `0.0.7-1` to cause this as the last working version is `0.0.7-0`

**Comment by manucorporat** [comment]
Already fixed it!
