### ISSUE TITLE
Error when running todo-ap test

### ISSUE THREAD

**Issue by rafaelgfirmino** [ionic-team/stencil#2902]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When I running projects in path test/todo-app
This error happen
```shell
 > start
> node ../../bin/stencil build --dev --watch --serve

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../cli/index.cjs'
Require stack:
- /home/rafa/stencil/bin/stencil
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/rafa/stencil/bin/stencil:35:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/rafa/stencil/bin/stencil'
  ]
}
npm ERR! code 1
npm ERR! path /home/rafa/stencil/test/todo-app
npm ERR! command failed
npm ERR! command sh -c node ../../bin/stencil build --dev --watch --serve

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rafa/.npm/_logs/2021-05-05T22_42_51_599Z-debug.log
```
**Expected behavior:**
Running tests  example
**Steps to reproduce:**
yarn install
yarn start
-->

**Comment by rwaskiewicz** [comment]
This looks to be a result of not having the Stencil compiler built prior to running these tests. I'm able to successfully run the app as of v2.8.0 of Stencil with the following steps

From the root level of the repo:
1. `npm ci && npm run build`
2. `cd test/todo-app`
3. `npm i && npm start`

I'm going to close this, but please feel free to open a new issue if you're seeing this still on the latest version of Stencil
