### ISSUE TITLE
bug: Error: write EPIPE while strating the dev server

### ISSUE THREAD

**Issue by marco9446** [ionic-team/stencil#3514]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

@stencil/core@2.17.3

### Current Behavior

Whenever I start the Dev server with command `stencil build --dev --watch --serve`  the process fails almost immediatly with this error: 

```
> test-component@0.0.1 start
> stencil build --dev --watch --serve

[46:52.0]  @stencil/core
[46:52.2]  v2.17.3
[46:54.7]  build, test-component, dev mode, started ...
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (node:internal/child_process:866:20)
    at ChildProcess.target.send (node:internal/child_process:739:19)
    at receiveFromMain (C:\Users\Marco.Ravazzini\stencil-issue\node_modules\@stencil\core\dev-server\index.js:48:27)
    at Object.emit [as callback] (C:\Users\Marco.Ravazzini\stencil-issue\node_modules\@stencil\core\dev-server\index.js:142:17)
    at Object.emit (C:\Users\Marco.Ravazzini\stencil-issue\node_modules\@stencil\core\compiler\stencil.js:2031:14)
    at BuildContext.start (C:\Users\Marco.Ravazzini\stencil-issue\node_modules\@stencil\core\compiler\stencil.js:13787:29)
    at onBuild (C:\Users\Marco.Ravazzini\stencil-issue\node_modules\@stencil\core\compiler\stencil.js:64504:14)
    at Object.tsWatchHost.afterProgramCreate (C:\Users\Marco.Ravazzini\stencil-issue\node_modules\@stencil\core\compiler\stencil.js:64352:11)
    at Z (C:\Users\Marco.Ravazzini\stencil-issue\node_modules\@stencil\core\compiler\stencil.js:8913:2292225)
    at Object.e.createWatchProgram (C:\Users\Marco.Ravazzini\stencil-issue\node_modules\@stencil\core\compiler\stencil.js:8913:2290238)
Emitted 'error' event on ChildProcess instance at:
    at node:internal/child_process:870:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -4047,
  code: 'EPIPE',
  syscall: 'write'
}
```

If I omit the `--serve` flag, it works without any problems. 

### Expected Behavior

the dev server should start as expected with watch mode enabled

### Steps to Reproduce

The steps would be like the ones explained in the [getting started guide](https://stenciljs.com/docs/getting-started) 

1)  npm init stencil
2) chose components 
3) npm install 
4) npm start 

In my case it fails as soon as i run `npm start`

### Code Reproduction URL

https://github.com/marco9446/stencil-issue

### Additional Information

node version:  v16.16.0
npm version:  8.11.0

OS: Windows 10 build: 19044.1826

**Comment by rwaskiewicz** [comment]
Hey @marco9446 👋 

I'm unable to replicate this using the specified version of Node and npm on Windows.  It's possible that you don't have permissions to run the dev server on your local filesystem (e.g. missing write permissions in that directory), but it's hard to say for sure.  LMK if there's another way we can reproduce this on additional machines and we can go from there.

**Comment by willholmeswastaken** [comment]
I had this issue too, but it resolved itself when I changed my deps to these versions:
```
    "@stencil/core": "^2.10.0",
    "@stencil/eslint-plugin": "^0.4.0",
    "@stencil/postcss": "^2.1.0",
    "@stencil/sass": "^1.5.2",
```

**Comment by rwaskiewicz** [comment]
I'm going to close this issue due to lack of being able to reproduce this issue. If this is still an issue, please feel free to create a new issue with a minimal reproduction URL for the team to pull down and take a look at. Thanks!

**Comment by dutscher** [comment]
this happens randomly on our jenkins with testing:

$ stencil test --spec --e2e --coverage --silent
->

[58:27.1] @stencil/core
[58:27.7] v4.22.3 🐤
[58:28.6] testing e2e and spec files
[58:31.0] build, lib, dev mode, started ...

stdErr node:events:497
throw er; // Unhandled 'error' event
^

Error: write EPIPE
at target._send (node:internal/child_process:877:20)
at target.send (node:internal/child_process:751:19)
at receiveFromMain (/var/lib/jenkins/workspace/node_modules/@stencil/core/dev-server/index.js:56:21)
at close (/var/lib/jenkins/workspace/node_modules/@stencil/core/dev-server/index.js:126:7)
at serverError (/var/lib/jenkins/workspace/node_modules/@stencil/core/dev-server/index.js:183:13)
at receiveFromWorker (/var/lib/jenkins/workspace/node_modules/@stencil/core/dev-server/index.js:223:9)
at Socket.<anonymous> (/var/lib/jenkins/workspace/node_modules/@stencil/core/dev-server/index.js:72:5)
at Socket.emit (node:events:519:28)
at addChunk (node:internal/streams/readable:561:12)
at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
Emitted 'error' event on ChildProcess instance at:
at node:internal/child_process:881:39
at process.processTicksAndRejections (node:internal/process/task_queues:85:11) {
errno: -32,
code: 'EPIPE',
syscall: 'write'
}

Node.js v22.19.0
