### ISSUE TITLE
bug: tsconfig path does not work with spec tests

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/stencil#3826]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

v2.19.3

### Current Behavior

Running a spec test on a component that imports something from a path define in tsconfig results in a "Cannot find module" error:

`Cannot find module '@utils/utils' from 'src/components/my-component/my-component.tsx'`

### Expected Behavior

I expect the tsconfig path to be respected when running spec tests.

### Steps to Reproduce

1. Clone repo.
2. Run `npm install`.
3. Run `npm run test`.
4. Observe that the following error is logged:

```
 FAIL  src/components/my-component/my-component.spec.ts
  ● Test suite failed to run

    Cannot find module '@utils/utils' from 'src/components/my-component/my-component.tsx'

    Require stack:
      src/components/my-component/my-component.tsx
      src/components/my-component/my-component.spec.ts

      1 | import { Component, Prop, h } from '@stencil/core';
    > 2 | import { format } from '@utils/utils';
        | ^
      3 |
      4 | @Component({
      5 |   tag: 'my-component',

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/components/my-component/my-component.tsx:2:1)
```

### Code Reproduction URL

https://github.com/liamdebeasi/blank-stencil-repro/tree/tsconfig-test

**Comment by alicewriteswrongs** [comment]
Stencil v3.1 was [just released](https://github.com/ionic-team/stencil/releases/tag/v3.1.0) and includes a fix for this issue! I just confirmed that I was able to fix the issue in the supplied reproduction case by doing the following:

- installed `@stencil/core@latest` (`3.1.0`)
- cleared the jest cache (`npx jest --clearCache`)
- ran `npm test`

and it works! Accordingly I'm going to close this issue.
