### ISSUE TITLE
Alias imports cause a compile error

### ISSUE THREAD

**Issue by yomatters** [ionic-team/stencil#403]
**Stencil version:**
```
@stencil/core@0.1.1-0
```

**I'm submitting a:**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
```
[ ERROR ]  Error parsing: /Users/yomatters/stencil-app-starter/dist/collection/components/app-home/app-home.js, line: 1, column: 9
```

**Expected behavior:**
Component should compile.

**Steps to reproduce:**
1. Clone the Stencil app starter.
2. Add the lines below to any of the components.
3. Attempt to build the project.

**Related code:**

```tsx
import { Method as MethodNew } from '@stencil/core';
console.log(MethodNew);
```

**Other information:**
The same error occurs when importing from other (non-Stencil) packages. This makes it difficult to use two imports that have the same name. E.g.:

```tsx
import { WMTS as WMTSSource } from 'ol/source/wmts';
import { WMTS as WMTSTileGrid } from 'ol/tilegrid/wmts';
```

**Comment by jgw96** [comment]
Hey, thanks for opening an issue with us! I followed your steps exactly and unfortunately cannot reproduce this issue with either a dev or prod build. Just to be clear this happens with a completely vanilla stencil-app-starter correct?

**Comment by yomatters** [comment]
I get the error in both a freshly-cloned starter app (with the two lines added) and in my own project. Since you're not seeing the error, I'm wondering if it's related to something in my development environment. I'm going to try building inside a Docker container to see if that makes a difference. I'll report back with the results.

**Comment by yomatters** [comment]
I'm able to reproduce the error in a Docker container as well. Here's my Dockerfile:

```Dockerfile
FROM node:9.4.0
WORKDIR /usr/src/app
RUN git clone https://github.com/ionic-team/stencil-app-starter.git .
RUN npm install
RUN sed -i "2s;^;import { Method as MethodNew } from \'@stencil/core\'\;\nconsole.log(MethodNew)\;\n;" \
  /usr/src/app/src/components/app-home/app-home.tsx
CMD [ "npm", "run", "build" ]
```
I build the image with:
```sh
docker build -t stencil-debug .
```

And inspect the edited file using `docker run --rm stencil-debug cat /usr/src/app/src/components/app-home/app-home.tsx`:
```tsx
import { Component } from '@stencil/core';
import { Method as MethodNew } from '@stencil/core';
console.log(MethodNew);


@Component({
  tag: 'app-home',
  styleUrl: 'app-home.scss'
})
export class AppHome {

  render() {
    return (
      <div>
        <p>
          Welcome to the Stencil App Starter.
          You can use this starter to build entire apps all with
          web components using Stencil!
          Check out our docs on <a href='https://stenciljs.com'>stenciljs.com</a> to get started.
        </p>

        <stencil-route-link url='/profile/stencil'>
          <button>
            Profile page
          </button>
        </stencil-route-link>
      </div>
    );
  }
}
```

I then build the project using `docker run --rm stencil-debug`, which produces this output:
```sh
> @stencil/starter@0.0.1 build /usr/src/app
> stencil build --prerender

[27:48.7]  @stencil/core v0.1.1-0 
[27:48.7]  build, app, prod mode, started ... 
[27:48.7]  compile started ... 
[27:51.2]  compile finished in 2.47 s 
[27:51.2]  bundle styles started ... 
[27:51.2]  bundle modules started ... 
[27:51.3]  bundle styles finished in 160 ms 
[27:51.7]  bundle modules finished in 482 ms 
[27:51.7]  generate es2015 bundles started ... 
[27:51.8]  generate es2015 bundles finished in 107 ms 
[27:51.8]  generate es5 bundles started ... 
[27:51.8]  generate es5 bundles finished in 55 ms 
[27:51.8]  generate service worker started ... 
[27:51.9]  generate service worker finished in 78 ms 

[ ERROR ]  Error parsing: /usr/src/app/dist/collection/components/app-home/app-home.js, line: 1, column: 9 

[27:51.9]  build failed in 3.22 s 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @stencil/starter@0.0.1 build: `stencil build --prerender`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @stencil/starter@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-11T14_27_52_005Z-debug.log
```

**Comment by jgw96** [comment]
Hey! Good news, I am now able to reproduce this issue. Not sure why I wasn't able to repro yesterday (maybe I just needed some sleep haha) but yeah, I can repro now. We will look into this.

**Comment by adamdbradley** [comment]
@jgw96 would you be able to test this again with the latest? Stencil should be reading the user's tsconfig now too

**Comment by juanmiguelbesada** [comment]
I still can reproduce this error in latest stencil version (0.7.24)
```
JuanMi@DESKTOP-RSD0KTU MINGW64 ~/Projects/my-app (master)
$ npm run build

> @stencil/starter@0.0.1 build C:\Users\JuanMi\Projects\my-app
> stencil build --prerender

[02:28.4]  @stencil/core v0.7.24
[02:28.4]  build, app, prod mode, started ...
[02:28.4]  compile started ...
[02:34.0]  compile finished in 5.57 s
[02:34.0]  module map started ...
[02:35.7]  module map finished in 1.69 s
[02:36.3]  generate bundles started ...
[02:38.6]  generate bundles finished in 2.30 s
[02:38.6]  generate app files started ...
[02:43.9]  generate app files finished in 5.30 s
[02:44.0]  prerendering started ...
[02:44.0]  prerender, started: / ...
[02:45.9]  generate service worker started ...
[02:46.7]  prerender, finished: / in 2.72 s
[02:46.7]  prerendered urls: 1 in 2.72 s
[02:46.7]  generate service worker finished in 825 ms

[ ERROR ]  Runtime error detected while loading bundle
           MethodNew is not defined ReferenceError: MethodNew is not defined at evalmachine.<anonymous>:2:98 at
           execBundleCallback
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:12503:13) at
           Object.loadBundle
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:12541:9) at
           evalmachine.<anonymous>:2:5 at Script.runInContext (vm.js:74:29) at Object.runInContext (vm.js:182:6) at
           Object.runInContext
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\sys\node\index.js:587:8) at loadFile
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:12579:23) at
           Object.requestBundle
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:12572:17) at
           Object.domApi.$createElement
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:12365:17)

[ ERROR ]  Runtime error detected while loading bundle
           MethodNew is not defined ReferenceError: MethodNew is not defined at evalmachine.<anonymous>:2:98 at
           execBundleCallback
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:12503:13) at
           Object.loadBundle
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:12541:9) at
           evalmachine.<anonymous>:2:5 at Script.runInContext (vm.js:74:29) at Object.runInContext (vm.js:182:6) at
           Object.runInContext
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\sys\node\index.js:587:8) at loadFile
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:12579:23) at
           Object.requestBundle
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:12572:17) at
           connectHostElement
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:11954:13)

[ ERROR ]  Runtime error detected while loading bundle
           MethodNew is not defined ReferenceError: MethodNew is not defined at evalmachine.<anonymous>:2:98 at
           execBundleCallback
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:12503:13) at
           Object.loadBundle
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:12541:9) at
           evalmachine.<anonymous>:2:5 at Script.runInContext (vm.js:74:29) at Object.runInContext (vm.js:182:6) at
           Object.runInContext
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\sys\node\index.js:587:8) at loadFile
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:12579:23) at
           Object.requestBundle
           (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:12572:17) at
           plt.queue.tick (C:\Users\JuanMi\Projects\my-app\node_modules\@stencil\core\dist\compiler\index.js:10487:13)

[02:46.7]  build finished in 18.35 s
```
