### ISSUE TITLE
bug: Error Exporting 3rd party JS Lib ion-js

### ISSUE THREAD

**Issue by rahulrsingh09** [ionic-team/stencil#4085]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

3.0.0

### Current Behavior

I am trying to ion-js in Stencil Component. I can get the same code to work in a React workspace but due to module it dosent seem to work in Stencil 

```
componentWillLoad() {
    let ionData = `{ ccp_datatype_name:ResponsiblePerson, ccp_datatype_version:"1.0", definition:type::{ name: PriceSchema, major_version:1, minor_version:0, base:VariantBase, fields:[ { name:category, type:symbol, nullable:false, min_occurs:1, max_occurs:1 }, { name:address_identifier, type:string, nullable:false, min_occurs:1, max_occurs:1 } ] }, status:active, table_name:ccp_datatypes}`;
    let value = ion.load(ionData);
    console.log(value.fields())
  }

```

This same code works in run kit / React but not in stencil 

```
require("jsbi/package.json"); // jsbi is a peer dependency. 
var ionJs = require("ion-js")
let ionData = `{ ccp_datatype_name:ResponsiblePerson, ccp_datatype_version:"1.0", definition:type::{ name: PriceSchema, major_version:1, minor_version:0, base:VariantBase, fields:[ { name:category, type:symbol, nullable:false, min_occurs:1, max_occurs:1 }, { name:address_identifier, type:string, nullable:false, min_occurs:1, max_occurs:1 } ] }, status:active, table_name:ccp_datatypes}`;


let value = ionJs.load(ionData);


console.log(value.fields());
```

### Expected Behavior

It should be able to parse and use the lib 

### System Info

```shell
Brave / Mac
```

### Steps to Reproduce

Just Put this code in any Stencil Starter Repo under ComponentDidLoad and you should see error in console. 

```
TypeError: Cannot read properties of undefined (reading 'IonTypes')
    at Blob.js:6:36
    at createCommonjsModule (utils.ts:3:1)
    at Lob.js:58:1 undefined   
 ```

### Code Reproduction URL

NA

**Comment by rwaskiewicz** [comment]
Hey @rahulrsingh09 👋 

Thanks for the bug report and repro case! I can confirm that this is an issue, where it appears that there appears to be a use-before-definition issue occurring here:
![Screenshot 2023-02-22 at 10 28 23 AM](https://user-images.githubusercontent.com/1930213/220670183-337dbdd8-a81d-41ef-a4a7-a5def02290c8.png)

I'm going to label this to get it added to our backlog. Thanks again!

**Comment by rahulrsingh09** [comment]
Hi @rwaskiewicz is there any workaround for now or we are stuck..

**Comment by alicewriteswrongs** [comment]
@rahulrsingh09  It looks like the ion-js maintainers have [some suggestions](https://github.com/amazon-ion/ion-js#web-browser) for usage in the browser - perhaps you could achieve your end goal by incorporating the suggested approach there? Basically they suggest using a `<script>` tag to import a browser-compatible script they build and distribute.

**Comment by rahulrsingh09** [comment]
Yes i was checking it, dosent seem to be an ideal approach when we eventually want to ship this as another resource. I wish we had a solution to bypass this without having to download at runtime
