### ISSUE TITLE
bug: Unexpected token: punc (()

### ISSUE THREAD

**Issue by valadas** [ionic-team/stencil#4218]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

3.2.0

### Current Behavior

build fails with the following error:

```
[28:15.1]  @stencil/core
[28:15.5]  v3.2.0
[28:17.8]  build, dnn, prod mode, started ...
[28:18.0]  transpile started ...
[28:22.7]  transpile finished in 4.65 s
[28:22.7]  copy started ...
[28:23.3]  generate lazy + source maps started ...
[28:23.5]  copy finished (3 files) in 895 ms
SyntaxError: Unexpected token: punc (()
    at js_error (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:21312)
    at u (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:30713)
    at l (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:30811)
    at c (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:30865)
    at h (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:31407)
    at D (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:36051)
    at e (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:32865)
    at D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:31515
    at I (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:41701)
    at e (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:32960)

SyntaxError: Unexpected token: punc (()
    at js_error (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:21312)
    at u (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:30713)
    at l (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:30811)
    at c (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:30865)
    at h (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:31407)
    at D (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:36051)
    at e (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:32865)
    at D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:31515
    at I (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:41701)
    at e (D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js:9950:32960)

[30:50.0]  generate lazy + source maps finished in 146.67 s

[ ERROR ]  Minify JS
           Unexpected token: punc (()

 L149502:  if (workerMsg === workerMsgId) {
 L149503:  const err = data[3]; 
 L149504:  const [resolve, reject, callbackIds] = pending.get(id);

[ WARN  ]  Bundling Warning SOURCEMAP_BROKEN
           Sourcemap is likely to be incorrect: a plugin (workerPlugin) was used to transform files, but didn't
           generate a sourcemap for the transformation. Consult the plugin documentation for help

[30:50.0]  build failed in 152.16 s
```

### Expected Behavior

Build should succeed as it succeeded with v3.1.0

### System Info

```shell
System: node 16.15.0
    Platform: windows (10.0.22621)
   CPU Model: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 cpus)
    Compiler: D:\dnn-elements\dnn-elements\node_modules\@stencil\core\compiler\stencil.js
       Build: 1678807683
     Stencil: 3.2.0
  TypeScript: 4.9.5
      Rollup: 2.42.3
      Parse5: 7.1.2
      Sizzle: 2.42.3
      Terser: 5.16.6
```

### Steps to Reproduce

I don't have right now excact MINIMAL steps to reproduce but will try to get something to pinpoint it. I _believe_ it has something to do with using workers like this:

```
import { worker as jsonWorker } from 'monaco-editor/esm/vs/language/json/json.worker.js?worker';
import { worker as cssWorker } from 'monaco-editor/esm/vs/language/css/css.worker.js?worker';
import { worker as htmlWorker } from 'monaco-editor/esm/vs/language/html/html.worker.js?worker';
import { worker as tsWorker } from 'monaco-editor/esm/vs/language/typescript/ts.worker.js?worker';
import { worker as editorWorker } from 'monaco-editor/esm/vs/editor/editor.worker.js?worker';

connectedCallback() {
    (self as any).MonacoEnvironment = {
      getWorker: function (_moduleId, label) {
          if (label === 'json') {
            return jsonWorker;
          }
          if (label === 'css' || label === 'scss' || label === 'less') {
            return cssWorker;
          }
          if (label === 'html' || label === 'handlebars' || label === 'razor') {
            return htmlWorker;
          }
          if (label === 'typescript' || label === 'javascript') {
            return tsWorker;
          }
          return editorWorker;
      }
    };
```

### Code Reproduction URL

https://github.com/DNNCommunity/dnn-elements/pull/690

### Additional Information

I will try to pinpoint the bare minimal steps to reproduce if this is not enough to go by or to pull stencil locally and try to get more details. It was working fine with v3.1.0, it's only when upgrading to v3.2.0 that this issue started happening.

**Comment by valadas** [comment]
Ok, after investigation, looks like it is caused by terser 5.16.6 and a PR was already merged to bump that to 5.16.8 which solves that problem, so closing this issue and waiting for next release 😄

**Comment by alicewriteswrongs** [comment]
thanks for looking into that and closing! do let us know if you continue to experience the issue.

**Comment by rwaskiewicz** [comment]
Yes, thank you! If you'd like to verify that the terser upgrade works, feel free to give the latest Stencil nightly build a try:
```
npm i @stencil/core@nightly
```
