### ISSUE TITLE
Path issues in tests with windows

### ISSUE THREAD

**Issue by jgw96** [ionic-team/stencil#428]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

In our tests we do alot of testing of paths. In the majority of these cases we assume unix style paths. To make sure these tests also work in Windows I need to go through and normalize all those paths.

**Expected behavior:**

Tests would pass on Windows

**Steps to reproduce:**

- `npm run test` on a windows machine

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by mattdsteele** [comment]
Here's the type of error I see on Windows:

```
  ● bundle-module › build › should build 2 bundles of 3 components

   expect(received).toEqual(expected)

   Expected value to equal:
     []
   Received:
     [{"absFilePath": null, "code": "UNRESOLVED_IMPORT", "header": "build error", "language": "javascript", "level": "error", "lines": [], "messageText": "Could not resolve './../../../../../../dist/collection/cmp-c.js' from entry:cmp-c", "relFilePath": null, "type": "build"}, {"absFilePath": null, "header": "build error", "level": "error", "lines": [], "messageText": "rollup died

     54 |   return rollupBundle;
     55 | }
   > 56 |
     57 |
     58 | export async function writeEsModules(config: Config, rollupBundle: OutputChunk) {
     59 |   const results = await rollupBundle.generate({

     at Object.<anonymous> (src/compiler/bundle/rollup-bundle.ts:56:19)
     at throw (native)
     at rejected (src/compiler/bundle/rollup-bundle.ts:5:65)", "relFilePath": null, "type": "build"}]

     Difference:

     - Expected
     + Received

     - Array []
     + Array [
     +   Object {
     +     "absFilePath": null,
     +     "code": "UNRESOLVED_IMPORT",
     +     "header": "build error",
     +     "language": "javascript",
     +     "level": "error",
     +     "lines": Array [],
     +     "messageText": "Could not resolve './../../../../../../dist/collection/cmp-c.js' from entry:cmp-c",
     +     "relFilePath": null,
     +     "type": "build",
     +   },
     +   Object {
     +     "absFilePath": null,
     +     "header": "build error",
     +     "level": "error",
     +     "lines": Array [],
     +     "messageText": "rollup died
     +     at Object.<anonymous> (C:\\Users\\IGEN261\\code\\github\\stencil\\stencil\\src\\compiler\\bundle\\rollup-bundle.ts:56:19)
     +     at throw (native)
     +     at rejected (C:\\Users\\IGEN261\\code\\github\\stencil\\stencil\\src\\compiler\\bundle\\rollup-bundle.ts:5:65)",
     +     "relFilePath": null,
     +     "type": "build",
     +   },
     + ]
     at Object.<anonymous> (src/compiler/bundle/test/bundle-modules.spec.ts:61:35)
     at fulfilled (src/compiler/bundle/test/bundle-modules.spec.ts:4:58)


Test Suites: 8 failed, 73 passed, 81 total
Tests:       33 failed, 913 passed, 946 total
Snapshots:   0 total
Time:        29.977s, estimated 35s
Ran all test suites.
```

**Comment by ospatil** [comment]
I'm getting the same error mentioned in https://github.com/ionic-team/stencil/issues/520#issue-296165100 **on a Mac**. I think it's not Windows-specific and could be different error than the one mentioned on this issue.

**Comment by JStumpp** [comment]
We have the same issues as described in https://github.com/ionic-team/stencil/issues/520. It is a critical feature to test the components ;-)
Could you point me to where you assume unix style paths in the tests that need normalization? Than I could have a look. Thanks!

**Comment by tja4472** [comment]
https://github.com/ionic-team/stencil/blob/master/src/compiler/bundle/rollup-plugins/in-memory-fs-read.ts

Unwanted 'c:' in importee.

```typescript
    async resolveId(importee: string, importer: string) {
      console.log('#####resolveId:importee>', importee); // ./../../../__tmp__in__memory__/cmp-a.js
      console.log('#####resolveId:importer>', importer); // entry:cmp-a.cmp-b
      if (!sys.path.isAbsolute(importee)) {
        importee = normalizePath(sys.path.resolve(importer ? sys.path.dirname(importer) : sys.path.resolve(), importee));
        console.log('#####A:importee>', importee); // c:/__tmp__in__memory__/cmp-a.js
        if (importee.indexOf('.js') === -1) {
          importee += '.js';
        }
      }

      if (importee.startsWith('c:')) {
        console.log('*****Bodge applied*****');
        importee = importee.substr(2);
      }

      console.log('BBB>', compilerCtx.moduleFiles); //  jsFilePath: '/__tmp__in__memory__/cmp-a.js' },
      // it's possible the importee is a file pointing directly to the source ts file
      // if it is a ts file path, then we're good to go
      var moduleFile = compilerCtx.moduleFiles[importee];
```
hth
Tim
