### ISSUE TITLE
Stencil 0.1.6 doesn't return a valid HTMLElement

### ISSUE THREAD

**Issue by bassettsj** [ionic-team/stencil#433]
**Stencil version:**

```
@stencil/core@0.1.6
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Using this example repo: https://github.com/bassettsj/stencil-1.6-failing-tests
```
 FAIL  src/components/my-component/my-component.spec.ts
  my-component
    ✓ should build (4ms)
    rendering
      ✕ should work without parameters (610ms)
      ✕ should work with a first name (4ms)
      ✕ should work with a last name (2ms)
      ✕ should work with both a first and a last name (2ms)

  ● my-component › rendering › should work without parameters

    TypeError: Cannot read property 'textContent' of null

      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:61:28)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  ● my-component › rendering › should work with a first name

    TypeError: Cannot set property 'first' of null

      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:67:39)
      at step (src/components/my-component/my-component.spec.ts:32:23)
      at Object.next (src/components/my-component/my-component.spec.ts:13:53)
      at src/components/my-component/my-component.spec.ts:7:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter (src/components/my-component/my-component.spec.ts:3:12)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:63:66)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  ● my-component › rendering › should work with a last name

    TypeError: Cannot set property 'last' of null

      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:80:38)
      at step (src/components/my-component/my-component.spec.ts:32:23)
      at Object.next (src/components/my-component/my-component.spec.ts:13:53)
      at src/components/my-component/my-component.spec.ts:7:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter (src/components/my-component/my-component.spec.ts:3:12)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:76:65)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  ● my-component › rendering › should work with both a first and a last name

    TypeError: Cannot set property 'first' of null

      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:93:39)
      at step (src/components/my-component/my-component.spec.ts:32:23)
      at Object.next (src/components/my-component/my-component.spec.ts:13:53)
      at src/components/my-component/my-component.spec.ts:7:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter (src/components/my-component/my-component.spec.ts:3:12)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:89:82)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```
**Expected behavior:**

All the render tests should pass if render returned a valid `HTMLElement` instead of null

**Steps to reproduce:**

I created a repository from the component starter that reproduces the issue.

```bash
git clone git@github.com:bassettsj/stencil-1.6-failing-tests.git
cd stencil-1.6-failing-tests
npm install
npm test
```

**Other information:**
https://stencil-worldwide.slack.com/archives/C789G3X1R/p1516151100000154

**Comment by rolandjitsu** [comment]
Might be related to https://github.com/ionic-team/stencil/issues/381.

**Comment by bassettsj** [comment]
@rolandjitsu Turns out it is not related. I just turned off the shadow dom in the test component and the issue is still happening.

**Comment by jgw96** [comment]
Thanks for the info! Talking to the person who built the testing stuff. Will update here.

**Comment by adamdbradley** [comment]
Should be fixed in 0.2.3, thanks for the report!

https://github.com/ionic-team/stencil/commit/122b1cdfae7dfee873409074cf955030999ae133

**Comment by bassettsj** [comment]
Yep! Seems good now, thanks for adding a test so it won't break later!

**Comment by adamdbradley** [comment]
Awesome thanks for testing!
