### ISSUE TITLE
Tests get errors on registery

### ISSUE THREAD

**Issue by Tallyb** [ionic-team/stencil#441]
**Stencil version:**
0.2.0, 0.2.1

**I'm submitting a:**

- [ X ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
When running simple tests with rendering, the following error comes up: 
```
my-component
    ✓ should build (3ms)
    rendering
      ✕ should work without parameters (22ms)
      ✕ should work with a first name (1ms)
      ✕ should work with a last name
      ✕ should work with both a first and a last name (1ms)

  ● my-component › rendering › should work without parameters

    Error parsing app registry, /www/build/app/app.registry.json: Error: readFile, path doesn't exist: /www/build/app/app.registry.json

      at getAppRegistry (node_modules/@stencil/core/dist/testing/index.js:6312:15)
      at loadComponentRegistry (node_modules/@stencil/core/dist/testing/index.js:12397:25)
      at new Renderer (node_modules/@stencil/core/dist/testing/index.js:12425:28)
      at Object.<anonymous> (node_modules/@stencil/core/dist/testing/index.js:14527:26)
          at Generator.next (<anonymous>)
      at node_modules/@stencil/core/dist/testing/index.js:14519:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter$51 (node_modules/@stencil/core/dist/testing/index.js:14515:12)
      at Object.render$1 [as render] (node_modules/@stencil/core/dist/testing/index.js:14523:12)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:50:60)
      at step (src/components/my-component/my-component.spec.ts:32:23)
      at Object.next (src/components/my-component/my-component.spec.ts:13:53)
      at src/components/my-component/my-component.spec.ts:7:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter (src/components/my-component/my-component.spec.ts:3:12)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:47:41)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● my-component › rendering › should work without parameters

    TypeError: Cannot read property 'textContent' of undefined

      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:61:28)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● my-component › rendering › should work with a first name

    Error parsing app registry, /www/build/app/app.registry.json: Error: readFile, path doesn't exist: /www/build/app/app.registry.json

      at getAppRegistry (node_modules/@stencil/core/dist/testing/index.js:6312:15)
      at loadComponentRegistry (node_modules/@stencil/core/dist/testing/index.js:12397:25)
      at new Renderer (node_modules/@stencil/core/dist/testing/index.js:12425:28)
      at Object.<anonymous> (node_modules/@stencil/core/dist/testing/index.js:14527:26)
          at Generator.next (<anonymous>)
      at node_modules/@stencil/core/dist/testing/index.js:14519:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter$51 (node_modules/@stencil/core/dist/testing/index.js:14515:12)
      at Object.render$1 [as render] (node_modules/@stencil/core/dist/testing/index.js:14523:12)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:50:60)
      at step (src/components/my-component/my-component.spec.ts:32:23)
      at Object.next (src/components/my-component/my-component.spec.ts:13:53)
      at src/components/my-component/my-component.spec.ts:7:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter (src/components/my-component/my-component.spec.ts:3:12)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:47:41)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● my-component › rendering › should work with a first name

    TypeError: Cannot set property 'first' of undefined

      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:67:39)
      at step (src/components/my-component/my-component.spec.ts:32:23)
      at Object.next (src/components/my-component/my-component.spec.ts:13:53)
      at src/components/my-component/my-component.spec.ts:7:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter (src/components/my-component/my-component.spec.ts:3:12)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:63:66)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● my-component › rendering › should work with a last name

    Error parsing app registry, /www/build/app/app.registry.json: Error: readFile, path doesn't exist: /www/build/app/app.registry.json

      at getAppRegistry (node_modules/@stencil/core/dist/testing/index.js:6312:15)
      at loadComponentRegistry (node_modules/@stencil/core/dist/testing/index.js:12397:25)
      at new Renderer (node_modules/@stencil/core/dist/testing/index.js:12425:28)
      at Object.<anonymous> (node_modules/@stencil/core/dist/testing/index.js:14527:26)
          at Generator.next (<anonymous>)
      at node_modules/@stencil/core/dist/testing/index.js:14519:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter$51 (node_modules/@stencil/core/dist/testing/index.js:14515:12)
      at Object.render$1 [as render] (node_modules/@stencil/core/dist/testing/index.js:14523:12)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:50:60)
      at step (src/components/my-component/my-component.spec.ts:32:23)
      at Object.next (src/components/my-component/my-component.spec.ts:13:53)
      at src/components/my-component/my-component.spec.ts:7:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter (src/components/my-component/my-component.spec.ts:3:12)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:47:41)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● my-component › rendering › should work with a last name

    TypeError: Cannot set property 'last' of undefined

      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:80:38)
      at step (src/components/my-component/my-component.spec.ts:32:23)
      at Object.next (src/components/my-component/my-component.spec.ts:13:53)
      at src/components/my-component/my-component.spec.ts:7:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter (src/components/my-component/my-component.spec.ts:3:12)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:76:65)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● my-component › rendering › should work with both a first and a last name

    Error parsing app registry, /www/build/app/app.registry.json: Error: readFile, path doesn't exist: /www/build/app/app.registry.json

      at getAppRegistry (node_modules/@stencil/core/dist/testing/index.js:6312:15)
      at loadComponentRegistry (node_modules/@stencil/core/dist/testing/index.js:12397:25)
      at new Renderer (node_modules/@stencil/core/dist/testing/index.js:12425:28)
      at Object.<anonymous> (node_modules/@stencil/core/dist/testing/index.js:14527:26)
          at Generator.next (<anonymous>)
      at node_modules/@stencil/core/dist/testing/index.js:14519:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter$51 (node_modules/@stencil/core/dist/testing/index.js:14515:12)
      at Object.render$1 [as render] (node_modules/@stencil/core/dist/testing/index.js:14523:12)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:50:60)
      at step (src/components/my-component/my-component.spec.ts:32:23)
      at Object.next (src/components/my-component/my-component.spec.ts:13:53)
      at src/components/my-component/my-component.spec.ts:7:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter (src/components/my-component/my-component.spec.ts:3:12)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:47:41)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● my-component › rendering › should work with both a first and a last name

    TypeError: Cannot set property 'first' of undefined

      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:93:39)
      at step (src/components/my-component/my-component.spec.ts:32:23)
      at Object.next (src/components/my-component/my-component.spec.ts:13:53)
      at src/components/my-component/my-component.spec.ts:7:71
          at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter (src/components/my-component/my-component.spec.ts:3:12)
      at Object.<anonymous> (src/components/my-component/my-component.spec.ts:89:82)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Expected behavior:**

**Steps to reproduce:**
clone stencil-starter-lib repo, update to 0.2.x of @stencil/core and run `npm t`

**Related code:**

```tsx
```

**Other information:**

**Comment by adamdbradley** [comment]
Thanks for submitting the issue, I'm actively fixing this right now and we'll have it up in the next release. Thanks
