### ISSUE TITLE
bug: Stencil can resolve incorrect jest-runner dependency when using pnpm 

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/stencil#5196]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

v4.9.0

### Current Behavior

In a mono-repo using pnpm where you have mixed dependency versions of Jest, specifically the `jest-runner` package, Stencil will incorrectly use an older version of the `jest-runner` package, even though the Stencil project may be configured with a newer version.

For example, in a project that has Jest v29 for the Stencil project, but another package with Jest v26, Stencil will use the test facade for Jest v29, but use the `jest-runner@26` instance when executing the test runner. 

This results in an exception:
```
TypeError: Cannot read properties of undefined (reading 'serial')
```

I've modified the bundle to provide the entire stack trace:
<details>
<pre>
TypeError: Cannot read properties of undefined (reading 'serial')
    at e.runTests (/Users/sean/Documents/ionic/issues/ionic-framework/node_modules/.pnpm/jest-runner@26.6.3/node_modules/jest-runner/build/index.js:108:27)
    at e.runTests (/Users/sean/Documents/ionic/issues/ionic-framework/node_modules/.pnpm/@stencil+core@4.9.0/node_modules/@stencil/core/testing/index.js:926:19)
    at TestScheduler.scheduleTests (/Users/sean/Documents/ionic/issues/ionic-framework/node_modules/.pnpm/@jest+core@29.7.0/node_modules/@jest/core/build/TestScheduler.js:283:32)
    at async runJest (/Users/sean/Documents/ionic/issues/ionic-framework/node_modules/.pnpm/@jest+core@29.7.0/node_modules/@jest/core/build/runJest.js:367:19)
    at async _run10000 (/Users/sean/Documents/ionic/issues/ionic-framework/node_modules/.pnpm/@jest+core@29.7.0/node_modules/@jest/core/build/cli/index.js:343:7)
    at async runCLI (/Users/sean/Documents/ionic/issues/ionic-framework/node_modules/.pnpm/@jest+core@29.7.0/node_modules/@jest/core/build/cli/index.js:198:3)
    at async runJest (/Users/sean/Documents/ionic/issues/ionic-framework/node_modules/.pnpm/@stencil+core@4.9.0/node_modules/@stencil/core/testing/index.js:900:10)
    at async Object.run (/Users/sean/Documents/ionic/issues/ionic-framework/node_modules/.pnpm/@stencil+core@4.9.0/node_modules/@stencil/core/testing/index.js:12865:10)
    at async taskTest (/Users/sean/Documents/ionic/issues/ionic-framework/node_modules/.pnpm/@stencil+core@4.9.0/node_modules/@stencil/core/cli/index.cjs:2395:24)
    at async runTask (/Users/sean/Documents/ionic/issues/ionic-framework/node_modules/.pnpm/@stencil+core@4.9.0/node_modules/@stencil/core/cli/index.cjs:2514:13)
</pre>
</details>

This behavior is likely driven from pnpm hoisting the dependency, changing the execution location from which Stencil uses to grab the `jest-runner` instance and invoke it.  I suspect we will need to make stricter assumption around where this instance lives, such as from the `rootDir` of the project, instead of from the executing `node_modules`. 

### Expected Behavior

Stencil should resolve its own dependency of the `jest-runner`, regardless of if the workspace is using another dependency for another project in the mono-repo. 

### System Info

```shell
`npx stencil info` fails with:
> npm ERR! could not determine executable to run
```

### Steps to Reproduce

1. Clone the repository - it is a mono-repo.
2. Install pnpm, if not already installed: https://pnpm.io/installation
3. Install project dependencies: `pnpm install`
4. Run unit tests for the Stencil project: `cd packages/stencil && pnpm test.spec`
5. Observe: Exception is thrown, tests do not run successfully.
6. Expected: Tests run successfully.

### Code Reproduction URL

https://github.com/sean-perkins/stencil-pnpm-issue

### Additional Information

Workarounds:
1. Downgrade to the lowest version of Jest that is compatible with Stencil, for example with the reproduction downgrading the Stencil project to Jest v26.
2. Upgrade all packages in the mono-repo to the same version of Jest as the Stencil project. 
3. Use npm or a package manager that does not hoist dependencies.

**Comment by dutscher** [comment]
same here with stenciljs 4.18.3 with jest v27
![image](https://github.com/ionic-team/stencil/assets/14682/6437a111-d6a2-4486-964c-8a7a97e9396c)
