### ISSUE TITLE
bug: testing Stencil lib within external project with Jest not working since shadowDomShim was removed

### ISSUE THREAD

**Issue by zerock54** [ionic-team/stencil#5262]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4

### Current Behavior

Hi,

I have an app which uses a Stencil library as a Design System.
This app is tested with Jest and testing-library.
I was using the shadowDomShim extra config to make the shadow DOM available within Jest but, since this field is now gone, the content of my components configured with {shadow: true} is empty

### Expected Behavior

The shadow dom appears as normal within Jest

### Steps to Reproduce

- Clone https://github.com/zerock54/stencil-jest-shadow-dom/tree/main
- Run `npm --prefix ./stencil-jest install && npm --prefix ./bug-stencil-jest install`
- In `stencil-jest`, run `npm run build`
- In `stencil-jest`, run `npm link`
- In `bug-stencil-jest`, run `npm link stencil-jest`
- In `bug-stencil-jest`, run `npm run test`

### Code Reproduction URL

https://github.com/zerock54/stencil-jest-shadow-dom/tree/main

### Additional Information

Everything was fine with Stencil 3 by setting ```__deprecated__shadowDomShim: true``` 

Is there a way to make it work the same way now that this config is gone in Stencil 4 ?

Thanks

**Comment by zerock54** [comment]
Hey @rwaskiewicz, 

Sorry about that

I just sent a fix

**Comment by rwaskiewicz** [comment]
Thanks!

I'm now seeing the following error, which I think matches a little more closely with the issue you reported:

```
npm t

> bug-stencil-jest@0.0.0 test
> ng test

 FAIL  src/app/app.component.spec.ts (10.424 s)
  AppComponent
    ✕ should create (10090 ms)

  ● AppComponent › should create

    Unable to find an element with the text: Hello, World! I'm nicolas. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    Ignored nodes: comments, script, style
    <body>
      <div
        id="root0"
        ng-version="17.0.0"
      >
        <my-component
          class="hydrated"
          first="nicolas"
        />
      </div>
    </body>

      19 |     await setup();
      20 |
    > 21 |     await waitFor(
         |                  ^
      22 |       () => {
      23 |         expect(screen.getByText("Hello, World! I'm nicolas")).toBeInTheDocument();
      24 |       },

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:163:27)
      at src/app/app.component.spec.ts:21:18

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        10.65 s
Ran all test suites.
```

Since Stencil is no longer shimming the Shadow DOM, it appears that testing-library does not know how to "pierce" or read into our web components. 

Full Disclosure: I'm far from a testing-library expert and haven't used it myself.

As I understand it, testing-library itself doesn't support the Shadow DOM at this time (https://github.com/testing-library/dom-testing-library/issues/413). There does however, appear to be a library that can help bridge the gap here - https://github.com/KonnorRogers/shadow-dom-testing-library/tree/main

I was able to get your reproduction case working with `shadow-dom-testing-library` with minimal changes here (although these might not be optimal in terms of performance and idiomatic testing-library code, I'm not well-versed in the library):
```diff
 import { ComponentFixture, TestBed } from '@angular/core/testing';
 import { AppComponent } from './app.component';
 import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
-import { render, screen, waitFor } from '@testing-library/angular';
+import { render, waitFor } from '@testing-library/angular';
+import { screen } from "shadow-dom-testing-library";
 
 describe('AppComponent', () => {
   const setup = async (): Promise<{
@@ -20,7 +21,7 @@ describe('AppComponent', () => {
 
     await waitFor(
       () => {
-        expect(screen.getByText("Hello, World! I'm nicolas")).toBeInTheDocument();
+        expect(screen.getByShadowText("Hello, World! I'm nicolas")).toBeInTheDocument();
       },
       { timeout: 10000 }
     );
```

Let me know if that works for your use case!
