### ISSUE TITLE
Resolve imports that are directories w/ an index file

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/stencil#537]
Worky:

```
import {} from '../utils/index';
```

No Worky:

```
import {} from '../utils';
```

**Comment by mattdsteele** [comment]
Test case: https://github.com/mattdsteele/stencil-unresolved-imports

**Comment by mattdsteele** [comment]
Error I see:

```
> my-component@0.0.1 build C:\Users\IGEN261\code\github\stencil-unresolved-imports\stencil-component-starter
> stencil build

[45:17.2]  @stencil/core v0.5.1
[45:17.2]  build, mycomponent, prod mode, started ...
[45:17.3]  compile started ...
[45:19.9]  compile finished in 2.65 s
{ Error: Could not resolve '../../utils' from dist\collection\components\my-component\my-component.js
    at error (C:\Users\IGEN261\code\github\stencil-unresolved-imports\stencil-component-starter\node_modules\rollup\dist\rollup.js:170:15)
    at C:\Users\IGEN261\code\github\stencil-unresolved-imports\stencil-component-starter\node_modules\rollup\dist\rollup.js:19528:25 code: 'UNRESOLVED_IMPORT' }

[ ERROR ]  Could not resolve '../../utils' from
           dist\collection\components\my-component\my-component.js

[ ERROR ]  rollup died at
           C:\Users\IGEN261\code\github\stencil-unresolved-imports\stencil-component-starter\node_modules\@stencil\core\dist\compiler\index.js:2764:19
           at throw (native) at rejected
           (C:\Users\IGEN261\code\github\stencil-unresolved-imports\stencil-component-starter\node_modules\@stencil\core\dist\compiler\index.js:2721:65)

[45:20.1]  build failed in 2.87 s
```

**Comment by adamdbradley** [comment]
Fix is in, thanks for helping identify this @mattdsteele!

**Comment by mattdsteele** [comment]
This is working great, thanks! 🎉
