### ISSUE TITLE
Dev server is broken in linux

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#550]
```
➜  core git:(core) ✗ npm run dev

> @ionic/core@0.0.2 dev /home/manu/repos/ionic/ionic/packages/core
> sd concurrent "stencil build --dev --watch --docs" "stencil-dev-server"

module.js:540
    throw err;
    ^

Error: Cannot find module 'faye-websocket'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/manu/repos/ionic/ionic/packages/core/node_modules/tiny-lr/src/client.js:13:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
[11:36.9]  @stencil/core v0.6.0 💎
[11:36.9]  build, ionic, dev mode, started ...
[11:37.1]  compile started ...
[11:42.1]  compile finished in 5.03 s
[11:45.6]  generate bundles started ...
[11:45.6]  generate bundles finished in 14 ms
[11:45.6]  generate app files started ...
[11:45.6]  generate app files finished in 13 ms
[11:45.7]  created readme docs: ion-icon
[11:46.0]  build finished, watching for changes... in 9.05 s
```

Seems to be related with a broken dependency `faye-websocket`

**Comment by jgw96** [comment]
@manucorporat just to be clear, this is only happening on linux right? (im guessing Ubuntu or Debian?)

**Comment by manucorporat** [comment]
@jgw96 yes, i reproduce it 100% of the time, even if I remove `node_modules`.

It is an Ubuntu Gnome 17.10

**Comment by AnthoniG** [comment]
I am running it in Linux Mint 18 'Sylvia' and it runs fine.
It really, really does not like Yarn though which is a shame as I prefer it over npm :smile:
