### ISSUE TITLE
Not all components are compiled since an Ubuntu kernel/dependencies upgrade

### ISSUE THREAD

**Issue by kael** [ionic-team/stencil#560]
**Stencil version:**

```
    Node : v9.5.0
    npm  : 5.6.0 
    OS   : Ubuntu 16.04.3 LTS
    Kernel: Linux 4.4.0-103-generic x86_64 // also tested with Linux 4.4.0-112-generic x86_64

    "@ionic/core": "0.0.2-65",
    "@stencil/core": "0.6.1", // tested with 0.6.3 also
    "@stencil/router": "latest"
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Since an OS upgrade (kernel and dependencies), I can't seem to make Stencil work. Compilation of a fresh install fails out-of-the-box whereas it was working before that OS upgrade.

The upgrade includes patches for Spectre/Meltdown but also dependencies updates (please see below for an excerpt of APT history).

As a consequence of that bug compilation fails silently, not all components are being compiled and/or copied in the build directory. And the HTML page appears blank with only the `<my-app></my-app>` top tag being rendered (without its children) in the DOM.

I've tested with both Node 8 and 9, I've removed purged and removed node related packages and executables. I've finally rollback booting to the previous version, from _Linux 4.4.0-112_ to _Linux 4.4.0-103_ , but without success

Also, one Stencil project was started before the upgrade (now updated to _@stencil/core 0.6.0_), and the compilation still works although the CSS has vanished (despite Sass plugin update).

**Expected behavior:**

- All modules should be compiled and/or copied in the build directory.
- Hence all components should appear in the DOM and not only the top tag `<my-app></my-app>`.

I believe several issues with Linux are related to some Kernel versions or some dependencies which are difficult to track.

**Steps to reproduce:**

**Related code:**

```bash
git clone https://github.com/ionic-team/ionic-pwa-toolkit.git my-pwa
cd my-pwa
npm install
npm start
> @stencil/starter@0.0.1 start /home/kael/dev/test/new/my-pwa
> npm run dev


> @stencil/starter@0.0.1 dev /home/kael/dev/test/new/my-pwa
> sd concurrent "stencil build --dev --watch" "stencil-dev-server" 

Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/kael/dev/test/new/my-pwa/node_modules/opn/index.js:82:13)
    at Object.onceWrapper (events.js:255:19)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:160:13)
    at Pipe._handle.close [as _onclose] (net.js:562:12)
[51:57.7]  @stencil/core v0.6.3 💎
[51:57.8]  build, app, dev mode, started ...
[51:57.8]  compile started ...
[51:57.8]  compile finished in 21 ms
[51:58.1]  generate bundles started ...
[51:58.1]  generate bundles finished in 2 ms
[51:58.1]  generate app files started ...
[51:58.1]  compile global style start ...
[51:58.1]  compile global style finish in 8 ms
[51:58.1]  generate app files finished in 44 ms
[51:58.7]  build finished, watching for changes... in 935 ms

~/dev/test/my-pwa$ ls www/build/app
app.core.js  app.registry.json  es5-build-disabled.js
```
```bash
$ cat www/build/app/app.registry.json 
{
  "namespace": "App",
  "fsNamespace": "app",
  "loader": "../app.js",
  "core": "app.core.js",
  "corePolyfilled": "es5-build-disabled.js",
  "components": {}
}
```

Whereas on another Ubuntu version with same Node/NPM/Stencil versions it works fine:

```
    Node : v9.5.0
    npm  : 5.6.0 
    OS   : Ubuntu 14.04.5 LTS //<= Different than above
    Kernel: Linux 4.4.0-104-generic x86_64  //<= Different than above

    "@ionic/core": "0.0.2-65",
    "@stencil/core": "0.6.3",
    "@stencil/router": "latest"
```

```bash
...
~/Project/my-app$ ls www/build/app/
app.core.js  app.global.js  app-home.js  app-profile.js  app.registry.json  chunk1.js  es5-build-disabled.js  my-app.js
```
```bash
$ cat www/build/app/app.registry.json 
{
  "namespace": "App",
  "fsNamespace": "app",
  "loader": "../app.js",
  "global": "app.global.js",
  "core": "app.core.js",
  "corePolyfilled": "es5-build-disabled.js",
  "components": {
    "app-home": {
      "$": "app-home"
    },
    "app-profile": {
      "$": "app-profile"
    },
    "my-app": {
      "$": "my-app"
    },
    "stencil-route": {
      "$": "my-app"
    },
    "stencil-route-link": {
      "$": "app-home"
    },
    "stencil-router": {
      "$": "my-app"
    }
  }
}
```

**Other information:**

Here's a log excerpt of APT history related the potential "faulty" updates:

```syslog
Start-Date: 2018-02-15  10:02:23
Commandline: apt-get upgrade -y
Requested-By: kael (1000)
Upgrade: update-manager-core:amd64 (1:16.04.10, 1:16.04.12),
uuid-runtime:amd64 (2.27.1-6ubuntu3.3, 2.27.1-6ubuntu3.4),
libfdisk1:amd64 (2.27.1-6ubuntu3.3, 2.27.1-6ubuntu3.4),
libapt-inst2.0:amd64 (1.2.24, 1.2.25),
libsystemd0:amd64 (229-4ubuntu21, 229-4ubuntu21.1),
grub-common:amd64 (2.02~beta2-36ubuntu3.15, 2.02~beta2-36ubuntu3.16),
apt:amd64 (1.2.24, 1.2.25),
libparted2:amd64 (3.2-15, 3.2-15ubuntu0.1),
python-zope.hookable:amd64 (4.0.4-4build2, 4.0.4-4+ubuntu16.04.1+certbot+1),
python-zope.interface:amd64 (4.1.3-1build1, 4.3.2-1+ubuntu16.04.1+certbot+1),
libmount1:amd64 (2.27.1-6ubuntu3.3, 2.27.1-6ubuntu3.4),
util-linux:amd64 (2.27.1-6ubuntu3.3, 2.27.1-6ubuntu3.4),
grub2-common:amd64 (2.02~beta2-36ubuntu3.15, 2.02~beta2-36ubuntu3.16),
udev:amd64 (229-4ubuntu21, 229-4ubuntu21.1),
resolvconf:amd64 (1.78ubuntu5, 1.78ubuntu6),
libapt-pkg5.0:amd64 (1.2.24, 1.2.25),
grub-pc:amd64 (2.02~beta2-36ubuntu3.15, 2.02~beta2-36ubuntu3.16),
libudev1:amd64 (229-4ubuntu21, 229-4ubuntu21.1),
libapparmor1:amd64 (2.10.95-0ubuntu2.7, 2.10.95-0ubuntu2.8),
mount:amd64 (2.27.1-6ubuntu3.3, 2.27.1-6ubuntu3.4),
grub-pc-bin:amd64 (2.02~beta2-36ubuntu3.15, 2.02~beta2-36ubuntu3.16),
libblkid1:amd64 (2.27.1-6ubuntu3.3, 2.27.1-6ubuntu3.4),
python-zope.component:amd64 (4.2.2-1, 4.3.0-1+ubuntu16.04.1+certbot+3),
libapparmor-perl:amd64 (2.10.95-0ubuntu2.7, 2.10.95-0ubuntu2.8),
python3-update-manager:amd64 (1:16.04.10, 1:16.04.12),
systemd-sysv:amd64 (229-4ubuntu21, 229-4ubuntu21.1),
libuuid1:amd64 (2.27.1-6ubuntu3.3, 2.27.1-6ubuntu3.4),
libpam-systemd:amd64 (229-4ubuntu21, 229-4ubuntu21.1),
parted:amd64 (3.2-15, 3.2-15ubuntu0.1),
systemd:amd64 (229-4ubuntu21, 229-4ubuntu21.1),
libsmartcols1:amd64 (2.27.1-6ubuntu3.3, 2.27.1-6ubuntu3.4),
apt-utils:amd64 (1.2.24, 1.2.25),
bsdutils:amd64 (1:2.27.1-6ubuntu3.3, 1:2.27.1-6ubuntu3.4),
python-configobj:amd64 (5.0.6-2, 5.0.6-2+ubuntu16.04.1+certbot+1),
apparmor:amd64 (2.10.95-0ubuntu2.7, 2.10.95-0ubuntu2.8),
apt-transport-https:amd64 (1.2.24, 1.2.25),
linux-firmware:amd64 (1.157.15, 1.157.16)
End-Date: 2018-02-15  10:05:33

Start-Date: 2018-02-15  10:08:17
Commandline: apt-get dist-upgrade
Requested-By: kael (1000)
Install: python3-funcsigs:amd64 (0.4-2, automatic),
python3-ndg-httpsclient:amd64 (0.4.2-1+certbot~xenial+1, automatic),
python3-zope.interface:amd64 (4.3.2-1+ubuntu16.04.1+certbot+1, automatic),
javascript-common:amd64 (11, automatic),
python-configparser:amd64 (3.3.0r2-2, automatic),
linux-image-extra-4.4.0-112-generic:amd64 (4.4.0-112.135, automatic),
python3-icu:amd64 (1.9.2-2build1, automatic),
python3-configargparse:amd64 (0.11.0-1+certbot~xenial+1, automatic),
python3-josepy:amd64 (1.0.1-1+ubuntu16.04.1+certbot+7, automatic),
linux-headers-4.4.0-112:amd64 (4.4.0-112.135, automatic),
python-future:amd64 (0.15.2-4+ubuntu16.04.1+certbot+3, automatic),
python3-asn1crypto:amd64 (0.22.0-2+ubuntu16.04.1+certbot+1, automatic),
python3-zope.hookable:amd64 (4.0.4-4+ubuntu16.04.1+certbot+1, automatic),
python3-pbr:amd64 (1.8.0-4ubuntu1, automatic),
libjs-jquery:amd64 (1.11.3+dfsg-4, automatic),
libjs-underscore:amd64 (1.7.0~dfsg-1ubuntu1, automatic),
python3-zope.event:amd64 (4.2.0-1, automatic),
linux-headers-4.4.0-112-generic:amd64 (4.4.0-112.135, automatic),
python3-zope.component:amd64 (4.3.0-1+ubuntu16.04.1+certbot+3, automatic),
python3-mock:amd64 (1.3.0-2.1ubuntu1, automatic),
python3-pyparsing:amd64 (2.0.3+dfsg1-1ubuntu0.1, automatic),
python3-future:amd64 (0.15.2-4+ubuntu16.04.1+certbot+3, automatic),
python3-cryptography:amd64 (1.9-1+ubuntu16.04.1+certbot+2, automatic),
python3-cffi-backend:amd64 (1.10.0-0.1+ubuntu16.04.1+certbot+1, automatic),
python3-acme:amd64 (0.21.1-1+ubuntu16.04.1+certbot+4, automatic),
python3-configobj:amd64 (5.0.6-2+ubuntu16.04.1+certbot+1, automatic),
python3-openssl:amd64 (17.3.0-1~0+ubuntu16.04.1+certbot+1, automatic),
python3-rfc3339:amd64 (1.0-4+certbot~xenial+1, automatic),
linux-image-4.4.0-112-generic:amd64 (4.4.0-112.135, automatic),
python3-certbot:amd64 (0.21.1-1+ubuntu16.04.1+certbot+0.2, automatic),
python3-tz:amd64 (2014.10~dfsg1-0ubuntu2, automatic),
python3-certbot-nginx:amd64 (0.21.1-1+ubuntu16.04.1+certbot+1),
python-josepy:amd64 (1.0.1-1+ubuntu16.04.1+certbot+7, automatic),
libjs-sphinxdoc:amd64 (1.3.6-2ubuntu1.1, automatic),
python3-parsedatetime:amd64 (2.4-3+ubuntu16.04.1+certbot+3, automatic),
python3-pyasn1:amd64 (0.1.9-2+certbot~xenial+1, automatic),
libdrm-common:amd64 (2.4.83-1~16.04.1, automatic)
Upgrade: linux-headers-generic:amd64 (4.4.0.103.108, 4.4.0.112.118),
python-acme:amd64 (0.19.0-1+ubuntu16.04.1+certbot+1, 0.21.1-1+ubuntu16.04.1+certbot+4),
linux-image-generic:amd64 (4.4.0.103.108, 4.4.0.112.118),
certbot:amd64 (0.19.0-1+ubuntu16.04.1+certbot+1, 0.21.1-1+ubuntu16.04.1+certbot+0.2),
libdrm2:amd64 (2.4.76-1~ubuntu16.04.1, 2.4.83-1~16.04.1),
python-parsedatetime:amd64 (2.1-3+certbot~xenial+1, 2.4-3+ubuntu16.04.1+certbot+3),
python-certbot-nginx:amd64 (0.19.0-1+ubuntu16.04.1+certbot+1, 0.21.1-1+ubuntu16.04.1+certbot+1),
linux-generic:amd64 (4.4.0.103.108, 4.4.0.112.118)
Remove: python-certbot:amd64 (0.19.0-1+ubuntu16.04.1+certbot+1)
End-Date: 2018-02-15  10:10:08

Start-Date: 2018-02-15  16:03:47
Commandline: apt-get install -y nodejs
Requested-By: kael (1000)
Upgrade: nodejs:amd64 (8.9.4-1nodesource1, 9.5.0-1nodesource1)
End-Date: 2018-02-15  16:03:53
```

**Comment by jgw96** [comment]
Hmmm, admittedly this is going to be a tough issue to track down. Does this only happen with Stencil? Could you try things like the Preact CLI or Vue CLI and see if they work?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Stencil!
