### ISSUE TITLE
invalid testing root node

### ISSUE THREAD

**Issue by ScottMGerstl** [ionic-team/stencil#573]
**Stencil version:**

```
 @stencil/core@0.6.7
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When running test for the following component, I get this error when the flush function runs:

```
invalid testing root node

      at Object.<anonymous> (node_modules/@stencil/core/dist/testing/index.js:15794:19)
          at Generator.next (<anonymous>)
      at node_modules/@stencil/core/dist/testing/index.js:15722:71
      at Object.<anonymous>.__awaiter$58 (node_modules/@stencil/core/dist/testing/index.js:15718:12)
      at Object.flush (node_modules/@stencil/core/dist/testing/index.js:15791:12)
      at Object.<anonymous> (src/components/days/day-button-list/day-button-list.spec.ts:63:60)
      at step (src/components/days/day-button-list/day-button-list.spec.ts:32:23)
      at Object.next (src/components/days/day-button-list/day-button-list.spec.ts:13:53)
      at src/components/days/day-button-list/day-button-list.spec.ts:7:71
      at Object.<anonymous>.__awaiter (src/components/days/day-button-list/day-button-list.spec.ts:3:12)
      at Object.<anonymous> (src/components/days/day-button-list/day-button-list.spec.ts:60:90)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Steps to reproduce:**

1. Put the following component code in a starter app
2. run tests

**Related code:**

*// day-button-list.tsx*

```tsx
import { Component, State } from '@stencil/core';

@Component({
  tag: 'day-button-list',
  styleUrl: 'day-button-list.css'
})
export class DaysButtonList {

  @State() days: DaySelection[] = [
    { label: 'Su', selected: true },
    { label: 'M', selected: true },
    { label: 'Tu', selected: true },
    { label: 'W', selected: true },
    { label: 'Th', selected: true },
    { label: 'F', selected: true },
    { label: 'Sa', selected: true }
  ];

  private handleDayClicked(day: DaySelection) {
    day.selected = !day.selected;
    // day = Object.assign({}, day);
    this.days = [... this.days];
  }

  private selectedClass(day: DaySelection) {
    return day.selected === true ? 'selected' : '';
  }

  render() {
    return (
      <div class="form-group" id="days-form-group">
        <label>What days would you like notifications?</label>
        <div class="schedule-days-container">
          { this.days.map(day =>
            <div class={'day-button btn ' + this.selectedClass(day)} onClick={() => this.handleDayClicked(day)}>{day.label}</div>
          )}
        </div>
      </div>
    );
  }
}

interface DaySelection {
  label: string;
  selected: boolean
}

// class={this.completedClass(todo)}

```

*// day-button-list.spec.ts*

```ts
import { flush, render } from '@stencil/core/testing';
import { DaysButtonList } from './day-button-list';

describe('day-button-list', () => {
  it('should build', () => {
    expect(new DaysButtonList()).toBeTruthy();
  });

  describe('rendering', () => {
    let element;

    beforeEach(async () => {
      element = await render({
        components: [DaysButtonList],
        html: '<day-button-list></day-button-list>'
      });
    });

    it('should render all weekdays', async () => {
      await flush(element);
      // expect(element.queryselectorAll('.day-button').length).toEqual(7);
    })
  });
});
```

**Other information:**

A better error message would be helpful in this case I think.

I do not know what I have done wrong. Not sure if this is a bug or if the error isn't descriptive enough to track down the issue. When used in an app, it does render and behave as expected. This is my first experience with TSX or JSX.

**Comment by jagreehal** [comment]
@ScottMGerstl this looks to be fixed in the next version of Stencil.

You'll need to change element.queryselectorAll to element.querySelectorAll

**Comment by adamdbradley** [comment]
Thanks for creating the issue, should be fixed up now and tests added to the repo, thanks
