### ISSUE TITLE
bug: Our build break since `v4.18.1`

### ISSUE THREAD

**Issue by deleonio** [ionic-team/stencil#5766]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.18.1

### Current Behavior

We update `stencil` in this PR: https://github.com/public-ui/kolibri/pull/6418/files#diff-2c76dc06185f93bec73660e15338433b95eac6707317564c0f778f5b9abe446c

```bash
FAIL src/components/quote/test/snapshot.spec.tsx
    ● Test suite failed to run
  
      ENOENT: no such file or directory, open 'node:path'
  
        at Runtime.readFile (../../node_modules/.pnpm/jest-runtime@26.6.3_ts-node@10.9.2/node_modules/jest-runtime/build/index.js:1987:21)
        at Object.760 (../../node_modules/.pnpm/@stencil+core@4.18.1/node_modules/@stencil/core/sys/node/glob.js:1:2995)
        at s (../../node_modules/.pnpm/@stencil+core@4.18.1/node_modules/@stencil/core/sys/node/glob.js:1:85614)
        at Object.576 (../../node_modules/.pnpm/@stencil+core@4.18.1/node_modules/@stencil/core/sys/node/glob.js:1:67906)
```

### Expected Behavior

Have no dependency issues.

### Steps to Reproduce

Sorry. I do not know, how you can reproduce this exception.

### Code Reproduction URL

https://github.com/public-ui/kolibri/pull/6418/files#diff-2c76dc06185f93bec73660e15338433b95eac6707317564c0f778f5b9abe446c

### Additional Information

Thank you!

**Comment by alicewriteswrongs** [comment]
Hey @deleonio thanks for reporting this, I wasn't able to reproduce that error locally my testing. Would you possibly be able to put together a minimal reproduction? Without that we have a hard time debugging errors.

**Comment by deleonio** [comment]
@alicewriteswrongs 

Here I prepare a reproduction sample: https://github.com/deleonio/kolibri-library/tree/reproduction-5766

4.18.0 works
4.18.1 does not work

**Comment by christian-bromann** [comment]
Thanks @deleonio for providing more information on this, I will take a look!

**Comment by christian-bromann** [comment]
Hey @deleonio 👋 

I've identified that our recent update of [glob](https://github.com/ionic-team/stencil/commit/cbb06cdb73365e16dccb10f22cc5bee478eb94c7) has caused this issue, in particular the part where it imports node internals:

<img width="1162" alt="Screenshot 2024-05-20 at 11 31 55 AM" src="https://github.com/ionic-team/stencil/assets/731337/d4597a96-2411-4f9d-b821-1a8dfdf2381a">

It seems that this conflicts with running tests in Jest v26. Is there any reason you are on this particular Jest version and are unable to update?

**Comment by christian-bromann** [comment]
@deleonio I have a dev build for you with a fix. Yoi can install it via `npm i @stencil/core@4.18.2-dev.1716246842.b6713e1`. I recommend to update Jest to avoid these types of compatibility issues moving on.

**Comment by deleonio** [comment]
> Hey @deleonio 👋
> 
> I've identified that our recent update of [glob](https://github.com/ionic-team/stencil/commit/cbb06cdb73365e16dccb10f22cc5bee478eb94c7) has caused this issue, in particular the part where it imports node internals:
> 
> <img alt="Screenshot 2024-05-20 at 11 31 55 AM" width="1162" src="https://private-user-images.githubusercontent.com/731337/332166379-d4597a96-2411-4f9d-b821-1a8dfdf2381a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjQ4OTUsIm5iZiI6MTcxNjI2NDU5NSwicGF0aCI6Ii83MzEzMzcvMzMyMTY2Mzc5LWQ0NTk3YTk2LTI0MTEtNGY5ZC1iODIxLTFhOGRmZGYyMzgxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwNDA5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDI1NzNiNDJjODEyNGExMzhhNzRmNDFiM2I5ZWU5MzMxNzM4ZmYxNWMzMGE0ZTdmNzlkY2NmYzllOGRiOGM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E3_X-fRzrVc_D2fA_p8lw3FxLfvtOx6UGUqCxisIUQk">
> _(left new vs right older version of glob bundled in Stencil)_
> 
> It seems that this conflicts with running tests in Jest v26. Is there any reason you are on this particular Jest version and are unable to update? Updating Jest to the latest version has fixed the problem for me using your reproduction case.

We always try to switch to the latest versions. With Jest, we have never managed to upgrade from 26.

We will try again.

**Comment by deleonio** [comment]
Hey,

first I tried to upgrade jest again. Now we could upgrade to version `^27`.

Next I will check you provided npm package `stencil/core@4.18.2-dev.1716246842.b6713e1`.

**Comment by deleonio** [comment]
> @deleonio I have a dev build for you with a fix. Yoi can install it via `npm i @stencil/core@4.18.2-dev.1716246842.b6713e1`. I recommend to update Jest to avoid these types of compatibility issues moving on.

👍 our pipeline passed! https://github.com/public-ui/kolibri/pull/6460
