### ISSUE TITLE
Growl desktop popup notification of compilation result

### ISSUE THREAD

**Issue by kael** [ionic-team/stencil#579]
**I'm submitting a:**

[ ] bug report
[x] feature request

**Expected behavior:**

It'd be nice to be notified of the end of the compilation with a Growl desktop popup notification. That way, we wouldn't need to keep watching the console or live reload to be aware of the end of the compilation.

The popup would display the compilation result similarly to that erlang [Sync](https://github.com/rustyio/sync#desktop-notifications) utility. 

There could be a new optional `--alert` or `--growl` parameter to pass at start.

**Comment by adamdbradley** [comment]
Love it! I'll add this to the dev-server milestone. Thanks!

**Comment by kael** [comment]
Thank you !

And BTW, a big thanks to the team for Stencil, that's an awesome smart tool.

**Comment by kael** [comment]
Digging a bit on the subject, I came across [node-notifier](https://github.com/mikaelbr/node-notifier). It has the ability to add a button to the notification.

One button that'd be nice to have is an optional/conditionnal one that would restart the compilation, because sometimes failed compilation are due to _rollup_ errors, (see below) and it only requires to save the file - `Ctrl+s` - again to have a correct compilation.

Example of recoverable compilation error that vanishes with  a `Ctrl+s`:

```
[48:40.7]  changed file: myapp-maps.tsx
[48:40.7]  rebuild, app, dev mode, started ...
[48:40.7]  compile started ...
[48:44.9]  compile finished in 4.15 s
{ Error: 'my-component' is not exported by dist/collection/components/my-component/my-component.js
    at error (/home/kael/Project/dev/myapp/node_modules/@stencil/core/node_modules/rollup/dist/rollup.js:170:15)
    at Module.error (/home/kael/Project/dev/myapp/node_modules/@stencil/core/node_modules/rollup/dist/rollup.js:17195:9)
    at handleMissingExport (/home/kael/Project/dev/myapp/node_modules/@stencil/core/node_modules/rollup/dist/rollup.js:17458:12)
    at /home/kael/Project/dev/myapp/node_modules/@stencil/core/node_modules/rollup/dist/rollup.js:19070:56
    at Array.reduce (<anonymous>)
    at Graph.handleMissingExport (/home/kael/Project/dev/myapp/node_modules/@stencil/core/node_modules/rollup/dist/rollup.js:19069:27)
    at Module.traceExport (/home/kael/Project/dev/myapp/node_modules/@stencil/core/node_modules/rollup/dist/rollup.js:17315:28)
    at /home/kael/Project/dev/myapp/node_modules/@stencil/core/node_modules/rollup/dist/rollup.js:17107:34
    at Array.forEach (<anonymous>)
    at Module.markExports (/home/kael/Project/dev/myapp/node_modules/@stencil/core/node_modules/rollup/dist/rollup.js:17106:29)
  code: 'MISSING_EXPORT',
  url: 'https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module',
  pos: 9,
  loc: 
   { file: 'entry:my-component',
     line: 1,
     column: 9 },
  frame: '1: export { my-component as my-component } from \'./dist/collection/components/my-component/my-component.js\';\n            ^\n2: export { MyComponent as MyComponent } from \'./dist/collection/components/my-component/my-component.js\'' }

[ ERROR ]  Error parsing:
           entry:my-component,
           line: 1, column: 9

[ ERROR ]  rollup died at /home/kael/Project/dev/myapp/node_modules/@stencil/core/dist/compiler/index.js:2061:19
           at Generator.throw (<anonymous>) at rejected
           (/home/kael/Project/dev/myapp/node_modules/@stencil/core/dist/compiler/index.js:2017:65) at <anonymous>

[48:45.5]  rebuild failed, watching for changes... in 4.79 s
```

**Comment by adamdbradley** [comment]
Going to close the feature request for now. If it's a heavily requested feature we can reevaluate. Thanks
