### ISSUE TITLE
bug: Error on test when using axios with stencil (MockAnchorElement)

### ISSUE THREAD

**Issue by zaaknafein** [ionic-team/stencil#6047]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.22.2

### Current Behavior

An error is displayed when importing Axios in spec / e2e file.\
No problem at runtime in the application.
```
FAIL  src/services/user.service.spec.ts
  ● Test suite failed to run

    TypeError: Invalid URL

> 1 | import axios from "axios";
        | ^
      2 | import { User, UserService } from "./user.service";
      3 |
      4 | describe('UserService', () => {

      at MockAnchorElement.get pathname [as pathname] (node_modules/@stencil/core/mock-doc/index.cjs:7848:12)
      at resolveURL (node_modules/axios/lib/helpers/isURLSameOrigin.js:41:35)
      at standardBrowserEnv (node_modules/axios/lib/helpers/isURLSameOrigin.js:47:17)
      at Object.<anonymous> (node_modules/axios/lib/helpers/isURLSameOrigin.js:60:4)
      at Object.<anonymous> (src/services/user.service.spec.ts:1:1)
```

### Expected Behavior

You should be able to test services while mocking Axios comportment without any problem.

### System Info

```shell
System: node 20.17.0
    Platform: windows (10.0.19045)
   CPU Model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 cpus)
    Compiler: C:\dev\projects\bandeau-patient\node_modules\@stencil\core\compiler\stencil.js
       Build: 1729874537
     Stencil: 4.22.2
  TypeScript: 5.5.4
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.31.1
```

### Steps to Reproduce

- Use Axios in a service
- Write a test with jest while mocking Axios

### Code Reproduction URL

https://github.com/zaaknafein/stencil-test

### Additional Information

Maybe similar to [this problem](https://github.com/ionic-team/stencil/issues/2969).

Dunno why this method is call on test initialization...

**Comment by christian-bromann** [comment]
This has been released in https://github.com/ionic-team/stencil/releases/tag/v4.22.3

**Comment by zaaknafein** [comment]
Great news, thank you for your responsiveness :)
