### ISSUE TITLE
in-memory-fs.spec.ts fails on Windows

### ISSUE THREAD

**Issue by tja4472** [ionic-team/stencil#629]
**Stencil version:**

```
 @stencil/core@0.7.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Test fails on Windows

**Expected behavior:**
Test passes on Windows

**Steps to reproduce:**
npm test in-memory-fs.spec.ts
```
 ● in-memory-fs › readdir, recursive

    expect(received).toHaveLength(length)

    Expected value to have length:
      5
    Received:
      [{"absPath": "/dir1/dir2", "isDirectory": true, "isFile": false, "relPath": "dir2"}, {"absPath": "/dir1/dir2/file1.js", "isDirectory": false, "isFile": true, "relPath": "dir2/file1.js"}, {"absPath": "/dir1/dir2/file1.js", "isDirectory": false, "isFile": true, "relPath": "dir2/file1.js"}, {"absPath": "/dir1/dir2/file2.js", "isDirectory": false, "isFile": true, "relPath": "dir2/file2.js"}, {"absPath": "/dir1/dir2/file2.js", "isDirectory": false, "isFile": true, "relPath": "dir2/file2.js"}, {"absPath": "/dir1/file1.js", "isDirectory": false, "isFile": true, "relPath": "file1.js"}, {"absPath": "/dir1/file2.js", "isDirectory": false, "isFile": true, "relPath": "file2.js"}]
    received.length:
      7

      332 |     await fs.writeFile(`/dir1/dir2/file2.js`, `2`);
      333 |     await fs.writeFile(`/dir1/dir2/sub1/file3.js`, `3`);
    > 334 |     await fs.writeFile(`/dir1/dir2/sub2/file4.js`, `4`);
      335 |     await fs.writeFile(`/not-dir/dir2/file5.js`, `5`);
      336 |     await fs.writeFile(`/not-dir/dir2/file6.js`, `6`);
      337 |     // NO COMMIT!

      at Object.<anonymous> (src/util/test/in-memory-fs.spec.ts:334:23)
      at fulfilled (src/util/test/in-memory-fs.spec.ts:4:58)

  ● in-memory-fs › readdir, no recursive

    expect(received).toHaveLength(length)

    Expected value to have length:
      3
    Received:
      [{"absPath": "/dir1/dir2", "isDirectory": true, "isFile": false, "relPath": "dir2"}, {"absPath": "/dir1/dir2/file1.js", "isDirectory": false, "isFile": true, "relPath": "dir2/file1.js"}, {"absPath": "/dir1/dir2/file2.js", "isDirectory": false, "isFile": true, "relPath": "dir2/file2.js"}, {"absPath": "/dir1/file1.js", "isDirectory": false, "isFile": true, "relPath": "file1.js"}, {"absPath": "/dir1/file2.js", "isDirectory": false, "isFile": true, "relPath": "file2.js"}]
    received.length:
      5

      357 |
      358 |   it(`readdir always does disk reads`, async () => {
    > 359 |     await fs.writeFile(`/dir/file1.js`, `1`);
      360 |     await fs.commit();
      361 |
      362 |     let files = await fs.readdir(`/dir`);

      at Object.<anonymous> (src/util/test/in-memory-fs.spec.ts:359:23)
      at fulfilled (src/util/test/in-memory-fs.spec.ts:4:58)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 46 passed, 48 total
```

**Related code:**

```tsx
  readdir(dirPath: string) {
    return new Promise<string[]>((resolve, reject) => {
      setTimeout(() => {
        dirPath = normalizePath(dirPath);
        this.diskReads++;

        if (!this.data[dirPath]) {
          reject(`readdir, dir doesn't exists: ${dirPath}`);
        } else {
          const filePaths = Object.keys(this.data);
          const dirs: string[] = [];

          filePaths.forEach(f => {
            const pathRelative = path.relative(dirPath, f);
            // Windows: pathRelative =  ..\dir2\dir3\dir4\file2.js
            const dirItem = normalizePath(pathRelative).split('/')[0];

            if (!dirItem.startsWith('.') && !dirItem.startsWith('/')) {
              if (dirItem !== '' && !dirs.includes(dirItem)) {
                dirs.push(dirItem);
              }
            }
          });

          resolve(dirs.sort());
        }
      }, this.resolveTime);
    });
  }

```

**Other information:**

**Comment by adamdbradley** [comment]
Fixed with https://github.com/ionic-team/stencil/pull/630
