### ISSUE TITLE
Cannot use ionic during test: TypeError: Cannot read property 'getAttribute' of undefined

### ISSUE THREAD

**Issue by JStumpp** [ionic-team/stencil#675]
**Stencil version:**

```
 "@stencil/core": "0.7.8",
 "@ionic/core": "0.1.5-2"
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When I use 
```
import '@ionic/core';
```
in a component, the test fail with the following exception:
``` ● Test suite failed to run

    TypeError: Cannot read property 'getAttribute' of undefined

      at Object.<anonymous>.m.ios (node_modules/@ionic/core/dist/ionic.js:5:575)
      at Object.<anonymous> (node_modules/@ionic/core/dist/ionic.js:5:1296)
      at Object.<anonymous> (src/components/my-app/my-app.tsx:9:1)
      at Object.<anonymous> (src/components/my-app/my-app.spec.ts:40:16)
```

This happens since ionic version 0.1.4-9 (0.1.4-8 was ok). I guess this is a stencil bug.

**Related code:**

my-app.tsx:
```tsx
import { Component } from '@stencil/core';
import '@ionic/core';

@Component({
  tag: 'my-app',
  styleUrl: 'my-app.scss'
})
export class MyApp {

  render() {
    return (
      <ion-app>
        <main>
        </main>
      </ion-app>
    );
  }
}
```

my-app.spec.ts:
```tsx
import { render } from '@stencil/core/testing';
import { MyApp } from './my-app';

describe('my-app', () => {
  it('should build', () => {
    expect(new MyApp()).toBeTruthy();
  });

  describe('rendering', () => {
    beforeEach(async () => {
      await render({
        components: [MyApp],
        html: '<my-app></my-app>'
      });
    });
  });
});
```

**Comment by jgw96** [comment]
cc @manucorporat , any ideas here?

**Comment by juanmiguelbesada** [comment]
Should this issue be closed due new stencil testing suite as commented here https://github.com/ionic-team/stencil/issues/713#issuecomment-425129415?

**Comment by adamdbradley** [comment]
@juanmiguelbesada yes thanks
