### ISSUE TITLE
Errors and incorrect DOM during DOM patch

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#698]
**Stencil version:**
```
 @stencil/core@0.7.15
```

**I'm submitting a:**
[x] bug report

**Current behavior:**

When certain content combinations are returned from the render function it can cause errors or incorrect order of the resulting DOM elements.

Content being placed into slots can sometimes result in the following error:

```tsx
app.core.js:2133 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Object.$insertBefore (http://localhost:3333/app/build/app/app.core.js:391:75)
    at addVnodes (http://localhost:3333/app/build/app/app.core.js:1357:20)
    at updateChildren (http://localhost:3333/app/build/app/app.core.js:1430:33)
    at patchVNode (http://localhost:3333/app/build/app/app.core.js:1474:11)
    at updateChildren (http://localhost:3333/app/build/app/app.core.js:1390:11)
    at patchVNode (http://localhost:3333/app/build/app/app.core.js:1474:11)
    at updateChildren (http://localhost:3333/app/build/app/app.core.js:1390:11)
    at patchVNode (http://localhost:3333/app/build/app/app.core.js:1474:11)
    at Object.patch [as render] (http://localhost:3333/app/build/app/app.core.js:1511:13)
    at render (http://localhost:3333/app/build/app/app.core.js:871:35)
```

This seems to occur when content is being placed in a slot.  For example, using the `<ion-content>` element.

Here are the results of rendering various content combinations into the element:

```tsx
// Test data

const textA = 'A';
const spanA = <span>A</span>;
const divA = <div>A</div>;

const textB = 'B';
const spanB = <span>B</span>;
const divB = <div>B</div>;

// Here are the results of various rendering approaches

return <ion-content>{textA}{textB}</ion-content>; // works
return <ion-content>{textA}{spanB}</ion-content>; // works
return <ion-content>{textA}{divB}</ion-content>; // Error
return <ion-content><div>{textA}{divB}</div></ion-content>; // works (wrapped in div)

return <ion-content>{spanA}{textB}</ion-content>; // works
return <ion-content>{spanA}{spanB}</ion-content>; // works
return <ion-content>{spanA}{divB}</ion-content>; // Error

return <ion-content>{divA}{textB}</ion-content>; // renders as "BA", again as "AB"
// 1st time => <div class="scroll-inner"><!---->B</div><div style="">A</div>
// 2nd time => <div class="scroll-inner"><!----><!----><div>A</div>B</div>
return <ion-content>{divA}{spanB}</ion-content>; // renders as "BA", again as "AB"
return <ion-content>{divA}{divB}</ion-content>; // renders as "BA", again as "AB"

```

It appears that the errors occur in the following conditions:
- Slot content is an array of elements instead of a single element.
- DIV or other elements are used

**Comment by adamdbradley** [comment]
Thanks for debugging this, we'll get this fixed up. Thanks

**Comment by adamdbradley** [comment]
Also should add, we're implementing e2e tests as we speak to help prevent any regressions like these.

**Comment by adamdbradley** [comment]
Adding so more e2e tests here: https://github.com/ionic-team/stencil/tree/master/test/e2e/app/slot-basic

But I'm not able to replicate the issue, so this implementation is probably missing something. Would you be able to take a look?

**Comment by cjorasch** [comment]
It works when I use the `<slot-basic-content>` container but not when I use an `<ion-content>` container.
