### ISSUE TITLE
Windows: Incorrect path used to run Karma in package.json

### ISSUE THREAD

**Issue by tja4472** [ionic-team/stencil#722]
**Stencil version:**

```
@stencil/core@0.7.20
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

```powershell
PS C:\VSCode\stencil\stencil> npm run test.karma

> @stencil/core@0.7.20 test.karma C:\VSCode\stencil\stencil
> node bin/stencil build -c test/karma/stencil.config.js && node test/karma/node_modules/.bin/karma start test/karma/karma.config.js

[33:16.8]  @stencil/core v0.7.20
[33:16.8]  build, app, prod mode, started ...
[33:16.8]  compile started ...
[33:19.6]  compile finished in 2.78 s
[33:19.6]  module map started ...
[33:19.7]  module map finished in 160 ms
[33:19.7]  generate bundles started ...
[33:19.7]  generate bundles finished in 8 ms
[33:19.7]  generate app files started ...
[33:19.8]  generate app files finished in 21 ms
[33:19.8]  build finished in 3.02 s

C:\VSCode\stencil\stencil\test\karma\node_modules\.bin\karma:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
**Expected behavior:**

Test passes on Windows
```powershell
PS C:\VSCode\stencil\stencil> npm run test.karma.windows

> @stencil/core@0.7.20 test.karma.windows C:\VSCode\stencil\stencil
> node bin/stencil build -c test/karma/stencil.config.js && cd test/karma/node_modules/.bin && karma start ../../karma.config.js

[34:38.1]  @stencil/core v0.7.20
[34:38.1]  build, app, prod mode, started ...
[34:38.1]  compile started ...
[34:40.8]  compile finished in 2.75 s
[34:40.8]  module map started ...
[34:41.0]  module map finished in 157 ms
[34:41.0]  generate bundles started ...
[34:41.0]  generate bundles finished in 7 ms
[34:41.0]  generate app files started ...
[34:41.0]  generate app files finished in 21 ms
[34:41.0]  build finished in 2.98 s

11 04 2018 11:34:43.053:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.8.1
11 04 2018 11:34:45.296:INFO [compiler.karma-typescript]: Compiled 15 files in 2184 ms.
11 04 2018 11:34:45.965:INFO [bundler.karma-typescript]: Bundled imports for 7 file(s) in 166 ms.
11 04 2018 11:34:45.994:INFO [karma]: Karma v2.0.0 server started at http://0.0.0.0:9876/
11 04 2018 11:34:45.996:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
11 04 2018 11:34:46.003:INFO [launcher]: Starting browser ChromeHeadless
11 04 2018 11:34:47.058:INFO [HeadlessChrome 67.0.3372 (Windows 10.0.0)]: Connected on socket Cr2OQcukivFhNe_sAAAA with id 89463791
HeadlessChrome 67.0.3372 (Windows 10.0.0): Executed 4 of 4 SUCCESS (0.146 secs / 0 secs)
```

**Steps to reproduce:**

**Related code:**

package.json
```json
"test.karma.windows": "node bin/stencil build -c test/karma/stencil.config.js && cd test/karma/node_modules/.bin && karma start ../../karma.config.js",  
```

**Other information:**

**Comment by adamdbradley** [comment]
Would you be able to test with the latest release? Thanks

**Comment by tja4472** [comment]
## `npm run test.karma` fails :sob:

```bash
PS C:\VSCode\2018\git-hub-ionic\stencil> npm run test.karma

> @stencil/core@0.9.10 test.karma C:\VSCode\2018\git-hub-ionic\stencil
> cd test/karma && npm run karma.prod

> @ karma.prod C:\VSCode\2018\git-hub-ionic\stencil\test\karma
> npm run tsc && npm run build.app && npm run build.sibling && npm run build.prerender && npm run karma.webpack && karma start karma.config.js

> @ tsc C:\VSCode\2018\git-hub-ionic\stencil\test\karma
> node ../../node_modules/.bin/tsc -p tsconfig.json

C:\VSCode\2018\git-hub-ionic\stencil\node_modules\.bin\tsc:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
^^^^^^^

SyntaxError: missing ) after argument list
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module.\_compile (module.js:616:28)
at Object.Module.\_extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module.\_load (module.js:497:3)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:191:16)
at bootstrap_node.js:612:3
```

## test\karma\package.json

Replace

```json
"tsc": "node ../../node_modules/.bin/tsc -p tsconfig.json"
```

with

```json
 "tsc": "node ../../node_modules/typescript/lib/tsc -p tsconfig.json"
```

## Success! :smile:

```bash
21 06 2018 11:04:45.665:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.9.1
21 06 2018 11:04:49.275:INFO [compiler.karma-typescript]: Compiled 89 files in 3419 ms.
21 06 2018 11:04:49.971:INFO [bundler.karma-typescript]: Bundled imports for 33 file(s) in 193 ms.
21 06 2018 11:04:50.028:INFO [karma]: Karma v2.0.0 server started at http://0.0.0.0:9876/
21 06 2018 11:04:50.029:INFO [launcher]: Launching browsers ChromeHeadless, Firefox with unlimited concurrency
21 06 2018 11:04:50.035:INFO [launcher]: Starting browser ChromeHeadless
21 06 2018 11:04:50.081:INFO [launcher]: Starting browser Firefox
21 06 2018 11:04:52.816:INFO [HeadlessChrome 67.0.3372 (Windows 10.0.0)]: Connected on socket 1u5QPbYZT5iFKDHvAAAA with id 14410666
HeadlessChrome 67.0.3372 (Windows 10.0.0): Executed 43 of 43 SUCCESS (16.256 secs / 0 secs)
```
