### ISSUE TITLE
0.7.25 - Rollup Dies

### ISSUE THREAD

**Issue by popcorn245** [ionic-team/stencil#750]
**Stencil version:**

```
 @stencil/core@v0.7.25
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Rollup keeps dying

**Expected behavior:**

Would build correctly 
**Steps to reproduce:**

**Related code:**

```
[43:47.5]  @stencil/core v0.7.25
[43:47.5]  build, app, dev mode, started ...

> trackmygiving@1.0.0 sync D:\apps\TrackMyGiving
> browser-sync start -c bs-config.js

[43:47.5]  compile started ...
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3245
    External: http://192.168.1.106:3245
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.106:3001
 --------------------------------------
[Browsersync] Serving files from: www
[Browsersync] Watching files...
[43:53.6]  compile finished in 6.12 s
[43:53.6]  module map started ...
[43:55.1]  module map finished in 1.51 s

[ ERROR ]  TypeError: Cannot read property 'start' of null
           at IfStatement.render
           (D:\apps\TrackMyGiving\node_modules\rollup\dist\rollup.js:15204:52)
           at IfStatement.NodeBase.render
           (D:\apps\TrackMyGiving\node_modules\rollup\dist\rollup.js:13611:23)
           at IfStatement.render
           (D:\apps\TrackMyGiving\node_modules\rollup\dist\rollup.js:15199:37)
           at renderStatementList
           (D:\apps\TrackMyGiving\node_modules\rollup\dist\rollup.js:13709:25)           at BlockStatement.render
           (D:\apps\TrackMyGiving\node_modules\rollup\dist\rollup.js:14500:13)
           at IfStatement.NodeBase.render           (D:\apps\TrackMyGiving\node_modules\rollup\dist\rollup.js:13611:23)
           at IfStatement.render
           (D:\apps\TrackMyGiving\node_modules\rollup\dist\rollup.js:15199:37)           at renderStatementList
           (D:\apps\TrackMyGiving\node_modules\rollup\dist\rollup.js:13709:25)
           at BlockStatement.render           (D:\apps\TrackMyGiving\node_modules\rollup\dist\rollup.js:14500:13)
           at FunctionExpression.NodeBase.render
           (D:\apps\TrackMyGiving\node_modules\rollup\dist\rollup.js:13611:23)
[43:55.2]  build failed, watching for
           changes... in 7.69 s
```

**Other information:**

Was working happily on v0.7.24, just updated this morning and got this.

**Comment by jgw96** [comment]
Hey! This is actually a rollup issue in their latest release https://github.com/rollup/rollup/issues/2134 . We are aware of this issue and are actively pushing people towards that issue so the rollup team can get it prioritized. Because this is a rollup issue and not actually an issue in our code I am going to close this issue for now with a link to the rollup issue. Thanks for using Stencil!
