### ISSUE TITLE
Rollup dies - Cannot read property 'type' of null

### ISSUE THREAD

**Issue by popcorn245** [ionic-team/stencil#776]
**Stencil version:**

```
 @stencil/core@v0.8.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Just upgraded an Ionic PWA toolkit app to the latest stencil / ionic core

**Expected behavior:**

Should build

**Steps to reproduce:**

```
git clone https://github.com/madnesslabs/madnesslabspwa
cd madnesslabspwa
npm install
npm start
```

**Related code:**

```
[45:07.4]  @stencil/core v0.8.0
[45:07.4]  build, app, dev mode, started ...
[45:07.5]  compile started ...
[45:10.0]  compile finished in 2.60 s
[45:10.1]  module map started ...
{ TypeError: Cannot read property 'type' of null
    at extractNames (D:\apps\MadnessLabsPWA\node_modules\rollup-pluginutils\dist\pluginutils.cjs.js:52:20)
    at Scope.addDeclaration (D:\apps\MadnessLabsPWA\node_modules\rollup-pluginutils\dist\pluginutils.cjs.js:83:3)
    at Object.enter (D:\apps\MadnessLabsPWA\node_modules\rollup-pluginutils\dist\pluginutils.cjs.js:105:11)
    at visit (D:\apps\MadnessLabsPWA\node_modules\rollup-pluginutils\node_modules\estree-walker\dist\estree-walker.umd.js:32:9)
    at visit (D:\apps\MadnessLabsPWA\node_modules\rollup-pluginutils\node_modules\estree-walker\dist\estree-walker.umd.js:51:4)
    at visit (D:\apps\MadnessLabsPWA\node_modules\rollup-pluginutils\node_modules\estree-walker\dist\estree-walker.umd.js:46:5)
    at Object.walk (D:\apps\MadnessLabsPWA\node_modules\rollup-pluginutils\node_modules\estree-walker\dist\estree-walker.umd.js:11:2)
    at Object.attachScopes (D:\apps\MadnessLabsPWA\node_modules\rollup-pluginutils\dist\pluginutils.cjs.js:100:15)
    at inject (D:\apps\MadnessLabsPWA\node_modules\rollup-plugin-node-globals\dist\rollup-plugin-node-globals.cjs.js:83:33)
    at Object.transform (D:\apps\MadnessLabsPWA\node_modules\rollup-plugin-node-globals\dist\rollup-plugin-node-globals.cjs.js:254:17)
  code: 'PLUGIN_ERROR',
  plugin: undefined,
  id: 'D:\\apps\\MadnessLabsPWA\\node_modules\\rollup-plugin-node-builtins\\src\\es6\\http-lib\\to-arraybuffer.js' }ffer.js' }
[45:11.7]  module map finished in 1.64 s

[ ERROR ]  Cannot read property 'type' of null
                                                                                                          9 at
[ ERROR ]  rollup died at D:\apps\MadnessLabsPWA\node_modules\@stencil\core\dist\compiler\index.js:17071:19 at
           Generator.throw (<anonymous>) at rejected
           (D:\apps\MadnessLabsPWA\node_modules\@stencil\core\dist\compiler\index.js:17030:65) at <anonymous>
[45:11.7]  build failed, watching for changes... in 4.28 s
preferring built-in module 'punycode' over local alternative at 'D:\apps\MadnessLabsPWA\node_modules\punycode\punycode.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warningpreferring built-in module 'punycode' over local alternative at 'D:\apps\MadnessLabsPWA\node_modules\punycode\punycode.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'string_decoder' over local alternative at 'D:\apps\MadnessLabsPWA\node_modules\string_decoder\lib\string_decoder.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warningpreferring built-in module 'string_decoder' over local alternative at 'D:\apps\MadnessLabsPWA\node_modules\string_decoder\lib\string_decoder.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
```

**Other information:**

**Comment by dmunicio** [comment]
It was solved in [https://github.com/ionic-team/stencil/issues/733](https://github.com/ionic-team/stencil/issues/733)

There they say that you should add this to your stencil.config.js
```
exports.config = {
  nodeResolve: {
    browser: true
  }
};
exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
};
```
