### ISSUE TITLE
Error during compilation w/ prerender parameter

### ISSUE THREAD

**Issue by ardatan** [ionic-team/stencil#800]
**Stencil version:**

```
  @stencil/core@0.8.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Stencil cannot compile with `--prerender`
```
$ stencil build --prerender
[59:46.7]  @stencil/core v0.8.2 🎡
[59:46.7]  build, app, prod mode, started ...
[59:46.7]  compile started ...
[59:49.2]  compile finished in 2.41 s
[59:49.2]  module map started ...
[59:49.8]  module map finished in 684 ms
[59:50.1]  generate bundles started ...
[59:51.4]  generate bundles finished in 1.25 s
[59:51.4]  generate app files started ...
[59:54.1]  generate app files finished in 2.78 s
[59:54.2]  prerendering started ...
[59:54.2]  prerender, started: / ...
[59:54.2]  prerender, finished: / in 46 ms
[59:54.2]  generate service worker started ...
[59:54.5]  prerendering failed in 328 ms
[59:54.5]  generate service worker finished in 293 ms

[ ERROR ]  TypeError: Parameter "url" must be a string, not undefined at Url.parse (url.js:103:11) at Object.urlParse
           [as parse] (url.js:97:13) at getWritePathFromUrl
           (/mnt/c/Users/ardat_000/my-app/node_modules/@stencil/core/dist/compiler/index.js:8658:38) at
           /mnt/c/Users/ardat_000/my-app/node_modules/@stencil/core/dist/compiler/index.js:13380:26 at Generator.next
           (<anonymous>) at /mnt/c/Users/ardat_000/my-app/node_modules/@stencil/core/dist/compiler/index.js:13250:71 at
           new Promise (<anonymous>) at __awaiter$35
           (/mnt/c/Users/ardat_000/my-app/node_modules/@stencil/core/dist/compiler/index.js:13246:12) at
           writePrerenderDest
           (/mnt/c/Users/ardat_000/my-app/node_modules/@stencil/core/dist/compiler/index.js:13378:12) at
           /mnt/c/Users/ardat_000/my-app/node_modules/@stencil/core/dist/compiler/index.js:13364:19

[ ERROR ]  Cannot find module 'request' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load
           (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at
           /mnt/c/Users/ardat_000/my-app/node_modules/request-promise-native/lib/rp.js:8:12 at module.exports
           (/mnt/c/Users/ardat_000/my-app/node_modules/stealthy-require/lib/index.js:62:23) at Object.<anonymous>
           (/mnt/c/Users/ardat_000/my-app/node_modules/request-promise-native/lib/rp.js:7:15) at Module._compile
           (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32)

[59:54.5]  build failed in 7.78 s

error Command failed with exit code 1.
````
**Expected behavior:**

Built successfully with prerendered HTML.

**Steps to reproduce:**

- Clone the stencil-app-starter repository
- Update `stencil` version.
- Run command `npm run build`
**Related code:**

```tsx
// insert any relevant code here
const express = require('express');
const stencil = require('@stencil/core/server');

// create the express app
const app = express();

// load the stencil config and
// express serve-side rendering middleware
console.log(stencil);
const {
  wwwDir,
  logger
} = stencil.initApp({
  app: app,
  configPath: __dirname
});

// serve static files
app.use(express.static(wwwDir));

// set which port express it will be listening on
const port = 3030;

// start listening and handling requests
app.listen(port, () => logger.info(`server-side rendering listening on port: ${ port }`));

```

**Other information:**

**Comment by AmitMY** [comment]
I have the same issue with the latest version of stencil. No clue why specifically so no idea how to replicate.

**Comment by OneMuppet** [comment]
I just started getting this error too after updating to: 
```
"@stencil/core": "0.12.4",
"@stencil/router": "0.2.6",
```

**Comment by Kiho** [comment]
Looks like problem is coming from @stencil/router, builds OK with @stencil/router v.0.2.5

**Comment by bitflower** [comment]
#1058 Error number 1 is the same:
`[ ERROR ]  TypeError: Parameter "url" must be a string, not undefined at Url.pars`

**Comment by bitflower** [comment]
@Kiho can't find router 0.2.6 ?

**Comment by Kiho** [comment]
@bitflower 
You can try this
```
  "dependencies": {
    "@stencil/core": "0.12.4",
    "@stencil/router": "0.2.5",
```

**Comment by bitflower** [comment]
Like I said, I have `0.2.5`

**Comment by adamdbradley** [comment]
This should be fixed in the most recent releases, thanks
