### ISSUE TITLE
Module 'resolve' cannot be found

### ISSUE THREAD

**Issue by marcus-sa** [ionic-team/stencil#820]
**Stencil version:**
```
@stencil/core@0.7.22
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
```
npm run dev

> @stencil/starter@0.0.1 dev /home/msa/Git/stencil-nest-example/client
> sd concurrent "stencil build --dev --watch" "stencil-dev-server" 

[51:27.3]  @stencil/core v0.7.22 ⛷
[51:27.3]  build, app, dev mode, started ...
[51:27.3]  compile started ...
[51:29.6]  compile finished in 2.33 s
[51:29.6]  module map started ...
[51:29.6]  module map finished in 17 ms

[ ERROR ]  Cannot find module 'resolve' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15) at
           Function.Module._load (internal/modules/cjs/loader.js:497:25) at Module.require
           (internal/modules/cjs/loader.js:626:17) at require (internal/modules/cjs/helpers.js:20:18) at
           Object.<anonymous>
           (/home/msa/Git/stencil-nest-example/client/node_modules/@stencil/core/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:10:15)
           at Module._compile (internal/modules/cjs/loader.js:678:30) at Object.Module._extensions..js
           (internal/modules/cjs/loader.js:689:10) at Module.load (internal/modules/cjs/loader.js:589:32) at
           tryModuleLoad (internal/modules/cjs/loader.js:528:12) at Function.Module._load
           (internal/modules/cjs/loader.js:520:3)
```

**Expected behavior:**
The web application would build and initialize using `npm` without the error. 
Works fine using `yarn`

**Steps to reproduce:**
Simply clone the starter repository `https://github.com/ionic-team/stencil-app-starter`, run `npm install` and then `npm run dev`

**Comment by jthoms1** [comment]
After update the issue should be resolved.
