### ISSUE TITLE
Running Build Generate an error (Windows 10)

### ISSUE THREAD

**Issue by tonyawad88** [ionic-team/stencil#907]
**Stencil version:**

```
@stencil/core@0.10.0-11
```

**I'm submitting a:**
[X] bug report

**Current behavior:**
Running `npm run build` produces the following error, this error also happens with version 0.9.11.
```
[ ERROR ]  runtime console.error: /
           Error: getaddrinfo ENOTFOUND prerender.stenciljs.com prerender.stenciljs.com:80 at Object.dispatchError
           (...\node_modules\jsdom\lib\jsdom\living\xhr-utils.js:65:19) at
           Request.client.on.err
           (...\node_modules\jsdom\lib\jsdom\living\xmlhttprequest.js:664:20)
           at emitOne (events.js:121:20) at Request.emit (events.js:211:7) at Request.onRequestError
           (...\node_modules\jsdom\node_modules\request\request.js:877:8) at
           emitOne (events.js:116:13) at ClientRequest.emit (events.js:211:7) at Socket.socketErrorListener
           (_http_client.js:387:9) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7),
```

**Expected behavior:**
Build succeeds with dist files.

**Steps to reproduce:**
Run the following command twice: `npm run build`

**Related code:**

```tsx
// N/A
```

**Comment by adamdbradley** [comment]
great thanks for testing!
