### ISSUE TITLE
Stencil 11 - sass is not a function TypeError: sass is not a function at Object.<anonymous>

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil#985]
**Stencil version:**

```
@stencil/core@0.11.0
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Crash

**Expected behavior:**
Build and run

**Steps to reproduce:**

**Related code:**

```tsx
C:\ae\adaept.com\ae-svg-components>npm list @stencil/core
ae-svg-components@0.0.8 C:\ae\adaept.com\ae-svg-components
`-- @stencil/core@0.11.0


C:\ae\adaept.com\ae-svg-components>npm start

> ae-svg-components@0.0.8 start C:\ae\adaept.com\ae-svg-components
> npm run dev


> ae-svg-components@0.0.8 dev C:\ae\adaept.com\ae-svg-components
> stencil build --dev --watch --serve


[ ERROR ]  sass is not a function TypeError: sass is not a function at Object.<anonymous>
           (C:\ae\adaept.com\ae-svg-components\stencil.config.js:18:5) at Module._compile (module.js:652:30) at
           Object.require.extensions..js
           (C:\ae\adaept.com\ae-svg-components\node_modules\@stencil\core\dist\sys\node\index.js:766:20) at Module.load
           (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at
           Module.require (module.js:596:17) at require (internal/module.js:11:18) at requireConfigFile
           (C:\ae\adaept.com\ae-svg-components\node_modules\@stencil\core\dist\sys\node\index.js:773:20) at
           loadConfigFile (C:\ae\adaept.com\ae-svg-components\node_modules\@stencil\core\dist\sys\node\index.js:717:32)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ae-svg-components@0.0.8 dev: `stencil build --dev --watch --serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ae-svg-components@0.0.8 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\peter\AppData\Roaming\npm-cache\_logs\2018-08-02T04_58_39_419Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ae-svg-components@0.0.8 start: `npm run dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ae-svg-components@0.0.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\peter\AppData\Roaming\npm-cache\_logs\2018-08-02T04_58_39_446Z-debug.log

C:\ae\adaept.com\ae-svg-components>
```

**Other information:**

This works: 
https://github.com/peterennis/ae-svg-components
Builds this:
https://aesvg.adaept.com/
Using this:
```
    "@stencil/core": "~0.10.9",
    "@stencil/sass": "0.0.5",
```

This will crash with above error:
```
    "@stencil/core": "~0.11.0",
    "@stencil/sass": "0.1.0",
```

**Comment by kensodemann** [comment]
Did you update your `stencil.config.js` (or even better, convert it to a `stencil.config.ts`) as per the CHANGELOG? https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#-0110-2018-07-31

**Comment by mattcosta7** [comment]
The sass import changed from 005 to 010

Now it should be either 

const { sass } = require.....
Or 
import { sass } from.....

Instead of the same without the curly brackets

**Comment by peterennis** [comment]
@kensodemann 
I changed to stencil.config.ts and it needed some other changes
here: https://github.com/peterennis/ae-svg-components/commit/7bcfa1887a821d186d1faeb1d3ebb041f23a056d
running again here: https://aesvg.adaept.com/

Thanks!
