### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by rstevens354** [ionic-team/stencil#99]
> @stencil/starter@0.0.1 start C:\xampp\htdocs\my-app
> npm run dev

> @stencil/starter@0.0.1 dev C:\xampp\htdocs\my-app
> sd concurrent "stencil build --dev --watch" "stencil-dev-server"

C:\xampp\htdocs\my-app\node_modules\@stencil\utils\dist\utils\promisify.js:10
            func(...args, (err, response) => {
                 ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\xampp\htdocs\my-app\node_modules\@stencil\utils\di
st\index.js:16:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by john-landgrave** [comment]
Not an expert, but it looks like your node doesn't understand the es6 rest operator. Is your node up to date?

**Comment by rstevens354** [comment]
I upgraded node to latest and all works ok,

will there be more indepth 'docs' as would like to know more around using JS alongside the rendered html to access the {tag values}

**Comment by john-landgrave** [comment]
Awesome @rstevens354, glad that worked!

**Comment by jgw96** [comment]
@rstevens354 out of curiosity, what version of node where you running when you had the issue?
